### ISSUE TITLE
Need help for translating Kaguya engine games

### ISSUE THREAD

**Issue by Docs17** [satan53x/SExtractor#101]
Thank you for your great tools!

However, I have encountered an issue where, after repacking, some versions of the KAGUYA engine fail during the execution process.

![image](https://github.com/user-attachments/assets/4dcaac05-7c98-4954-b544-26792fea5e12)

I tried translating the game into Korean, and while the repacking worked fine, when I attempt to run it in a Korean locale, the following error occurs. 

![image](https://github.com/user-attachments/assets/d2c32585-9e6b-493a-9bb5-bcf39f4fa98d)

Normally, this screen should be displayed.

The strange Korean errors mentioned earlier are due to S-JIS characters being forcibly displayed in EUC-KR encoding, which indicates a registry-related issue. Naturally, the game runs perfectly and the installation completes successfully in a Japanese locale.

However, Games from Kaguya Chesire Cat Studio, including Shibora Renkare Keiyaku and other recent titles (2020 and onwards), run perfectly fine in a Korean locale.

The game now i'm testing is アまヤカシな彼女.

![image](https://github.com/user-attachments/assets/7373eae7-d678-4599-bdfd-c0df506148a9)

When I run the game in a Japanese locale, the Korean text does not display correctly, as shown in the attached image. Given that the games I previously translated using your tool (such as Isekai Monmus Sensation) also do not display properly in a Japanese locale, there seems to be a specific logic causing this issue.

![image](https://github.com/user-attachments/assets/346b9e87-ddc5-408b-856e-7d7783c47d94)

As shown in the Upper image, the game executable (.EXE) has already been modified to display Korean text correctly. Games like Shibora Renkare Keiyaku and others can display Korean text properly with just this modification.

I once again send my compliments to your powerful tool.

**Comment by satan53x** [comment]
If wanna import with Korean encoding, you can see this: 
https://github.com/satan53x/SExtractor/issues/35#issuecomment-1972460745
Modify `self.NewEncodeName = 'gbk'` to `self.NewEncodeName = 'cp949'` in `src/var_extract.py`

**Comment by Docs17** [comment]
Thanks for your comment.
Unfortunately, i already did that but same error also occurs.

![image](https://github.com/user-attachments/assets/64d5d0c0-d6d0-49f2-b009-bb7aa4109e05)

I think.... it need same locale with translated language. or need new way to print them.

**Comment by satan53x** [comment]
Yes. If the text and `CreateFontIndirect` have been changed to Korean, then the Japanese environment should not be used. 
It should only function properly under the conditions where the language and region settings are Korean too.

**Comment by satan53x** [comment]
> I tried translating the game into Korean, and while the repacking worked fine, when I attempt to run it in a Korean locale, the following error occurs.

If you cannot run in Korean, try edit the `ini` config. (Maybe the name is `アまヤカシな彼女.ini`)
```
[PATH]
SetupType="1"
Current="./"
CDDrive="Z:\"
```
The point is `Current`.

**Comment by Docs17** [comment]
OMG, it works!

After adding the アまヤカシな彼女.ini file from the installation folder, it finally worked. Thank you so much for your help!
