### ISSUE TITLE
Cyberworks不支持注解的格式

### ISSUE THREAD

**Issue by wjh191** [satan53x/SExtractor#102]
原文是这样的：
<img src="https://imglink.win/image/2024/09/01/xHzDZ.png" alt="屏幕截图 2024 09 01 003358" border="0">

SE导出后的：
> その全員の視線が、堂々と遅刻してきたÿÿ\u0004あいはら\u0002相原ÿÿ\u0003あんり\u0002杏里に注がれた。

\u0004这些数字应该是指后面的文本长度。

这是游戏脚本：
https://www.123pan.com/s/muyGjv-4AN4h

虽然感觉只要翻译前修正一下就行，但总归是个问题，所以跟大佬报告一下。

**Comment by satan53x** [comment]
恩，这个是文本自带的控制字节，属于文本逻辑，不会由脚本处理，可以修改正则处理（因为不同版本有细微差别，所以没有写到默认里）：
https://github.com/satan53x/SExtractor/issues/7#issuecomment-1732512209

不想改正则可以随便用个文本编辑器批量处理json。
要转换开头的两个字节乱码，可以在正则里加上keepBytes=\xFF\xFF
