### ISSUE TITLE
提取 MV/MZ 文本时，关于 json 文件解析的两个问题

### ISSUE THREAD

**Issue by neavo** [satan53x/SExtractor#103]
如题

在提取 RPGMaker MV/MZ 的 .json 文件时，经常会出现解析错误而报错从而停止提取流程的问题。

这里有两个问题：

1、打开程序提示报错的文件，发现似乎是合法的json文件，并没有发现什么格式错误，不知道这是否是程序的BUG，能否修复？

2、能否提供一个跳过报错文件继续进行的功能，因为大部分时候这些报错的数据文件都是应用的配置文件，并不包含文本，出错以后直接跳过这个文件实际上也不影响提取结果。

附上一个示例：

[data.zip](https://github.com/user-attachments/files/16834711/data.zip)

![QQ截图20240902161312](https://github.com/user-attachments/assets/77944bcb-6966-4593-be75-d8131574e363)

**Comment by satan53x** [comment]
我试了下没有报错，你应该是编码没选对，你文件是带BOM签名的，编码要选UTF-8-SIG。
顺便说明一下，如果是UTF-16-LE BOM的话是选UTF-16，而不是utf-16-le（这个不带BOM）。

**Comment by satan53x** [comment]
又看了下，好像你这些json一些带BOM一些不带，建议直接把不需要的移走，不然即使选UTF-8-SIG也会有问题，new里都会变成带BOM的

**Comment by neavo** [comment]
> 又看了下，好像你这些json一些带BOM一些不带，建议直接把不需要的移走，不然即使选UTF-8-SIG也会有问题，new里都会变成带BOM的

对的，我现在就是这么操作的，把报错的手动移走，提完了再移回来，但是这样挺麻烦的，还容易误操作

如果能只报错而不中断任务，那就简单多了

**Comment by satan53x** [comment]
> 对的，我现在就是这么操作的，把报错的手动移走，提完了再移回来，但是这样挺麻烦的，还容易误操作

不用移动回来，你直接放new里就行，导入的时候并不会清空new文件夹。

**Comment by neavo** [comment]
> > 对的，我现在就是这么操作的，把报错的手动移走，提完了再移回来，但是这样挺麻烦的，还容易误操作
> 
> 不用移动回来，你直接放new里就行，导入的时候并不会清空new文件夹。

主要我只用 SExtractor 来提文本用于抓词表，并不使用本应用的翻译导入功能，所以得还原回原始的文件结构，以方便其他应用处理

**Comment by satan53x** [comment]
加了，但目前只会忽略提取时异常。

**Comment by neavo** [comment]
> 加了，但目前只会忽略提取时异常。

超棒，爱你 😁
