### ISSUE TITLE
正则表达式捕捉错误

### ISSUE THREAD

**Issue by bqwert0** [satan53x/SExtractor#104]
如果用custom的正则表达式无法正确的捕抓文字
会捕抓到前一个文字
举例:

使用
01_search=text="([^"]*)"
捕抓
[text="test_text"]

会捕抓到
\"test_tex 
而不是 
test_text

似乎往前位移一个字元

我用之前的版本就没有这个问题能正确捕抓到
test_text

**Comment by satan53x** [comment]
昨天刚更新出的BUG，再更新一下，刚修复了。

**Comment by bqwert0** [comment]
恩
修好了

thanks
BTW
引擎到底是啥意思

**Comment by bqwert0** [comment]
跟選正則
差別在哪阿

**Comment by satan53x** [comment]
和正则不是区别而是相互配合。
比如你引擎选TXT就是按换行符分割文本，然后再进行正则提取。
但是只有kirikiri之类的引擎才是纯文本的剧本。像yuris之类的都是二进制剧本结构，里边有指令和文本，所以需要选引擎来只匹配文本所在的字符串。
所以不同引擎就是不同分割剧本文件的方法，然后才能进行正则。

**Comment by bqwert0** [comment]
喔終於懂了

BTW
可以把用的正則存在ctrl資料夾裡面嗎?
如果使用custom的就把custom的正則也存在裡面

不知道為啥我每次遇到的krkr的語法都不一樣
都要自己寫但是很容易寫完重開正則就沒了
回都猜自己寫了啥太痛苦了
猜錯翻譯又要重搞

**Comment by satan53x** [comment]
custom不是本来就会保存吗？为啥会打开就没有了？
然后就是，设置里边默认应该是勾上了`自动缓存config.ini`的啊，然后提取目录右边`选择文件夹`之后就会在ctrl里生成。
可能你SE版本比较旧？

**Comment by bqwert0** [comment]
custom 的會被覆蓋掉吧
在用不同的正則的情況下

而且我遇過幾次莫名不見
不知道是不是我手殘點到什麼了

**Comment by bqwert0** [comment]
恩確定沒問題了
我去看config.ini有記錄到正則
之前不知道是怎樣手殘@@
可close掉了
謝謝
