### ISSUE TITLE
提取并翻译后重新写入，不知为何出现立绘丢失问题。

### ISSUE THREAD

**Issue by Hummycookies** [satan53x/SExtractor#105]
![2](https://github.com/user-attachments/assets/eafb5a4c-4878-4936-9671-c813ebf51c1d)
![1](https://github.com/user-attachments/assets/d6611279-7c07-48e5-8793-1d424d35d6c9)
问题如图，提取和写入用的都是RPGMV的默认设置，格式为name-message。部分立绘正常，部分立绘丢失。
附原json和新json
[Map020orin.json](https://github.com/user-attachments/files/17063744/Map020orin.json)
[Map020trans.json](https://github.com/user-attachments/files/17063745/Map020trans.json)

**Comment by satan53x** [comment]
>![1](https://private-user-images.githubusercontent.com/182137561/369108591-d6611279-7c07-48e5-8793-1d424d35d6c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MTE5NzAsIm5iZiI6MTcyNjgxMTY3MCwicGF0aCI6Ii8xODIxMzc1NjEvMzY5MTA4NTkxLWQ2NjExMjc5LTdjMDctNDhlNS04NzkzLTFkNDI0ZDM1ZDZjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQwNTU0MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDk5ZjNlZGE4MDA5ZWRhN2YxMDhiN2I1NWQ3NDIxODlmYjQyY2I1ZDI3M2EzODk1N2Q0MGEwM2YyOWVkNWM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IfLNbO-f3x1lwxxr_rOMoscyi8YVROQPDRmhuugPEnA) 

默认正则和你的这个名字结构不一样啊，所以应该是名字前边的代码被翻译错误了。
比如`\\F[beni_smile]\\FF[hanasaku_laugh]\\AA[1]紅`这种，前边就是立绘代码`\\F`或者`\\FF`肯定是不能被乱翻译的。
或者是修改正则一开始就不提取这些代码：
```
15_search=^<code401>[ -~]*\\AA\[\d+\](?P<name>.+)$
```

**Comment by Hummycookies** [comment]
> > ![1](https://private-user-images.githubusercontent.com/182137561/369108591-d6611279-7c07-48e5-8793-1d424d35d6c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MTE5NzAsIm5iZiI6MTcyNjgxMTY3MCwicGF0aCI6Ii8xODIxMzc1NjEvMzY5MTA4NTkxLWQ2NjExMjc5LTdjMDctNDhlNS04NzkzLTFkNDI0ZDM1ZDZjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQwNTU0MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDk5ZjNlZGE4MDA5ZWRhN2YxMDhiN2I1NWQ3NDIxODlmYjQyY2I1ZDI3M2EzODk1N2Q0MGEwM2YyOWVkNWM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IfLNbO-f3x1lwxxr_rOMoscyi8YVROQPDRmhuugPEnA)
> 
> 默认正则和你的这个名字结构不一样啊，所以应该是名字前边的代码被翻译错误了。 比如`\\F[beni_smile]\\FF[hanasaku_laugh]\\AA[1]紅`这种，前边就是立绘代码`\\F`或者`\\FF`肯定是不能被乱翻译的。 或者是修改正则一开始就不提取这些代码：
> 
> ```
> 15_search=^<code401>[ -~]*\\AA\[\d+\](?P<name>.+)$
> ```
我一共找到四种name的样式，但第一种没有控制符号的我无法和正文区分，请问有什么解决方案吗？
1.{"code":401,"indent":0,"parameters":["綿"]}
2.{"code":401,"indent":0,"parameters":["\\F[wata_kamen]綿"]}
3.{"code":401,"indent":1,"parameters":["\\FF[nako_true]撫子"]}
4.{"code":401,"indent":0,"parameters":["\\F[wata_kamen]\\FF[beni_kamenoti]\\AA[2]紅"]}
正文：{"code":401,"indent":0,"parameters":["「ねぇ？私のここに手を触れて？"]}

**Comment by satan53x** [comment]
方案一：设置`强制设定名字`栏，用英文逗号隔开：`单独名字1,单独名字2`。
方案二：如果能保证`「`之前一定是名字的话也可以改成这样：
```
15_search=^<code401>\\F[ -~]+(?P<name>.+)$
16_search=^<code401>(?P<unfinishANDpre_name>「[\S\s]+)$
17_search=^<code401>(?P<unfinish>[\S\s]+)$
```

**Comment by Hummycookies** [comment]
> 方案一：设置`强制设定名字`栏，用英文逗号隔开：`单独名字1,单独名字2`。 方案二：如果能保证`「`之前一定是名字的话也可以改成这样：
> 
> ```
> 15_search=^<code401>\\F[ -~]+(?P<name>.+?)$
> 16_search=^<code401>(?P<unfinishANDpre_name>「[\S\s]+)$
> 17_search=^<code401>(?P<unfinish>[\S\s]+)$
> ```

通过强制命名解决，感谢您的帮助。
