### ISSUE TITLE
There is an issue with the CSystemArc tool. Please help.

### ISSUE THREAD

**Issue by fushi002** [satan53x/SExtractor#108]
Hello,

First of all, I understand that this may be an impolite question since this isn’t code you wrote yourself, but I hope for your understanding.

I would like to modify the Arc00.dat file to change the font size and title of a game developed with CSystem. However, when I run readconfig.bat, an error occurs stating that invalid data was found during decoding.

This issue occurs with both of the recently released games.

I’ve attached two sample files. When you have time, could you please take a look at them?
[CSystemArc00.zip](https://github.com/user-attachments/files/17126699/CSystemArc00.zip)

Thank you as always.

**Comment by satan53x** [comment]
Updated.
You need an extra command param: `CSystemArc readconfig Arc00.dat config.xml 24`.

**Comment by fushi002** [comment]
Everything works perfectly now!
Thank you so much for your quick help :)
