### ISSUE TITLE
可以增加一个与提取相关的功能吗

### ISSUE THREAD

**Issue by singiaoba** [satan53x/SExtractor#109]
search=^(?P\<message\>「.\*」)$
search=^(?P<pre_messageANDunfinish>「.\* )$
例如这样，把被「」包裹的内容提取为message

用这个把指定的内容提取为name
search=(?P\<name\>アオ|カレン)$

我想提高name提取的精确度
能不能实现提取name时
且name的后一行一定是
search=^(?P\<message\>「.\*」)$
search=^(?P\<pre_messageANDunfinish\>「.\* )$
所有提取的内容
如果不是则提取为message

**Comment by satan53x** [comment]
你这需求描述得不明确啊，如果「之前都是名字，那直接pre_name就行了。
如果你是说名字之后可能有名字，对话，旁白这三种，那只能区分两种。因为不同文本之间只能感知分组名，旁白和对话的话在分组上都是message。

没看到你的剧本格式，纯文本的话可以用跨行提取来确定提取内容。选BIN引擎再勾上纯文本模式，然后separare=任意不会被匹配的字符串就行。

**Comment by singiaoba** [comment]
例如这样的文本
```
のの
「一二三四」
のの
ちゃん
一二三四
```
如果我用这个提取
```
search=(?P<name>のの)$
search=^(?P<message>「.*」)$
search=^(?P<unfinish>.+)$
```
会变成这样
```json
[
{
  "name": "のの",
  "message": "「一二三四」"
},
{
  "name": "のの",
  "message": "ちゃん\r\n一二三四"
}
]
```
我想处理成这样
```json
[
{
  "name": "のの",
  "message": "「一二三四」"
},
{
  "message": "のの\r\nちゃん\r\n一二三四"
}
]
```

**Comment by satan53x** [comment]
如果能保证「前边全是名字直接用pre_name就行，pre_name这种分组名需要加参数`struct=para`才能生效（`structure=paragraph`也行）
```
15_search=^(?P<pre_name>「.+」)$
20_search=^(?P<unfinish>.+)$
struct=para
```

**Comment by satan53x** [comment]
如果要自行指定名字的话，可以用predel_name来取消之前的name。
不过需要更新一下SE，之前默认name分组是无法del的。
```
10_search=^(?P<name>のの)$
15_search=^(「.+」)$
20_search=^(?P<unfinishANDpredel_name>.+)$
struct=para
```

**Comment by singiaoba** [comment]
谢谢，我这就去试一试
