### ISSUE TITLE
Valkyria引擎

### ISSUE THREAD

**Issue by TXT2GAM** [satan53x/SExtractor#11]
在正则预设里看到了`Valkyria_ODN`，问一下这个引擎的游戏有封包或者免封包的方法吗？
在网上没找到相关信息

**Comment by satan53x** [comment]
封odn包用我改过的[Garbro](https://github.com/satan53x/GARbro/releases/tag/v1.5.44-d3)。
不过不清楚是不是对所有odn版本都生效。

**Comment by TXT2GAM** [comment]
感谢！对于我遇到的这个游戏也适用
不过这个引擎也太冷门了...

**Comment by satan53x** [comment]
如果不是找不到封包工具，谁愿意自己写呢。

**Comment by satan53x** [comment]
我记得我之前那个游戏文本长度是可变的，不需要相等。
译文\r\n是分割段落用的，最好不要删除。虽然有的游戏删除\r\n不影响运行，因为他们的文本会自动换行。
但是这个引擎貌似是有每行长度限制，就是文本窗口显示宽度。
不过我是在运行到超长的文本时才会闪退，没有出现过一开始就闪退。
如果是因为GPT翻译掉了\r\n，可以手动添加，也可以在设置里尝试启用`重新分割`功能，就会尽量还原长度。
旁边的`每行最大字符数`可以设置每行最大长度，但并不会截断修改文本，只是个打印提示。

**Comment by satan53x** [comment]
不一定需要重新翻译，你开启`重新分割`试试就行，会按照原文的行数和长度进行等比例就近分割，分割位置默认是匹配标点符号。
我之前是在日文时直接文本窗口人工数的字数。

**Comment by tcg279** [comment]
> 如果不是找不到封包工具，谁愿意自己写呢。



> 封odn包用我改过的[Garbro](https://github.com/satan53x/GARbro/releases/tag/v1.5.44-d3)。 不过不清楚是不是对所有odn版本都生效。

佬，我用你这个回封原包。打开游戏有如下bug 1.游戏标题界面全黑，但移动鼠标还能听到选择开始和读档的音效，点击也能进游戏。2.有概率会一直重复游戏log画面连标题都进不去。3.我把开头的文本翻了塞回去封包测试打开游戏直接跳到其他sence（连游戏标题页面都直接跳过了）。游戏名是吸尻鬼 ～アナル姫肛姦調教録～。我用原本odn封包文件不会出现bug可以排除游戏资源损坏问题。用garbro解原包再封原包会出现以上bug（解的是文本包）。

**Comment by satan53x** [comment]
> > 封odn包用我改过的[Garbro](https://github.com/satan53x/GARbro/releases/tag/v1.5.44-d3)。 不过不清楚是不是对所有odn版本都生效。
> 
> 佬，我用你这个回封原包。打开游戏有如下bug 1.游戏标题界面全黑，但移动鼠标还能听到选择开始和读档的音效，点击也能进游戏。2.有概率会一直重复游戏log画面连标题都进不去。3.我把开头的文本翻了塞回去封包测试打开游戏直接跳到其他sence（连游戏标题页面都直接跳过了）。游戏名是吸尻鬼 ～アナル姫肛姦調教録～。我用原本odn封包文件不会出现bug可以排除游戏资源损坏问题。用garbro解原包再封原包会出现以上bug（解的是文本包）。

有可能，因为garbro解包odn的时候其实有3个版本，我封包只写了第3版，所以我才说不一定适配所有odn。
你把原始文本odn包发出来看看呢。

**Comment by tcg279** [comment]
> > > 封odn包用我改过的[Garbro](https://github.com/satan53x/GARbro/releases/tag/v1.5.44-d3)。 不过不清楚是不是对所有odn版本都生效。
> > 
> > 
> > 佬，我用你这个回封原包。打开游戏有如下bug 1.游戏标题界面全黑，但移动鼠标还能听到选择开始和读档的音效，点击也能进游戏。2.有概率会一直重复游戏log画面连标题都进不去。3.我把开头的文本翻了塞回去封包测试打开游戏直接跳到其他sence（连游戏标题页面都直接跳过了）。游戏名是吸尻鬼 ～アナル姫肛姦調教録～。我用原本odn封包文件不会出现bug可以排除游戏资源损坏问题。用garbro解原包再封原包会出现以上bug（解的是文本包）。
> 
> 有可能，因为garbro解包odn的时候其实有3个版本，我封包只写了第3版，所以我才说不一定适配所有odn。 你把原始文本odn包发出来看看呢。
已上传，麻烦大佬了
[data02.zip](https://github.com/user-attachments/files/18475654/data02.zip)

**Comment by satan53x** [comment]
> > 已上传，麻烦大佬了
> > [data02.zip](https://github.com/user-attachments/files/18475654/data02.zip)

我看了下，是第3版的啊。
而且我试了，解压后不修改，直接压缩，进行新旧包二进制比较，是完全一样的。
确定你只解压压缩了文本包？只支持文本包的。

**Comment by tcg279** [comment]
> > > 已上传，麻烦大佬了
> > > [data02.zip](https://github.com/user-attachments/files/18475654/data02.zip)
> 
> 我看了下，是第3版的啊。 而且我试了，解压后不进行任何编辑修改，直接压缩，进行新旧包二进制比较，是完全一样的。 确定你只解压压缩了文本包？只支持文本包的。
是的我确定为此我还重新操作录了一遍视频bug还是存在，麻烦大佬看一下。

**Comment by tcg279** [comment]
> > > 已上传，麻烦大佬了
> > > [data02.zip](https://github.com/user-attachments/files/18475654/data02.zip)
> 
> 我看了下，是第3版的啊。 而且我试了，解压后不进行任何编辑修改，直接压缩，进行新旧包二进制比较，是完全一样的。 确定你只解压压缩了文本包？只支持文本包的。

你只解压压缩了文本包？只支持文本包的。
是的我确定为此我还重新操作录了一遍视频bug还是存在，麻烦大佬看一下。
可能是内容太大GitHub上无法上传成功，我传到百度盘了 
https://pan.baidu.com/s/1DWPL1XNviF9JbYVqBA2dUw?pwd=3a7y

**Comment by satan53x** [comment]
你把你用的garbro和新创建的那个odn发来看看呢？

**Comment by tcg279** [comment]
> 你把你用的garbro和新创建的那个odn发来看看呢？
> 
> 不用了，我复现了你的操作。

是我的操作问题，还是工具的问题呢？

**Comment by tcg279** [comment]
> 你打包的时候不要选中任意一个脚本，进文件夹就直接ctrl+a，右边不要有脚本显示。 或者是你直接在上一层对着文件夹打包就行。 这个应该是garbro自身的问题，选中打包好像有BUG，可能。

还真是，没想到是这样。感谢大佬的解答谢谢谢谢谢谢！！！！

**Comment by fushi002** [comment]
It seems that the character limit for translating games using this engine is quite restrictive.
If it were possible to adjust the font size or increase the number of characters displayed per line by widening the message area, I believe it could resolve this issue. Would such adjustments be technically challenging to implement?

I noticed that there are quite a few text-based scripts in files like data02, data03, and data06, but I couldn’t find the specific configuration or settings to make these changes. Perhaps I might have overlooked something.

The game in question is based on ODN version 3.

Thank you as always for your support!

**Comment by satan53x** [comment]
Generally speaking, the font size of many Japanese games does not change the number of words per line. When the font size is reduced, the spacing between words will increase.
This may be a problem with the `exe`, and may not be achieved to achieve this by changing the the script file or odn package.
Haven't tried changing the font width of `Valkyria` engine, maybe you can try with some dll tools to test, such as:
https://github.com/marcussacana/StringReloads
Or `UIF` that I modified: [tools/UIF](https://github.com/satan53x/SExtractor/tree/main/tools/UIF) to set `override_width`

**Comment by Cosetto** [comment]
@fushi002 I managed to pull off [this game](https://vndb.org/v19908) with [the hook](https://github.com/Cosetto/Netorenai/tree/main/FixMessage_hook)
<img width="1090" height="844" alt="Image" src="https://github.com/user-attachments/assets/6521a99a-8b57-48dc-8e20-d7f0b7d0eb0b" />
