### ISSUE TITLE
关于多行文本正则的问题请教

### ISSUE THREAD

**Issue by wjh191** [satan53x/SExtractor#112]
大佬请教一下，像这种多行文本：
```
砂州賀
「僕ね、
さすが
砂州賀
っていうんだ」
```
该怎么提取成这种：
```
    "name": "砂州賀",
    "message": "「僕ね、\r\nさすが\r\n砂州賀\r\nっていうんだ」"
```

一开始我用的是：
```
05_skip=^$|^[\x20-\x7E]+$
10_search=^(?P<pre_name>「.+」)$
66_search=^(?P<pre_nameANDunfinish>「(?!.*」).*)$
67_search=^(?P<pre_unfinish>.+)(?<=」)$
68_search=^(?P<unfinish>.+)
```
但它会把选项这些没有特殊标识的文本也提取到一行。

**Comment by satan53x** [comment]
这个需要用BIN跨行，确实比较麻烦，你更新一下，我加了2个新的分组名可以不用跨行分割。
```
05_skip=^$|^[\x20-\x7E]+$
10_search=^(?P<pre_name>「.+」)$
66_search=^(?P<pre_nameANDstart_unfinish>「.*)$
67_search=^(?P<end_unfinish>.*」)$
68_search=^(.+)$
struct=para
```
根据你这个改的，主要就是把66和67用区间进行表示：从`「`的行开始start_unfinish；到`」`的行结束end_unfinish（不含这一行，这一行不会被设置为unfinish）。
`struct=para`是`structure=paragraph`的简写。

**Comment by satan53x** [comment]
这一行没匹配上：`博士は……、博士は、り……利用され……て……しまう……こと、に……」”`
行尾可能会有个引号：`13_search=^(?!.*「)(?P<end_unfinish>.+?」)”?$`
`”?`等效于`”{0,1}`

在json里搜”就知道哪些漏掉了。
比如有些句子开头也需要加个全角空格或者全角引号的匹配，比如`12_search=^　?”?(?P<name>.+)(?P<start_unfinish>「(?!.*」).+)$`

**Comment by satan53x** [comment]
> 感谢，我以为start_unfinish和unfinish一样skip后就不会保留了，就没太注意。

确实应该这样好些，我待会儿改下默认设定。

**Comment by satan53x** [comment]
更新了，现在默认skip也会中断start_了。
如果要想不中断可以用postSkip，或者是search里边排除。

**Comment by satan53x** [comment]
中断你用end_unfinish分组不就行了吗？start_和end_并不限制个数。
而且你这个需求的话直接用单纯unfinish就行，不需要start_和end_。

**Comment by satan53x** [comment]
end_只代表中断，你还需要加predel `end_unfinishANDpredel_unfinish`

**Comment by satan53x** [comment]
其实照你这个说法，就不需要用start_和end_来判断，因为你有行首是否有空格的信息：
```
05_skip=^$|^[\x20-\x7E　]+$
10_search=^　?”?(?P<name>.+)(「[^」]+」?)”?$
13_search=^　(?P<predel_unfinish>.+)”?$
20_search=^(?P<pre_unfinish>.+)$
struct=para
pureText=1
```
就是只有行首没有空格的时候才可能存在前一个是unfininsh。
当然，是在10_search已经匹配了带名字的行之后。
