### ISSUE TITLE
一个文本导入问题想要请教。

### ISSUE THREAD

**Issue by jianghuplayerW** [satan53x/SExtractor#113]
大佬，想向您询问一个krkr引擎文本导入的问题，在将翻译完毕的文本通过SE重新导入回的过程中，我发现SE窗口中的报错：
1、'gbk' codec can't encode character '\u266a' in position 0: illegal multibyte sequence
2、TypeError: can only concatenate str (not "bool") to str
本人新人小白一个，暂时不知道这两个问题究竟因何而起，所以想问问您有没有相关解决方法，或者知道它们出现的原因，还望指点一二。

**Comment by satan53x** [comment]
krkr大部分都支持utf-16-le bom，你需要先自己把ks剧本转为utf-16-le bom，然后提取时在SE右下角选编码utf-16。（提取出的json和之前并没有区别）

**Comment by jianghuplayerW** [comment]
大佬，您的意思是在提取文本前就将日文原ks转换为utf-16-le bom编码，然后再提取，翻译导入吗？

**Comment by jianghuplayerW** [comment]
而且，不论我如何修改日文原文本ks文件的编码还是修改译文的编码，始终报错UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte。可我明明把编码改成了utf-16 le bom了

**Comment by satan53x** [comment]
SE里右下角选utf-16了吗？

**Comment by jianghuplayerW** [comment]
选择了，需要我把截图发给您分析吗？

**Comment by satan53x** [comment]
你发界面截图和报错截图呢

**Comment by jianghuplayerW** [comment]
![SE提取出来的文本](https://github.com/user-attachments/assets/922b1ee5-c325-4182-aaf0-c304db817589)
![日文脚本](https://github.com/user-attachments/assets/0e8788b2-5bb3-4027-9eb4-e72502705b88)
![译文](https://github.com/user-attachments/assets/cbc682c8-e4da-4249-95b2-0ed0aa7c74e0)
![运行的情况](https://github.com/user-attachments/assets/471ec45d-4976-48f0-b253-d5adc79011af)

**Comment by satan53x** [comment]
只转一次原始ks剧本的编码，不要转orig或trans里json的编码。（导入后的new里边ks也不用转，游戏可以识别）

**Comment by jianghuplayerW** [comment]
依照大佬所言，确实没问题，但是报错内容变化了：
![image](https://github.com/user-attachments/assets/7071c7ee-d049-4ff5-8a00-3022be797aaf)

**Comment by jianghuplayerW** [comment]
![image](https://github.com/user-attachments/assets/edbfa43b-c297-496b-a74d-71c4c5951bf1)
这个报错昨晚我也出现过，但是我不记得文本中存在bool值的问题.......还是说设置中需要一些设置？
![image](https://github.com/user-attachments/assets/4119bcc6-184c-4928-b365-d639598189f2)

**Comment by satan53x** [comment]
TXT模式一般别开截断，截断会进行jis和gbk编码验证。

**Comment by jianghuplayerW** [comment]
好的，辛苦大佬指点了。
