### ISSUE TITLE
在汉化恋の恋时，仍然遇到选项闪退问题

### ISSUE THREAD

**Issue by hhj2004563** [satan53x/SExtractor#115]
和之前的AI补丁制作者有过联络，从他那里得到了非常好的经验，但是在实际翻译过程中还是遇到了一些问题，还望大佬能帮忙答疑解惑一番！

首先是采用的正则和设置：
![1729077498309](https://github.com/user-attachments/assets/a6c0a1c6-a74e-441f-bb37-0877cf5caf81)
![1729077524886](https://github.com/user-attachments/assets/420e45b0-9d63-4db2-9d3f-d074dcde210c)
接着是参数文件：
[参数.txt](https://github.com/user-attachments/files/17394788/default.txt)
然后利用dat_pack来进行封包：
![31f2eaaecae4f675e5ad720b496666b2](https://github.com/user-attachments/assets/153cefa7-c7a9-43f4-93cd-9dfc7c5cacbc)
然后会发现游戏进行到选项时（即选择自起名&原版名），出现连续报错：
![1729077973751](https://github.com/user-attachments/assets/5fe08c3b-26b4-4308-9adb-728e14220770)
![1729077986224](https://github.com/user-attachments/assets/57ece454-983a-403d-83ef-934c75eafd94)
![1729077995578](https://github.com/user-attachments/assets/051be64a-4d7f-416c-8e73-f4088b488785)
![1729078006437](https://github.com/user-attachments/assets/1000069f-a7d5-4ffe-b79b-b48ef0c5c43e)

**Comment by satan53x** [comment]
更新了一下，但是没有游戏没测试过，只是目测有一种新的，无分支有条件的跳转结构。

**Comment by hhj2004563** [comment]
> 更新了一下，但是没有游戏没测试过，只是目测有一种新的，无分支有条件的跳转结构。

万分感谢大佬！！我上午上完课就去试试！

**Comment by hhj2004563** [comment]
> 更新了一下，但是没有游戏没测试过，只是目测有一种新的，无分支有条件的跳转结构。

大佬，启动SE程序的时候报错了：

D:\GHS\翻译\SExtractor-main>python run.py
Traceback (most recent call last):
  File "D:\GHS\翻译\SExtractor-main\run.py", line 7, in <module>
    from main.mainWindow import MainWindow
  File "D:\GHS\翻译\SExtractor-main\main\mainWindow.py", line 18, in <module>
    from main.batchManager import BatchManager
  File "D:\GHS\翻译\SExtractor-main\main\batchManager.py", line 4, in <module>
    from main.thread import extractThread
  File "D:\GHS\翻译\SExtractor-main\main\thread.py", line 8, in <module>
    import debugpy
ModuleNotFoundError: No module named 'debugpy'
请按任意键继续. . .

**Comment by satan53x** [comment]
缺模块，装一下：
pip install debugpy

**Comment by hhj2004563** [comment]
装好了，重新走了一遍流程，这次直接打开游戏就报错了……
![1729140603614](https://github.com/user-attachments/assets/fa9a2768-5dfc-4f74-b443-babcc9bb48b9)
![1729140615450](https://github.com/user-attachments/assets/825a80cd-57d5-4c74-a3de-8a5915d690f2)
![1729140621593](https://github.com/user-attachments/assets/97183744-7e94-4d19-8326-2ec0775c06a2)
![1729140624343](https://github.com/user-attachments/assets/4655ad5b-de80-4025-9a13-f746ff972a33)
![1729140663389](https://github.com/user-attachments/assets/0b23859d-50a1-45fb-86a9-c1e9b11a62c4)
![1729140670105](https://github.com/user-attachments/assets/01120d73-09b8-4346-abd5-ff5f811ec7d3)
[提取目录：DGHS恋の恋Renkoiシナリオ.txt](https://github.com/user-attachments/files/17406206/DGHS.Renkoi.txt)
大佬，还需要我提供什么文件吗

**Comment by hhj2004563** [comment]
[all.trans.json](https://github.com/user-attachments/files/17406214/all.trans.json)
[all.orig.json](https://github.com/user-attachments/files/17406215/all.orig.json)
[new.zip](https://github.com/user-attachments/files/17406216/new.zip)
上面是提取出来的原文和译文，以及替换后的脚本

**Comment by satan53x** [comment]
直接发提取目录压缩包就行

**Comment by hhj2004563** [comment]
> 直接发提取目录压缩包就行

[シナリオ.zip](https://github.com/user-attachments/files/17406252/default.zip)

**Comment by satan53x** [comment]
更新了，修复了一个BUG。
但是这应该不是你启动报错的问题，你是不是用新的SE的dat_pack.py没有改里边的长度？

**Comment by hhj2004563** [comment]
> 更新了，修复了一个BUG。 但是这应该不是你启动报错的问题，你是不是用新的SE的dat_pack.py没有改里边的长度？

哦哦哦对的，醍醐灌醒！！！

**Comment by hhj2004563** [comment]
> 更新了，修复了一个BUG。 但是这应该不是你启动报错的问题，你是不是用新的SE的dat_pack.py没有改里边的长度？

完美运行了！！！！非常非常非常感谢大佬！！！！！！！

**Comment by hhj2004563** [comment]
大佬，在汉化同引擎的fu.shi.da.ra时又一次遇到了报错问题，但这次好像和先前不太相同：
![1729216425254](https://github.com/user-attachments/assets/67ee69c3-f5d5-4f69-85d3-e0f38538f178)
![1729216428947](https://github.com/user-attachments/assets/95b356b8-84f1-4ed0-9fc6-060fb6857419)
![1729216432887](https://github.com/user-attachments/assets/6c2bb36a-ae1d-48ef-ab79-beca1f039f89)
[シナリオ.zip](https://github.com/user-attachments/files/17426906/default.zip)
[参数1.txt](https://github.com/user-attachments/files/17426913/1.txt)

能麻烦大佬再看一看问题出在哪吗QAQ

**Comment by satan53x** [comment]
这个引擎版本就是比较多，指令不一样又不像yuris有yst指令声明，有些需要自己目测。
你更新一下我把0x15加到默认了，或者是不更新自己用正则说明里的那个`ctrlStr=[None,None,None,[None,0x15],None]`

**Comment by hhj2004563** [comment]
> 这个引擎版本就是比较多，指令不一样又不像yuris有yst指令声明，有些版本需要自己观察decompress后的剧本字节具体是多少。 你更新一下我把0x15加到默认了，或者是不更新自己用正则说明里的那个`ctrlStr=[None,None,None,[None,0x15],None]`

感谢大佬倾力相助！！这就去试试@

**Comment by hhj2004563** [comment]
![1729241698257](https://github.com/user-attachments/assets/00401553-bdd9-4e43-b04b-5e9d53188297)
![1729241735566](https://github.com/user-attachments/assets/04fa1a3e-e80d-45c5-a725-007508ab5f86)
![image](https://github.com/user-attachments/assets/2a755ef6-dc85-45f5-968a-37066d5c4b5a)
[シナリオ.zip](https://github.com/user-attachments/files/17431548/default.zip)
![1729241893502](https://github.com/user-attachments/assets/97cea96a-1fa9-492b-b5db-9a8d4abf9f04)
大佬，现在出现了新的报错

**Comment by satan53x** [comment]
那你直接更新一下再导入试试呢，ctrlStr的用法没有测试过不知道对不对。
还有你发报错没有用，你得发报错之前显示的啥文本。

**Comment by hhj2004563** [comment]
> 那你直接更新一下再导入试试呢，ctrlStr的用法没有测试过不知道对不对。 还有你发报错没有用，你得发报错之前是显示的哪些句子。

已经用了更新版的了

**Comment by hhj2004563** [comment]
> ![1729244367617](https://private-user-images.githubusercontent.com/185200645/377814367-a4d0ee6c-57a8-4552-89d1-a241970212c5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNDQ4ODUsIm5iZiI6MTcyOTI0NDU4NSwicGF0aCI6Ii8xODUyMDA2NDUvMzc3ODE0MzY3LWE0ZDBlZTZjLTU3YTgtNDU1Mi04OWQxLWEyNDE5NzAyMTJjNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQwOTQzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODA5MjhjZTI4MGM0ZDdhNTAzOWNiZjUzMzY4OWE1ZTIzZjg5NjExZWI3NmVhYjI2ZGJmY2FkNGI1MTkxYzFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5cSsxZyaEoTErho3WyyFEHDjRs-yL-G31AIbHhm4n-E) [all.trans.json](https://github.com/user-attachments/files/17432253/all.trans.json) [all.orig.json](https://github.com/user-attachments/files/17432258/all.orig.json) 应该是“呐……你……”这个位置

抱歉，应该是在后面一点的“啊啊……你…………”

**Comment by satan53x** [comment]
“啊啊……你…………”这个文本太多了，有没有独特一点的文本，或者你直接说json里的哪一行？你先确定是显示的这个文本附近。

或者先试试这个：`ctrlStr=[None,None,[None,0x17],None,[None,0x19]]`
但是这个ctrlStr不一定和你报错的这个位置有关。

**Comment by satan53x** [comment]
你再更新一下，我修正了一个昨天刚改出来的导入BUG。

**Comment by hhj2004563** [comment]
> 你再更新一下，我修正了一个昨天刚改出来的缓存字节BUG。

完美运行！！！再次感谢大佬的无私奉献，另外，能问问大佬有没有赞助的渠道哇！

**Comment by satan53x** [comment]
直接放有风险，可以先进交流群：https://github.com/satan53x/SExtractor/issues/19
