### ISSUE TITLE
关于RM游戏的提取问题

### ISSUE THREAD

**Issue by galact-byte** [satan53x/SExtractor#119]
你好，我把一个RPGMakerMV游戏的数据文件转为了csv格式，然后想转成json文件，结果我发现csv文件会提取不出文本。但是同样的操作我在上个月的旧版本却提取了出来，本来一直用的很久前下载的没想过更新，但是电脑突然坏了数据都没了，就下载了最新的，结果提取不出来了，想问下这个该如何解决？文件里有文本的。
![image](https://github.com/user-attachments/assets/0277692d-eef2-4e83-b1fe-a10b79162260)
![image](https://github.com/user-attachments/assets/5674c520-c7b2-4be6-8fd2-5f01df51a6cf)
![image](https://github.com/user-attachments/assets/7d3320a2-61cc-46b0-ba0a-2bac9aba3d90)

**Comment by galact-byte** [comment]
我刚才试了一下，改成extractKey还是提取不出来东西
![image](https://github.com/user-attachments/assets/078b134d-9469-4b49-841a-c6ff773a9610)

**Comment by galact-byte** [comment]
> 为了修复一个struct关键字冲突的bug，新版的CSV把参数关键字改了下，现在extractKey=才是列名（之前是extraData），而extraData现在是nohead之类的（之前是struct）。 你选了CSV引擎之后应该有新的默认正则，里边有说明。（或者是预设选None也能看到）

我刚才试了一下，改成extractKey还是提取不出来东西
![image](https://github.com/user-attachments/assets/078b134d-9469-4b49-841a-c6ff773a9610)

**Comment by satan53x** [comment]
你把提取目录打个压缩包发出来看看呢？

**Comment by galact-byte** [comment]
> 你把提取目录打个压缩包发出来看看呢？

[data.zip](https://github.com/user-attachments/files/17801352/data.zip)
感觉很奇怪，我之前是在win10上运行的，用的也是python3.10，那次确实成功提取出来了。现在我是win11，python3.12，按道理也没有什么大的变化结果就不行了。

**Comment by satan53x** [comment]
你把整个文件夹都打包，包括ctrl这个子文件夹，我才能看到缓存ini。

**Comment by satan53x** [comment]
不对啊，按理说现在默认会缓存ini在ctrl里，你看设置界面里这个有勾选吗？（这个默认应该是勾选的）
![image](https://github.com/user-attachments/assets/56a20af1-dede-410e-868a-1b3ea4163487)

**Comment by galact-byte** [comment]
> 不对啊，按理说现在默认会缓存ini在ctrl里，你看设置界面里这个有勾选吗？（这个默认应该是勾选的） ![image](https://private-user-images.githubusercontent.com/138396258/387253785-56a20af1-dede-410e-868a-1b3ea4163487.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5Mzk1NDYsIm5iZiI6MTczMTkzOTI0NiwicGF0aCI6Ii8xMzgzOTYyNTgvMzg3MjUzNzg1LTU2YTIwYWYxLWRlZGUtNDEwZS04NjhhLTFiM2VhNDE2MzQ4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQxNDE0MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYmQzZDc2MTRhNWEwYTZlNjI5Zjg2MDcyMTFjOTUyNmI1NmVjNzFjMTZlNTA2NDYzMTZiYWYzYzUwZDIyZWJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.34C1DV1NV5jEV6kX4I5kvtHmKjmM9O1F0kqqSiTPgRg)

[data.zip](https://github.com/user-attachments/files/17801501/data.zip)
我重新下载这个然后有了

**Comment by satan53x** [comment]
哦，你预设没选Custom0再运行我还是看不到正则，那只有你自己检查一下你正则前后是不是有空格之类的了。

**Comment by satan53x** [comment]
![image](https://github.com/user-attachments/assets/1820df94-f373-453a-bf61-8925abaa8205)
我这边运行是正常的啊

**Comment by galact-byte** [comment]
好奇怪，我好像也可以了，只是显示的还是没有提取文件，但是文件夹里却会出现那个json文件
![image](https://github.com/user-attachments/assets/0d40a4d2-0f7b-4eab-97a2-424314ad1f91)

**Comment by galact-byte** [comment]
> ![image](https://private-user-images.githubusercontent.com/138396258/387257707-1820df94-f373-453a-bf61-8925abaa8205.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NDAzNjYsIm5iZiI6MTczMTk0MDA2NiwicGF0aCI6Ii8xMzgzOTYyNTgvMzg3MjU3NzA3LTE4MjBkZjk0LWYzNzMtNDUzYS1iZjYxLTg5MjVhYmFhODIwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQxNDI3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGVlYWFjY2M2ZDExMDZiM2UzNzhmMWQ1MjVmZTQ1Y2QxNjQyYzllNzY5YTc5NzliMzc0ZWZjNWZjNTI2ZmRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.c31rryvSlo_ajbxofNrfnwE5IDqDc5wB-fevVB2Sxsk) 我这边运行是正常的啊
> 
> ```
> 22_search=^([\s\S]+)$
> extractKey=^Original Text$
> writeOffset=1
> ```

好奇怪，我好像也可以了，只是显示的还是没有提取文件，但是文件夹里却会出现那个json文件
![image](https://github.com/user-attachments/assets/0d40a4d2-0f7b-4eab-97a2-424314ad1f91)

**Comment by galact-byte** [comment]
> 你这次是复制你之前的正则还是复制的我的？ 你之前的正则是不是哪里有空格之类的？ 你之前的正则复制到Sublime、VSCode、EmEditor之类的编辑器里边看看呢？ 你提示没提取到的是本来就没内容的csv吧现在。

我这次是手敲的，之前好像是我后面有空格我没发现，提示没提取到还真是没东西的。总算解决了，感谢你。
