### ISSUE TITLE
请问一下kaguya导入回去乱码的问题

### ISSUE THREAD

**Issue by JassNull** [satan53x/SExtractor#12]
用了JIS替换，看了下tblstr.arc是导入成功的，就是位置和原来的不一样，也替换了新的ari文件
![{CBFB6710-4AF0-474e-9AF2-6DB5BFD76699}](https://github.com/satan53x/SExtractor/assets/142082458/b8a53b8e-249e-452f-b662-d1d284a1bde0)

**Comment by satan53x** [comment]
你这截图看起来不像是开启了JIS替换的啊，看着像是GBK导入的。
还有竹子有些文本长度不能变，需要开启截断填充。
你试下用原文当做译文，只替换开头两个字成简体`测试`能不能正常显示，保证长度不变。

**Comment by JassNull** [comment]
谢谢试了下，确实是文本太长了

**Comment by TXT2GAM** [comment]
竹子社有些游戏的文本地址在另一个封包里，想改偏移的话需要分析这个封包，成本太大了，建议直接截断。
