### ISSUE TITLE
Nexas support

### ISSUE THREAD

**Issue by Cosetto** [satan53x/SExtractor#120]
This issue is somewhat related to issue #117 
I found this [script disassemble/assemble codes](https://github.com/masagrator/NXGameScripts/tree/main/Aonatsu%20Line), which supports the Switch version's script format (binu8/utf8). I tried modifying Script_disassembler.py to handle PC's script.

I changed line 175 to cp932 but encounters this
```
D:\s>scr a
00共通01
437
String size check failed! Expected: 2412088575, got 13
Offset: 0x1f8ec
奄ﾉ戻りました
```
If I delete lines 220–224, it somewhat works, but the script ends up being truncated, as shown in this image:
![image](https://github.com/user-attachments/assets/ad199379-58ec-43b5-8d53-a7fa8751faec)
For reference, here’s how it looks like binu8 format
![image](https://github.com/user-attachments/assets/8fefa138-51c7-4e8e-bdad-7e4146996091)
You can also see how the names are parsed in the asm file. So, is it possible to modify the codes to support pc script format?
I'll attach the scripts here
[scr.zip](https://github.com/user-attachments/files/17803524/scr.zip)

**Comment by satan53x** [comment]
[Script_assembler_re.zip](https://github.com/user-attachments/files/17816647/Script_assembler_re.zip)
Edit to support `cp932`, the `Pc_script` dir above can be disassembled/assembled, and bytes not changed. 
(The dat file replaces the functionality of the patcher script)

**Comment by satan53x** [comment]
But some other game's bins cannot be disassembled, print error `Some string were not pulled`.
It seems that some strings are not called. 
Not sure if some key code in the command area at the beginning do not support when parse.

**Comment by Cosetto** [comment]
@satan53x Thanks again.

As for the script you gave me. It seems like the dissembler can't handle split strings. If you use [Aiyoku no Eustia's disassembler](https://github.com/masagrator/NXGameScripts/blob/main/Aiyoku%20no%20Eustia/Script_disassembler.py), it will just ignore the error and keep going. The strings will appear in .json file, but not .asm file, so far there're only 3 files have that error

**Comment by Cosetto** [comment]
Btw, can you also make add regex support in SExtractor for the asm files?

**Comment by Cosetto** [comment]
I managed to handle the asm files. Thanks anyway

**Comment by satan53x** [comment]
Added.
Because some games cannot convert parameter values ​​to parameter names such as PUSH_MESSAGE.
So I finally checked the previous and next lines of `name` to determine whether it is a name.
And the default regex is for processing Japanese original text. 
If it is English original text, may need to delete `15_search`. Not tested.

**Comment by satan53x** [comment]
> But some other game's bins cannot be disassembled, print error `Some string were not pulled`.
> It seems that some strings are not called.
> Not sure if some key code in the command area do not support when parse, or the string is indeed not used.

Some games has unassociated strings, but they cannot be abandoned, so I use the json to keep them.
No json file will be output if there is unassociated  string.
