### ISSUE TITLE
Yuris 引擎提取场景标题

### ISSUE THREAD

**Issue by yotsubayo** [satan53x/SExtractor#121]
老师你好，我在处理yuris 488 版本的游戏文本时想要提取替换游戏场景标题
不然的存档预览会是乱码 有没有方法解决 以下是样例ybn
[yst00164 - 副本.txt](https://github.com/user-attachments/files/17819622/yst00164.-.txt)

其中我想提取 "美術室へ～１回目"

**Comment by yotsubayo** [comment]
感谢

**Comment by yotsubayo** [comment]
@satan53x 老师按你说的这么改确实能提取和修改 但仅限日文和中文翻译一样长短的 3个字日文改成4个字中文的游戏到那个场景就会报错

**Comment by yotsubayo** [comment]
![}LC7@ZJJ}FWKWB}2NQNH$BF](https://github.com/user-attachments/assets/f158e21c-4128-44b3-bba3-29a9cd992157)
这是报错信息 翻译后长短一致就没事

**Comment by satan53x** [comment]
那你更新一下，再重新导入，之前这种字符串默认是没有修正内部长度的。

**Comment by yotsubayo** [comment]
问题解决 谢谢
