### ISSUE TITLE
Help request

### ISSUE THREAD

**Issue by Cosetto** [satan53x/SExtractor#123]
This is for Silky new internation script
![image](https://github.com/user-attachments/assets/58c31752-c520-431a-84da-8ade25f1a0cc)
Each script line starts with the opcode 0x14 at specific offsets, and there are pointers referencing these offsets, as shown in the image. Could you add support for SExtractor or adjust [vntextpatch silkymap](https://github.com/arcusmaximus/VNTranslationTools/blob/main/VNTextPatch.Shared/Scripts/Silkys/SilkysMapScript.cs) to handle it?
Also, byte array "00 1A 00 14" is for handle line break
![image](https://github.com/user-attachments/assets/cd4d76ec-83d1-4d9c-b3d0-4a004a0b122b)
[data.zip](https://github.com/user-attachments/files/18160691/data.zip)

**Comment by satan53x** [comment]
Updated.
`extractKey=1` to choose extraction section seq, can be list `=1,2,3`.

**Comment by Cosetto** [comment]
Thanks a lot again
