### ISSUE TITLE
MED怎么提取pre_name

### ISSUE THREAD

**Issue by wjh191** [satan53x/SExtractor#126]
因为游戏的文本十分规则，大体是
```
人名\x00
半角的语音变量\x00
「对话」\x00
```
所以我改了默认正则，改成`20_search=^(?P<pre_name>「.*」)$`这样的，但是导出的文本里全是massage。

**Comment by satan53x** [comment]
要加参数struct=para才能使pre_有效。（等效于structure=paragraph）
同时半角语音代码用postSkip而不是skip，否则pre的就是半角语音。（或者用skip则需要设置里勾选skip不影响lastCtrl）
