### ISSUE TITLE
关于WillPlus的建议

### ISSUE THREAD

**Issue by wjh191** [satan53x/SExtractor#129]
![image](https://github.com/user-attachments/assets/f9ec29f8-9f0b-4377-894a-4f792cbdc37d)
![image](https://github.com/user-attachments/assets/dc9b91cd-c50b-4b1c-b2ab-6d14280a5f10)
![image](https://github.com/user-attachments/assets/61ef3307-6108-4b4b-a1ca-d439c632d2f8)
有些游戏的图片名不是半角字符，当以gbk环境打开游戏时文件名字会变成乱码，导致游戏不能读取立绘而报错，我想到2个方法，一个是直接改封包里的文件名，但这样会导致补丁变大，另一个是改ws2里调用的文件名，目前我知道的有3种后缀，pna、png和mos，都在Graphic.arc里。
所以我想能不能增加个开关，用户自行决定要不要开启，匹配`\x00(.+?\.PNA)\x00`之类，导出不需要包含它们，但导入时把它们改成gbk编码。

**Comment by satan53x** [comment]
你分开提取就行啊，对话文本和图片名分成两个工程提取，串联处理。
比如第一次只提取图片名，直接BIN暴力匹配然后按GBK导入。（中日汉字字节长度一样的，不会改变字节长度）
然后对着第一次生成的new，再正常提取对话文本。
