### ISSUE TITLE
关于kaguya填充截断

### ISSUE THREAD

**Issue by sakura4214** [satan53x/SExtractor#13]
游戏是霧谷伯爵家の六姉妹，TBLSTR.ARC型
这游戏的每行最大字符数是25(应该)，但是原文也有不足25就加\r\n分割的句子，我就想测试将这样的句子改成25分割看看会不会报错，于是在有一句24分割处删掉了\r\n，结果导入时提示译文超出原文长度。
但是导入游戏可以正常运行，那句话也正常25分割，感觉只是个提示bug
![屏幕截图 2023-10-26 214026](https://github.com/satan53x/SExtractor/assets/113588801/0b76e244-119e-40fc-9804-de3ed5b1e98f)

**Comment by satan53x** [comment]
> 还有我是用的老版本提取的文本，提出来的每段末尾都有个\n的那一版，我都已经GPT跑好了，老版本重新分割有bug我就更新了，结果用现在的这个版本导入，提示导入和导出行数不一样，老版本我也没备份，这下子是不是只能重新跑GPT了？

你把search全删了就是之前的了，只留`extraData=fixLength,exportAri`一行

**Comment by satan53x** [comment]
重分这个你是启用了`按每行最大字数重分`？
但是不清楚到底是怎么操作的，你能把脚本所在的工作目录打包上传一下吗？

**Comment by sakura4214** [comment]
确实启用了，设置如图
![屏幕截图 2023-10-27 025548](https://github.com/satan53x/SExtractor/assets/113588801/78125e29-6099-4cdc-be0d-af1e1feabdb0)
![屏幕截图 2023-10-27 025627](https://github.com/satan53x/SExtractor/assets/113588801/e2f1832d-1ae1-461f-955f-9393e814fc82)

**Comment by sakura4214** [comment]
[script_jp.zip](https://github.com/satan53x/SExtractor/files/13181653/script_jp.zip)

**Comment by sakura4214** [comment]
我对原文的改动是38行删了\r\n及两个字符，74行删了\r\n，即all.trans.json文件

**Comment by satan53x** [comment]
`截断`和`按每行最大字数重分`字数不要同时开启。
`截断`是为了保证地址不变，也就是原文译文的每句话都对应字数相等；而`按每行最大字数重分`是按固定长度重分。
原文长度24，固定重分是25，所以会报错。
没有误报，报错会导致不替换，所以就还是原日文，74行等于说是先把第二行的一个字挪到了第一行，但是因为报错所以没替换，最后第一行不变，第二行少了第一个字。

**Comment by satan53x** [comment]
只有游戏需求地址不变的时候才开启截断，不然不要开。
如果游戏没有这个问题，你开启`按每行最大字数重分`就可以了，就能直接按最大字数分割。

**Comment by satan53x** [comment]
而且目前在JIS隧道或者替换时开启截断填充，填充是自动的，但超长时的截断不是自动的，需要手动处理。

**Comment by sakura4214** [comment]
这个游戏的引擎确实要保证译文和原文长度相同，截断之后多出来的cutoff.json是用来干嘛的？

**Comment by sakura4214** [comment]
> 而且目前在JIS隧道或者替换时开启截断填充，填充是自动的，但超长时的截断不是自动的，需要手动处理。 如果需要的话我可以改成自动截断。

需要！另外可以实现cutoff.json里只导入替换错误的文本吗？即下图中的第二句。我在第一句里多打了一个\n所以触发了截断但是这是不需要修改的 游戏里可以正常显示
![屏幕截图 2023-10-27 180138](https://github.com/satan53x/SExtractor/assets/113588801/85e89edb-d09c-43db-9af3-acf387974d85)
![屏幕截图 2023-10-27 180047](https://github.com/satan53x/SExtractor/assets/113588801/4bc6de69-06cb-4d5e-a9d1-e4adb8012df8)

**Comment by satan53x** [comment]
因为JIS隧道在cutoff字典之前，所以没法调用cutoff字典，需要自己去译文里改，只能加上自动截断。但自动截断会导致末尾多余的部分丢失不显示，只是能保证正常运行而已，效果好还是要人工。
你试试只启用重分但是不启用`按最大字数`和`行数一致不重分`呢，看下超长的黄色警告有多少。

至于另一个问题可以在设置里打印信息都关掉，只留Error就只有红色报错，方便定位错误。

**Comment by sakura4214** [comment]
因为我用的老版本，像你说的开启截断填充和重新分割但不开按最大字数和行数一致不重分会出现一大堆下面这种莫名其妙的，新版貌似不会
![屏幕截图 2023-10-27 182931](https://github.com/satan53x/SExtractor/assets/113588801/57ef1dba-4e83-4afc-9f99-e1ec3adee9dd)

**Comment by sakura4214** [comment]
cutoff不能先应用于译文生成新的译文之后在套用JIS隧道？

**Comment by satan53x** [comment]
老版本因为没有插入分割符，所以并不能重分，对工具来说原文和译文都是句话。\n不是工具的分隔符，是文本自带的。

因为JIS隧道在cutoff之后会有一个问题，就是JIS隧道可能会导致字节长度变化，所以之前才把JIS放到cutoff之前。
晚上我改下，把JIS放到cutoff之后，再判断一次长度，虽然可能会使运行效率降低一点。

**Comment by satan53x** [comment]
更新了，你试下有没有问题。

**Comment by sakura4214** [comment]
确实可以了，但是译文替换失效了，含有♪字符的译文不会替换也不会加入cutoff，之前可以依赖JIS隧道来使游戏显示♪，现在不行了，游戏里直接显示原文

**Comment by sakura4214** [comment]
cutoff里这个数字代表什么？
![屏幕截图 2023-10-28 010357](https://github.com/satan53x/SExtractor/assets/113588801/2189e617-786d-4d80-ac35-0d1f98289ba1)

**Comment by satan53x** [comment]
> cutoff里这个数字代表什么？

原文减去译文的长度差值，字节数。负数就是超长，0或正数就没问题了。

**Comment by satan53x** [comment]
更新了一下实现方式。现在应该可以正常进行译文替换了。
同时因为修改了实现，现在基本不会出现译文超长导致的替换失败了。
（但是现在超长在截断后不完全与原文字节长度一致，所以可能还会自动填充一个空格）

**Comment by sakura4214** [comment]
> 更新了一下实现方式。现在应该可以正常进行译文替换了。 同时因为修改了实现，现在基本不会出现译文超长导致的替换失败了。（现在只有黄色警告，不再产生红色错误导致不替换） 但是现在超长在截断后不完全与原文字节长度一致，所以可能还会自动填充一个空格。

我试了一下发现超长的部分不会显示只会显示超长之前的修改，并且游戏里打开backlog（历史记录）到那句超长附近会直接闪退

**Comment by sakura4214** [comment]
我把原文里这句话的\n删了发现它不会按原文截断，导入游戏会出现字符重叠的情况，如图
![无标题](https://github.com/satan53x/SExtractor/assets/113588801/a1468be7-0120-40f5-b512-3afefb6a49fc)
![屏幕截图 2023-10-28 122054](https://github.com/satan53x/SExtractor/assets/113588801/54949fe4-af89-4914-9eba-af9b354812b5)
应该不是更新JIS隧道与cutoff的顺序导致的，我用之前没改顺序版本导入也会这样，不知道是我的设置问题还是因为我用的原先版本的kaguya模式（即每句末尾都带\n）的问题

**Comment by satan53x** [comment]
\n不是工具加的分割，是原文里就有的，所以这一句是看做一行，长度对比是全句的。
就是为了解决这个问题我才改的正则啊。竹子社有些不能自动换行，所以你需要保证\n不被翻译掉。
改了之后是\r\n可以通过重分添加。改之前只能手动保证。

**Comment by satan53x** [comment]
> 我试了一下发现超长的部分不会显示只会显示超长之前的修改，并且游戏里打开backlog（历史记录）到那句超长附近会直接闪退

这个就不太清楚啥问题了，是不是末尾的\n必须保留？

**Comment by sakura4214** [comment]
> > 我试了一下发现超长的部分不会显示只会显示超长之前的修改，并且游戏里打开backlog（历史记录）到那句超长附近会直接闪退
> 
> 这个就不太清楚啥问题了，是不是末尾的\n必须保留？

我保留了啊

**Comment by satan53x** [comment]
> 我保留了啊

不是超长吗？末尾的\n会不会被截断掉了？老版本的话

**Comment by sakura4214** [comment]
> \n不是工具加的分割，是原文里就有的，所以这一句是看做一行，长度对比是全句的。 就是为了解决这个问题我才改的正则啊。竹子社有些版本不能自动换行，所以你需要保证\n不被翻译掉，不然就会重叠起来。 改了之后是\r\n可以通过重分添加。改之前只能手动保证。

那改之后提取出来的行数为什么会不一致啊？

**Comment by sakura4214** [comment]
> > 我保留了啊
> 
> 不是超长吗？末尾的\n会不会被截断掉了？老版本的话

那我不超长只删掉译文末尾的\n导入后没问题啊

**Comment by sakura4214** [comment]
> > \n不是工具加的分割，是原文里就有的，所以这一句是看做一行，长度对比是全句的。 就是为了解决这个问题我才改的正则啊。竹子社有些版本不能自动换行，所以你需要保证\n不被翻译掉，不然就会重叠起来。 改了之后是\r\n可以通过重分添加。改之前只能手动保证。
> 
> 那改之后提取出来的行数为什么会不一致啊？

我是想着把\n全删了然后用新正则分割，但是行数不一致

**Comment by satan53x** [comment]
好像正则有点问题，我修改下，之前是最多只支持三行。这俩改成支持换行符就行
```
12_search=^([\s\S]+)\n$
15_search=^([\s\S]+)$
```

**Comment by sakura4214** [comment]
试了一下把\n全删了然后用新正则分割，有部分会替换失败
![屏幕截图 2023-10-28 132117](https://github.com/satan53x/SExtractor/assets/113588801/ac74e2c2-09e9-4f66-a717-6c8ac9e0c9e9)
![屏幕截图 2023-10-28 132316](https://github.com/satan53x/SExtractor/assets/113588801/d6cb98a2-9020-4fec-9685-4bab7cc615c8)
![屏幕截图 2023-10-28 132345](https://github.com/satan53x/SExtractor/assets/113588801/b614b592-bbfe-4fdb-b93f-0d8c78c2c420)

**Comment by satan53x** [comment]
```
12_search=^([\s\S]+?)\n$
15_search=^([\s\S]+)$
```
这样改也行。不过我又更新了下，现在用脚本辅助，正则可以简单一点了，你可以重新提取下试试。
或者把译文json发我看看呢。

**Comment by sakura4214** [comment]
我都是改原文测试的，译文还有好多超出原文长度的句子要改
[all.trans.zip](https://github.com/satan53x/SExtractor/files/13194618/all.trans.zip)

**Comment by satan53x** [comment]
上边的替换错误是用原文还是译文？

**Comment by sakura4214** [comment]
原文

**Comment by satan53x** [comment]
哦，那可能是之前正则问题，现在用最新的原文还有问题吗？最新的应该不会有\n，只有\r\n才对。

**Comment by satan53x** [comment]
现在超长截断的能显示了吗？还会闪退吗？
还会的话发下游戏名字我看看，是用翻译后的译文导入才会有这个问题吗？

**Comment by sakura4214** [comment]
![image](https://github.com/satan53x/SExtractor/assets/113588801/8e4da368-cfa7-4565-bded-4ab0ded1d9b7)
这是为什么？我用新正则导出原文，然后改了一句使其超长（为了测试闪退），导入就显示这个

**Comment by satan53x** [comment]
有BUG，再更新一下，改了

**Comment by sakura4214** [comment]
> 现在超长截断的能显示了吗？还会闪退吗？ 还会的话发下游戏名字我看看，是用翻译后的译文导入才会有这个问题吗？

超长部分仍然不显示，只显示超长之前的修改，不会闪退了。游戏名是霧谷伯爵家の六姉妹。改的原文测试，如图
![无标题](https://github.com/satan53x/SExtractor/assets/113588801/03ec1c4f-7626-4f72-95e5-3652e7bbda18)

**Comment by satan53x** [comment]
超长不显示正常的啊，截断就是保证译文原文长度一致，不修改肯定会少一部分。

**Comment by satan53x** [comment]
看了下，你这个貌似还是用旧版本的好些，就是带\n的提取，这样截断会少一些，只有总长超过的才需要改。

**Comment by sakura4214** [comment]
截断我觉得手改还好，主要是重分，这个游戏一行只能显示25个字符，有些总长小于原文但是一行超过了25个，这种游戏里会字符重叠
所以我想着把带\n的提取里面的\n全删了然后用新正则重分，但是刚刚试了一下发现会少字符
![无标题](https://github.com/satan53x/SExtractor/assets/113588801/995e0e5f-12f2-433d-b021-247324940987)
第一句少了ない。
第二句少了、悲しくなった。

**Comment by satan53x** [comment]
我想到了，你就用老的，不要正则，保留原文的\n。
然后你把all.trans.json用我工具Tools文件下的limit_maxlen_json_gt.py处理一次，py里边MaxLen可以设置大小（你这应该是26不是25吧）。
这样截断会少很多，而且截断只会出现在每段的末尾的。

**Comment by sakura4214** [comment]
完美！感谢大佬，太强了

**Comment by sakura4214** [comment]
要是cutoff里能显示对应的原文就好了，这样比较方便改

**Comment by satan53x** [comment]
不需要吧，cutoff有字节差值，你按那个改就行，比如-4字节就是去掉两个中文就行。
原文没啥用啊，又不认识日文。

**Comment by sakura4214** [comment]
gpt会有过度翻译或者串行翻译的情况（下一行的翻到这一行来），有原文能复制去机翻一下

**Comment by satan53x** [comment]
这种情况比较少吧，你可以自行修改一下脚本。
字典新增在[helper_text.py](https://github.com/satan53x/SExtractor/blob/main/src/helper_text.py)的第70行附近。
不过因为generateBytes函数参数没有原文，只有原文长度，你还需要新增一个参数在调用的时候传入。

**Comment by sakura4214** [comment]
非常感谢
