### ISSUE TITLE
请问一下tools目录下的Font用法

### ISSUE THREAD

**Issue by sakura4214** [satan53x/SExtractor#14]
游戏在用UniversalInjectorFramework的时候会字体会一粗一细，
![image](https://github.com/satan53x/SExtractor/assets/113588801/93e70574-f70a-4f68-9e85-dbe1c92dc9d7)
font_manager里面的override_face改黑体没用，就想问问这个不用安装字体就加载怎么操作，（安装了倒是能用）
![image](https://github.com/satan53x/SExtractor/assets/113588801/8cb79343-8880-4a7b-8c2f-1542fba06c64)

**Comment by satan53x** [comment]
override_face没用是不是createFont不能hook到，可以打开console看一下。
这个字体主要是给JIS替换用的，当然，因为兼容中文字符你拿来改字体应该也可以。resource_files改一下就行。
```
"resource_files": ["WenQuanYi_msgothic.otf"],
```
不过一般游戏字体不能游戏内选择的话也可以通过配置或者exe里搜索的方式改吧。

**Comment by sakura4214** [comment]
不行啊，还是一粗一细，CreatFont是Hook到了的，我的配置是这样
![image](https://github.com/satan53x/SExtractor/assets/113588801/3096b83e-64c0-4030-bf69-d038cc3e355a)
![image](https://github.com/satan53x/SExtractor/assets/113588801/95eaf46b-83b2-4abf-91de-caa40b11d38d)
这个字体文件也放到游戏录下了，override_face加不加WenQuanYi_msgothic都没用

**Comment by satan53x** [comment]
override_face换成宋体之类的字体会变化吗？不是说粗细，是说字体的形状。
override_charset依次试试134或128或0。

**Comment by sakura4214** [comment]
换134就可以了，非常感谢
