### ISSUE TITLE
SExtractor 和VNT对RealLive文本的提取

### ISSUE THREAD

**Issue by chuliu-hash** [satan53x/SExtractor#15]
一个裸足少女的游戏，用arc_conv解包，解密后用SExtractor和VNT都提了一遍，SExtractor好像大多数json里跟VNT比起来少提了一句或者有一句提取不完整，不过用VNT提的时候有些文件没法提取，可能是这个原因，哪怕没改文本用VNT写入用arc_conv封包后游戏也会闪退
SExtractor写入则没有这个问题
[Seen.zip](https://github.com/satan53x/SExtractor/files/13437328/Seen.zip)

**Comment by satan53x** [comment]
因为SE是暴力匹配的，只适配了最先我测试的那个游戏，所以可能对其他游戏不完全适用，可能会少提取。
而且因为是暴力匹配没有改长度字节，所以SE需要截断，不能改变长度，所以我一般是推荐解密后用VNT。
如果是用SE，少提取的文本不多的话建议是直接用010editor或者winHex，手动翻译编辑一下缺少的那几句话。因为解密后都是明文，可以直接编辑。

**Comment by chuliu-hash** [comment]
> 因为SE是暴力匹配的，只适配了最先我测试的那个游戏，所以可能对其他游戏不完全适用，可能会少提取。 而且因为是暴力匹配没有改长度字节，所以SE需要截断，不能改变长度，所以我一般是推荐解密后用VNT。 如果是用SE，少提取的文本不多的话建议是直接用010editor或者winHex，手动翻译编辑一下缺少的那几句话。因为解密后都是明文，可以直接编辑，注意保持总长不变就行。

那看来只能用SE了，VNT没法提取这个游戏所有文本，有几个文本会显示无法在流的结尾之外进行读取或卡死，然后VNT注入时就会出问题封包回去对话直接闪退

**Comment by satan53x** [comment]
> 那看来只能用SE了，VNT没法提取这个游戏所有文本，有几个文本会显示无法在流的结尾之外进行读取或卡死，然后VNT注入时就会出问题封包回去对话直接闪退

刚刚更新了一下RealLive的匹配正则，应该能改善漏提取的情况。
