### ISSUE TITLE
Cyberworks / CSystem怎么使用才能提取文本啊

### ISSUE THREAD

**Issue by wycstc353** [satan53x/SExtractor#18]
Cyberworks / CSystem怎么使用才能提取文本啊
我用CSystemTools解包了Arc04.dat，然后放了一个文件夹在
![image](https://github.com/satan53x/SExtractor/assets/39401653/01995f1c-7c6b-4a8e-96ae-6b9e2982e266)
是这这样操作的吧？
![image](https://github.com/satan53x/SExtractor/assets/39401653/f5481ae9-6a63-43df-9390-e7a0fd6b508f)
就这样了，是不是我操作那边有问题啊

**Comment by satan53x** [comment]
解包完把后缀为a0的复制到一个新文件夹进行提取，只有a0才是文本，其他的文件是图片之类的不能提取。

**Comment by satan53x** [comment]
哦，我知道了，你这个错误是Python版本过低。要3.9以上。

**Comment by wycstc353** [comment]
> 哦，我知道了，你这个错误是Python版本过低。要3.9以上。推荐是安装3.11

![image](https://github.com/satan53x/SExtractor/assets/39401653/c46c5434-e2aa-48e5-93dd-8cce23b1e787)
还是不行，Python版本升级过了，
[scenarios.zip](https://github.com/satan53x/SExtractor/files/13807131/scenarios.zip)
我把文件发你看下吧

**Comment by wycstc353** [comment]
> > 哦，我知道了，你这个错误是Python版本过低。要3.9以上。推荐是安装3.11
> 
> ![image](https://private-user-images.githubusercontent.com/39401653/293626615-c46c5434-e2aa-48e5-93dd-8cce23b1e787.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNzA5NjQsIm5iZiI6MTcwNDE3MDY2NCwicGF0aCI6Ii8zOTQwMTY1My8yOTM2MjY2MTUtYzQ2YzU0MzQtZTJhYS00OGU1LTkzZGQtOGNjZTIzYjFlNzg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA0NDQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4YTU2MzhmNjNhNjEyN2I4OGMwOGY0NzU2ODM1MGNhYzliZTljMzg5MDE1NzcxNTY3ZDJkMjU5MWFlYzhmYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AGg3psfq_Jgc5pUf_eEeBGtJgEMFC0Jr-CySwBLm6iY) 还是不行，Python版本升级过了， [scenarios.zip](https://github.com/satan53x/SExtractor/files/13807131/scenarios.zip) 我把文件发你看下吧

等等，提出来了，我重新换了种方法升级，用官方exe升级就没问题了，不知道为啥用代码升级就不对

**Comment by wycstc353** [comment]
> 哦，我知道了，你这个错误是Python版本过低。要3.9以上。推荐是安装3.11

还是不行，我导出后，随便改了一句话，导回去后，把dat复制进游戏，游戏直接打不开了，和VNTranslationTools导回后一样的情况

**Comment by satan53x** [comment]
首先确定一下导入和封包没有问题，可以先在设置里打开JIS替换再导入，导入的就是JIS编码，文本会变成类似繁体。再封包测试。（按理说应该是arc04和arc01一起处理的？）
如果导入封包没问题就是exe没改对，可能需要修改编码范围：https://www.bilibili.com/read/cv12543346

**Comment by wycstc353** [comment]
> 首先确定一下导入和封包没有问题，可以先在设置里打开JIS替换再导入，导入的就是JIS编码，文本会变成类似繁体。再封包测试。（按理说解封包应该是arc04和arc01一起修改的？） 如果导入封包没问题就是exe没改对，可能需要修改编码范围：https://www.bilibili.com/read/cv12543346
试了一下，这样如果只改一句是可以的，然后的操作就是把ctrl文件夹里的sjis_ext.bin复制进游戏根目录，然后找到VNTranslationTools下VNTextProxy里的正确的dll复制进去就行了还是还要做别的事情？

**Comment by satan53x** [comment]
> > 试了一下，这样如果只改一句是可以的，然后的操作就是把ctrl文件夹（我用的是单文档）里的sjis_ext.bin复制进游戏根目录，然后找到VNTranslationTools下VNTextProxy里的正确的dll复制进去就行了还是还要做别的事情？

看你是JIS隧道还是JIS替换，如果是隧道就复制sjis_ext.bin和VNT的dll，如果是替换就是uif_config和UIF的dll。（其实UIF也支持隧道，但是配置在uif_config里不需要sjis_ext.bin）

**Comment by wycstc353** [comment]
> > > 试了一下，这样如果只改一句是可以的，然后的操作就是把ctrl文件夹（我用的是单文档）里的sjis_ext.bin复制进游戏根目录，然后找到VNTranslationTools下VNTextProxy里的正确的dll复制进去就行了还是还要做别的事情？
> 
> 看你导入是选的JIS隧道还是JIS替换，如果是隧道就复制sjis_ext.bin和VNT的dll，如果是替换就是uif_config和UIF的dll。（其实UIF也支持隧道，但是配置也在uif_config里不需要sjis_ext.bin）

![image](https://github.com/satan53x/SExtractor/assets/39401653/8b65dd89-bfcc-45c4-af3e-170f053fa748)
![image](https://github.com/satan53x/SExtractor/assets/39401653/03e32d3f-5116-4347-9eb5-bb510c58b713)
我是这样选的，我把sjis_ext.bin和VNT的version.dll选进去没用啊，转区还是字不对，x64dbg不是显示这个游戏依赖version.dll吗？

**Comment by wycstc353** [comment]
> > > 试了一下，这样如果只改一句是可以的，然后的操作就是把ctrl文件夹（我用的是单文档）里的sjis_ext.bin复制进游戏根目录，然后找到VNTranslationTools下VNTextProxy里的正确的dll复制进去就行了还是还要做别的事情？
> 
> 看你导入是选的JIS隧道还是JIS替换，如果是隧道就复制sjis_ext.bin和VNT的dll，如果是替换就是uif_config和UIF的dll。（其实UIF也支持隧道，但是配置也在uif_config里不需要sjis_ext.bin）

![image](https://github.com/satan53x/SExtractor/assets/39401653/b0dbd073-a183-46e6-95c8-1e46b35ae94c)
还有问一下，这种导出来就有特殊符号的，咋弄啊，不改特殊符号，就改中间内容吗？还有修改的文本长度有没有要求，我现在因为就改了一句，是保持长度相同的

**Comment by satan53x** [comment]
不要同时勾选隧道和替换，只会有一个生效。
如果是测试的话最好用JIS替换测试，因为JIS隧道也会超出JIS的编码范围，JIS最小是8140，但是隧道会用到8101,8102之类的。
如果引擎有判断范围下限，隧道不一定能正常显示。
dll在运行时删不掉说明就是加载了，但是并不是加载了就等于有效，加载之后还要hook函数，如果函数hook不到也没有效果。UIF的dll可以在uif_config的配置里打开console观察打印。

**Comment by wycstc353** [comment]
> 不要同时勾选隧道和替换，只会有一个生效。 如果是测试的话最好用JIS替换测试，因为JIS隧道也会超出JIS的编码范围，JIS最小是8140，但是隧道会用到8101,8102之类的。 如果引擎有判断范围下限，隧道不一定能正常显示。 dll在运行时删不掉说明就是加载了，但是并不是加载了就等于有效，加载之后还要hook函数，如果函数hook不到也没有效果。UIF的dll可以在uif_config的配置里打开console观察打印。

![image](https://github.com/satan53x/SExtractor/assets/39401653/bc9649e3-d7ce-4c16-a7c1-0991c27b324d)
![image](https://github.com/satan53x/SExtractor/assets/39401653/490d4314-6980-4eda-a069-a4982a56aa0d)
奇怪，我没勾后一个，为啥还有uif_config.json生成了

**Comment by satan53x** [comment]
> ![image](https://private-user-images.githubusercontent.com/39401653/293677956-b0dbd073-a183-46e6-95c8-1e46b35ae94c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTM2ODAsIm5iZiI6MTcwNDE5MzM4MCwicGF0aCI6Ii8zOTQwMTY1My8yOTM2Nzc5NTYtYjBkYmQwNzMtYTE4My00NmU2LTk1YzgtMWU0NmIzNWFlOTRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDExMDMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkN2RiYmI4ZGNmNDdkNzAzNWNhNjM1M2Y1ZDZjMGJkZWQ2YzllNzk1Yjc3NmFiOWRkNzQwZTBiZGNhZGVkMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K9haKWTlxRrICiPcIITPNoCgQLTkmU4yeAIq75OOn9Y) 还有问一下，这种导出来就有特殊符号的，咋弄啊，不改特殊符号，就改中间内容吗？还有修改的文本长度有没有要求，我现在因为就改了一句，是保持长度相同的

文本长度可变，不影响。
你这个是中间有控制字节，比如图中`\u0011...\u0011`明显是控制长度的字节，表示中间有0x11也就是17个字符。
因为每个游戏有细节区别，可以通过自行调整正则里的search来忽略，也可以二次提取json再导出一次json，来不提取这部分文本。search=后边就是通用的正则用法，除了分组名没有自定义的东西。

**Comment by satan53x** [comment]
> ![image](https://private-user-images.githubusercontent.com/39401653/293679123-bc9649e3-d7ce-4c16-a7c1-0991c27b324d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTQzNjksIm5iZiI6MTcwNDE5NDA2OSwicGF0aCI6Ii8zOTQwMTY1My8yOTM2NzkxMjMtYmM5NjQ5ZTMtZDdjZS00YzE2LWE3YzEtMDk5MWMyN2IzMjRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDExMTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3M2Q5ODg4MjIxMjJlMGJmMzUzNTQwYzc3MTAxMzIyZDU0NDIzNTQ0NWVlMjAyMmQwN2YwMmMwNWYwMmVjZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wxVehN9xONUCQcuLBOIAMUVMJvm8NvGSWjp_9ynjusA) ![image](https://private-user-images.githubusercontent.com/39401653/293679174-490d4314-6980-4eda-a069-a4982a56aa0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTQzNjksIm5iZiI6MTcwNDE5NDA2OSwicGF0aCI6Ii8zOTQwMTY1My8yOTM2NzkxNzQtNDkwZDQzMTQtNjk4MC00ZWRhLWEwNjktYTQ5ODJhNTZhYTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDExMTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNWVjNDI0ZjkxMGIyOTZmZjVhZWE5NmJhODk0ZThhYWMxYmU1YTU2NjZiNmNmMDM4N2NmNWYyYWRkZmE2YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dPrmdWFDseIlolT0gYqSYhLaWKSULS6ysM_lndXa5V4) 奇怪，我没勾后一个，为啥还有uif_config.json生成了

没问题，UIF一样支持隧道，你用谁的dll就复制谁需要的文件

**Comment by wycstc353** [comment]
> > ![image](https://private-user-images.githubusercontent.com/39401653/293679123-bc9649e3-d7ce-4c16-a7c1-0991c27b324d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTQzNjksIm5iZiI6MTcwNDE5NDA2OSwicGF0aCI6Ii8zOTQwMTY1My8yOTM2NzkxMjMtYmM5NjQ5ZTMtZDdjZS00YzE2LWE3YzEtMDk5MWMyN2IzMjRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDExMTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3M2Q5ODg4MjIxMjJlMGJmMzUzNTQwYzc3MTAxMzIyZDU0NDIzNTQ0NWVlMjAyMmQwN2YwMmMwNWYwMmVjZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wxVehN9xONUCQcuLBOIAMUVMJvm8NvGSWjp_9ynjusA) ![image](https://private-user-images.githubusercontent.com/39401653/293679174-490d4314-6980-4eda-a069-a4982a56aa0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTQzNjksIm5iZiI6MTcwNDE5NDA2OSwicGF0aCI6Ii8zOTQwMTY1My8yOTM2NzkxNzQtNDkwZDQzMTQtNjk4MC00ZWRhLWEwNjktYTQ5ODJhNTZhYTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDExMTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNWVjNDI0ZjkxMGIyOTZmZjVhZWE5NmJhODk0ZThhYWMxYmU1YTU2NjZiNmNmMDM4N2NmNWYyYWRkZmE2YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dPrmdWFDseIlolT0gYqSYhLaWKSULS6ysM_lndXa5V4) 奇怪，我没勾后一个，为啥还有uif_config.json生成了
> 
> 没问题，UIF一样支持隧道，你用谁的dll就复制谁需要的文件

[UniversalInjectorFramework](https://github.com/AtomCrafty/UniversalInjectorFramework)是这个吗？我看他全是源码，没有dll下载啊，是要我自己编译吗？

**Comment by satan53x** [comment]
我tools文件夹下有编译好的dll

**Comment by wycstc353** [comment]
> 我tools文件夹下有编译好的dll。 它uif_config里可以配置打印设置，具体用法看它的github页面说明。

用UIF_config可以用，它这个也可以用隧道文件吗？是导入时两个都勾选出来的隧道文件，还是重新导入一下，只勾选隧道文件，然后uif_config里修改一下就能用隧道了还是要改dll的啊

**Comment by satan53x** [comment]
UIF不需要bin，UIF的隧道配置也在uif_config里。这就是为什么勾选JIS也会导出uif_config。

**Comment by wycstc353** [comment]
> UIF不需要bin，UIF的隧道配置也在uif_config里。这就是为什么勾选JIS也会导出uif_config。
意思是勾选隧道，然后把uif_config复制进去？还是勾选后一个，改uif_config？

**Comment by satan53x** [comment]
不用改，勾隧道导出的就是隧道用的uif_config

**Comment by wycstc353** [comment]
> 不用改，勾隧道导出的就是隧道用的uif_config

![image](https://github.com/satan53x/SExtractor/assets/39401653/61054c51-35f6-46eb-8057-4b3638c4632d)
没改是这样的，
![image](https://github.com/satan53x/SExtractor/assets/39401653/c0c7ff80-ddd2-4ff2-b5e2-b332955390df)
配置是这样，意思是隧道不行，要改exe的编码范围是吧？

**Comment by satan53x** [comment]
只能说有可能，也有可能是隧道hook不到。隧道和替换hook的并不是同一个函数。
uif_config配置console可以观察打印。

**Comment by wycstc353** [comment]
> 只能说有可能，也有可能是隧道hook不到。隧道和替换hook的并不是相同的函数。 uif_config配置console可以观察打印。

![image](https://github.com/satan53x/SExtractor/assets/39401653/a8d06f09-1eda-46ab-b4bf-3b08971d0009)
好像是没hook到，哎，这个就烦了，我dll感觉改不来

**Comment by satan53x** [comment]
JIS替换可以就用替换啊

**Comment by wycstc353** [comment]
> JIS替换可以就用替换啊

嗯，我主要怕用替换可能有字是没有的，哎

**Comment by satan53x** [comment]
没有的在字典里加，或者是直接译文里边删除或修改就行，没有的多半不是常用字。
233的VNT图形界面也支持替换：https://github.com/XD2333/GalTransl_DumpInjector
我和他的字典是一样的。

**Comment by wycstc353** [comment]
> 没有的在字典里加，或者是直接译文里边删除或修改就行，没有的多半不是常用字。 233的VNT图形界面也支持替换：https://github.com/XD2333/GalTransl_DumpInjector 我和他的字典是一样的。
如果有没有的字，会在导入时有提示哪些字没有吗？

**Comment by satan53x** [comment]
会，除了打印SE还会在uif_config里保存一个叫cache的列表，显示哪些字需要处理。

**Comment by wycstc353** [comment]
> > ![image](https://private-user-images.githubusercontent.com/39401653/293677956-b0dbd073-a183-46e6-95c8-1e46b35ae94c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTM2ODAsIm5iZiI6MTcwNDE5MzM4MCwicGF0aCI6Ii8zOTQwMTY1My8yOTM2Nzc5NTYtYjBkYmQwNzMtYTE4My00NmU2LTk1YzgtMWU0NmIzNWFlOTRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDExMDMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkN2RiYmI4ZGNmNDdkNzAzNWNhNjM1M2Y1ZDZjMGJkZWQ2YzllNzk1Yjc3NmFiOWRkNzQwZTBiZGNhZGVkMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K9haKWTlxRrICiPcIITPNoCgQLTkmU4yeAIq75OOn9Y) 还有问一下，这种导出来就有特殊符号的，咋弄啊，不改特殊符号，就改中间内容吗？还有修改的文本长度有没有要求，我现在因为就改了一句，是保持长度相同的
> 
> 译文文本长度可变，不影响。 你这个是中间有控制字节，比如图中`\u0011...\u0011`明显是控制长度的字节，表示中间有0x11也就是17个字符。 因为每个游戏有细节区别，可以通过自行调整正则里的search来忽略，也可以二次提取json再导出一次json，来不提取这部分文本。search=后边就是通用的正则用法，除了分组名没有自定义的东西。

对了，这边这个控制字符的这行，是不是有要求字数的，还是和别的行一样，不限制字数？

**Comment by satan53x** [comment]
每行总长是不限制的，是它自己的控制字后边跟随的字符限制。
刚刚貌似说错了，一个\u0011就是一个长度，另一个\u0011应该也是指它后边的长度。

**Comment by satan53x** [comment]
我打断点看了一下，它字节结构这样的`\xFF\xFF\x06...\x06...`。
你把15改成`15_search=(?P<unfinish>[\x40-\xFC]+)`就可以只提取纯文本不提取控制字节，但是因为\x06没有提取到所以操作数后的文本长度应该不能变。（这个在游戏里应该是类似注音的东西？）
如果改成`15_search=(?P<unfinish>[\x01-\xFC]+)`就是只忽略\xFF\xFF，这样\x06还在，长度可变，但是改变之后需要自行修正长度。

**Comment by wycstc353** [comment]
> 我打断点看了一下，它字节结构这样的`\xFF\xFF\x06...\x06...`。 你把15改成`15_search=(?P<unfinish>[\x40-\xFC]+)`就可以只提取纯文本不提取控制字节；但是因为\x06没有提取到，所以操作数后的文本长度应该不能变。（这个在游戏里应该是类似注音的东西？） 如果改成`15_search=(?P<unfinish>[\x01-\xFC]+)`就是只忽略\xFF\xFF，这样\x06还在，长度可变，但是改变之后需要自行修正长度。
前一个是指必须长度一样，还是能短的？
后一个自行修正是啥意思？

**Comment by satan53x** [comment]
前边应该是要一致。短了要补空格，长了要删除。
修正\x06啊，在json里显示的是\u0006，后边跟了6个日文字符，假如翻译之后变成4个，那\u0006就要修正为\u0004呗。

**Comment by satan53x** [comment]
不过还有种办法就是还是按照最初的默认正则提取，这个好像是注音？你直接在译文里全删了就行
`\xFF\xFF\x06...\x06...`这样的结构，你删了只剩最后的...就行了应该。
krkr也有这种情况，它一般是[ruby text=...]的结构，一般就是提取出来都删掉。

**Comment by wycstc353** [comment]
> 不过还有种办法就是还是按照最初的默认正则提取，这个好像是注音？你直接在json里全删了就行。 `\xFF\xFF\x06...\x06...`这样的结构，你删了只剩最后的...就行了应该。 krkr也有这种情况，它一般是[ruby text=...]的结构，一般就是提取出来都删掉。中文又不需要注音。

![image](https://github.com/satan53x/SExtractor/assets/39401653/c4e5aaca-7df2-4fbb-80ce-31e448e2fa80)
意思是\u0006的改成这样，别的\u还是保留？

**Comment by satan53x** [comment]
都删除，0006只是举例，\u的都是，甚至有些是\t或者\n。只要是这种结构的。搜索\u前边那2个空白字符，以空白字符为准。
正则要用初始默认的，默认的在\x06前边还有两个\xFF\xFF，json里是2个空白字符，也是要删除的。

**Comment by wycstc353** [comment]
> 都删除，0006只是举例，\u的都是，甚至有些是\t或者\n。只要是这种结构的。搜索\u前边那2个空白字符，以空白字符为准。 正则要用初始默认的，默认的在\x06前边还有两个\xFF\xFF，json里是2个空白字符，也是要删除的。
感觉字数可能限制了哎，我刚把它所有的除了带\的都翻译的一下，确定文本都是不长于原文10个字符的，导回去游戏打不开了

**Comment by satan53x** [comment]
\u前边的2个空白符删掉了吗？

**Comment by wycstc353** [comment]
> \u前边的2个空白符删掉了吗？

我用的是默认的原正则，然后所有带\的行都没动，就是所有的
![image](https://github.com/satan53x/SExtractor/assets/39401653/1aed1b61-69c8-415d-9f9f-280cd7dd1ff8)
\都是默认状态，我导出的时候用的是
![image](https://github.com/satan53x/SExtractor/assets/39401653/ad0ce381-fc99-4506-b5c3-3c840e5e3352)
这个

**Comment by satan53x** [comment]
照我的说法都删掉试试，因为我想起来你这是JIS替换的，还保留的话真不一定能按原来的导入。
或者是这些句子不要译文，译文为空字符串""，空字符串表示不替换，也就是这句话会保留原来的字节流，就不会有错。

**Comment by wycstc353** [comment]
> 照我的说法都删掉试试，因为我想起来你这是JIS替换的，还保留的话真不一定能按原来的导入。 或者是这些带\u的句子不要译文，译文为空字符串""，空字符串表示不替换，也就是这句话会保留原来的字节流，就不会有错。

![image](https://github.com/satan53x/SExtractor/assets/39401653/4d57e952-1d19-4cb4-b502-b372a236d6d4)
这个字符没有的吗？话说我没看到你说的没有的字符的文件啊

**Comment by wycstc353** [comment]
> 照我的说法都删掉试试，因为我想起来你这是JIS替换的，还保留的话真不一定能按原来的导入。 或者是这些带\u的句子不要译文，译文为空字符串""，空字符串表示不替换，也就是这句话会保留原来的字节流，就不会有错。

试了，不行，把带\的后一个双引号之内的都变空了还是不行，我先看视频了，明天试试把第一句话变短或者变长看看会不会打不开

**Comment by wycstc353** [comment]
> 照我的说法都删掉试试，因为我想起来你这是JIS替换的，还保留的话真不一定能按原来的导入。 或者是这些带\u的句子不要译文，译文为空字符串""，空字符串表示不替换，也就是这句话会保留原来的字节流，就不会有错。

试了一下，我弄了个比原文短的，就直接打不开了，估计那个游戏有字符限制，要不你这程序加个选项，把短于原文的字符填充到和原文一样长度的选项？

**Comment by wycstc353** [comment]
> 有这个功能啊，译文截断填充，长的截断，短的填充

好吧，我以为这功能只能截断来着，那我翻译的就只要都比原文短或者相同长度就行，\的之后再研究

**Comment by satan53x** [comment]
或者是干脆不提取注音这一段，但推荐还是提取了删掉。不提取就是保留不替换：
```
00_skip=^$
10_search=^(?P<name>【.+?】)
15_search=(\xFF\xFF[\x01-\x3F][\x40-\xFC]+?[\x01-\x3F])|(?P<unfinish>[\x40-\xFC]+)
postSkip=^\uF8F3
extraData=readJIS
structure=paragraph
```

还有就是导出格式可以选，第三个就是和VNT一样的json。

**Comment by wycstc353** [comment]
> 或者是干脆不提取注音这一段，但推荐还是提取了删掉。 不提取就是保留不替换，字节流还在文件里：
> 
> ```
> 00_skip=^$
> 10_search=^(?P<name>【.+?】)
> 15_search=(\xFF\xFF[\x01-\x3F][\x40-\xFC]+?[\x01-\x3F])|(?P<unfinish>[\x40-\xFC]+)
> postSkip=^\uF8F3
> extraData=readJIS
> structure=paragraph
> ```
> 
> `(\xFF\xFF[\x01-\x3F][\x40-\xFC]+?[\x01-\x3F])`这一段就是提取刚刚的注音控制段`\xFF\xFF\x06...\x06`，然后通过postSkip忽略掉。
> 
> 还有就是导出格式可以选，第三个就是和VNT导出一样的json，带\r\n的。

 话说有没有啥正则表达式是能只提取\的行中我想翻译的内容的啊，还有・那个未识别的框是不是都是这个符号啊

**Comment by satan53x** [comment]
新发的这个正则就是只提取文本，不提取注音啊。注音也就是・・・这个正则就是不提取的。

**Comment by satan53x** [comment]
总之你想要忽略啥就按通用正则写就行，=后边都是通用正则，只有=前才是工具控制用的。

**Comment by wycstc353** [comment]
> 总之你想要忽略啥就按通用正则写就行，=后边都是通用正则，只有=前才是工具控制用的。

  对了，a0是不是还是加密状态的啊，有没有啥工具能把a0解密后的内容放出来，然后再加密回去的吗？

**Comment by satan53x** [comment]
启用配置的console看打印有没有hook到，当然，有时即使hook到了也不一定是对话文本用的。
如果确定JIS替换也不行。
那要么就还是按GBK导入，然后修改exe的字符集和编码范围。
要么就是用JIS替换的字体，如果exe默认就是用`ＭＳ ゴシック`那直接用SE的tools/Font文件夹下otf就行。dll打开font_manager或者是直接安装字体。

**Comment by wycstc353** [comment]
> 启用配置的console看打印有没有hook到，当然，有时即使hook到了也不一定是对话文本用的。 如果确定JIS替换也不行。 那要么就还是按GBK导入，然后修改exe的字符集和编码范围。 要么就是用JIS替换的字体，如果exe默认就是用`ＭＳ ゴシック`那直接用SE的tools/Font文件夹下otf就行。dll打开font_manager或者是直接安装字体。
缺字体的原因，我这个游戏因为要在显示日文的里玩，我用的是虚拟机，把字体装上好了，我就说之前快进看着好不舒服

**Comment by satan53x** [comment]
不是说缺日文字体，是这个改过的字体专门针对JIS替换用的，可以不需要dll里开启source_characters。
UIF的dll开启source_characters就是走的hook，如果hook不行才需要字体。

**Comment by wycstc353** [comment]
> 不是说缺日文字体，是这个改过的字体专门针对JIS替换用的，可以不需要dll里开启source_characters。 UIF的dll开启source_characters就是走的hook，如果hook不行才需要字体。
原来如此，谢谢了，大佬，明白了

**Comment by wycstc353** [comment]
> 不是说缺日文字体，是这个改过的字体专门针对JIS替换用的，可以不需要dll里开启character_substitution。 UIF的dll开启character_substitution就是走的hook，如果hook不行才需要字体。
话说突然想到一件事，UniversalInjectorFramework现在是改字，是一个字一个字对的，那如果把它源码改一下，变成改句子，那不就能直接汉化游戏了？

**Comment by satan53x** [comment]
dll hook到的系统函数TextOut或者MultiByteToWideChar传入的参数并不是一定是正常的句子，有可能分开或者重复，还需要处理。
你说的这个功能类似平时的hook翻译器，只不过字幕是外挂的。
这里有skip一遍预翻译的Luna翻译器教程：https://www.south-plus.net/read.php?tid-1877211.html
Luna这个翻译器好像是说有部分能转成内嵌，就跟你这个意思差不多，不是所有引擎都通用。

**Comment by satan53x** [comment]
主要问题在于一旦句子是断开的，比如原文`私は食べる`，分别传入`私` `は食` `べる`，但是是单线程，所以不能等到全部所有都传入了才返回值，必须要立即返回值。
所以大部分都只能外挂字幕，外挂字幕才能收集到整句的信息。

**Comment by wycstc353** [comment]
> dll hook到的系统函数TextOut或者MultiByteToWideChar传入的参数并不是一定是正常的句子，有可能分开或者重复，还需要处理。 你说的这个功能类似平时的hook翻译器，只不过字幕是外挂的。 这里有skip一遍预翻译的Luna翻译器教程：https://www.south-plus.net/read.php?tid-1877211.html Luna这个翻译器好像是说有部分能转成内嵌，就跟你这个意思差不多，不是所有引擎都通用，需要特殊处理。
 我知道Luna，主要椎名里绪的游戏总是有特殊字符，那个特殊字符特讨厌

**Comment by satan53x** [comment]
椎名里绪确实难搞，走hook是最好的。
不过一般遇到椎名里绪都直接不搞，得不偿失，又不是非要玩他家的游戏。
这就是为啥krkr受欢迎，原生支持unicode，比这种不知所谓的引擎好太多。

**Comment by wycstc353** [comment]
> 椎名里绪确实难搞，走hook是最好的。 不过一般遇到椎名里绪都直接不搞，得不偿失，又不是非要玩他家的游戏。 这就是为啥krkr受欢迎，原生支持unicode，比这种不知所谓的引擎好太多。
话说它那个引擎看了一下，视频是免封包的，那能不能做到改exe，让文本也免封包呢？

**Comment by satan53x** [comment]
这个就不清楚了
