### ISSUE TITLE
SiglusEngine引擎

### ISSUE THREAD

**Issue by yqw1231** [satan53x/SExtractor#2]
您好，又有事要麻烦您了。就是我使用dump ss（copy text）生成很多.ss.txt文件，但是提取之后，发现得到的txt没有name，都只有message。
![AMWW VFRW(}8N~RCPK9JE%Q](https://github.com/satan53x/SExtractor/assets/136776881/d21947bd-1ee6-4f21-8063-ceb10e31affc)
请问是我有啥操作不对吗？

**Comment by satan53x** [comment]
因为txt里存在全日文的控制符，所以名字需要你用"强制设定名字"功能人工进行设定。（在“选择匹配规则”左边）
用英文逗号分开就行，不一定要所有名字，有些没出现过几次的配角名字等他在message中也行。
这个SE引擎写得比较早，其实你纯txt也可以直接用TXT引擎，有正则可以去掉一些"名無し"这样的无用文本。
当然SE引擎将就用也行。

**Comment by yqw1231** [comment]
哦，好的，感谢

**Comment by yqw1231** [comment]
请问SiglusEngie Tools是无法解决中文叠字的情况吗？

**Comment by yqw1231** [comment]
目前已经用SiglusExtract解决了这个问题

**Comment by yqw1231** [comment]
但是有个很僵硬的地方。
![~)VIGBAZI%@3BV4CQ}9BZ4Q](https://github.com/satan53x/SExtractor/assets/136776881/179c224a-557f-4c24-bab0-160650eb2bcc)

**Comment by yqw1231** [comment]
噢，明白啥情况了
![XU 2{52FP( 3_A4NVQ(XPK0](https://github.com/satan53x/SExtractor/assets/136776881/d7bc5aef-c646-4d2c-a8ad-b74214d1862c)

**Comment by yqw1231** [comment]
感觉得通过判断末尾是不是句号来提取一下

**Comment by satan53x** [comment]
因为格式比较灵活，一般都是TXT模式写正则来处理

**Comment by yqw1231** [comment]
这种感觉没法用正则来处理吧，主要我正则水平不大行，只能单纯找规律来提取
