### ISSUE TITLE
Reallive引擎文本封包

### ISSUE THREAD

**Issue by JassNull** [satan53x/SExtractor#20]
游戏是新妻こよみ
（官方最新的修正补丁的txt貌似去除了二次加密）
无论是选中全部子txt文件，还是放到一个文件夹拖到exe/bat都没有用，是不是这个封不了还是我的用法不对
用的VNT提取和导入的，因为我发现SE在第一处就少了一句
![5770139365f2e2c2bdaedc1f4d7819ae](https://github.com/satan53x/SExtractor/assets/142082458/05a5d634-c52f-42a6-80ec-12380877d119)
![489d7250ada330764709c3111e3f0173](https://github.com/satan53x/SExtractor/assets/142082458/380ef797-bb6d-4a43-bc57-8e94ead393b4)
顺便贴一下最新的txt[Seen.txt](https://github.com/satan53x/SExtractor/files/13872895/Seen.txt)

**Comment by satan53x** [comment]
arc_conv的用法详见github项目：[arc_conv](https://github.com/amayra/arc_conv)
它的根目录下有`formats.txt`可以看，当然，解封包我都写成bat了。
应该是你封包的路径不对，记事本打开bat就能看到。
```
arc_conv.exe --pack rlseen new\new Seen.new.txt
```
默认是脚本运行目录下的new\new文件夹，有两层是因为默认是二次加密的文件夹结构，你把`new\new`改成你自己子文件所在文件夹的路径就行。

**Comment by JassNull** [comment]
感谢
但是我替换了txt后打开游戏，“认证成功”的文本加载不出来就闪退了（用了sjis替换），是我的脚本有问题还是需要改程序

**Comment by satan53x** [comment]
用VNT进行JIS替换的是吧？JIS替换是要配合UIF的dll，但是即使不用dll也不会引起闪退，因为编码还是JIS。
你可以用解包后的日文txt子文件，只覆盖第一个场景的中文txt打包试试，控制变量法。
按理说VNT导入的话文本长度是可以变的，编码又是JIS应该不会闪退才对。

**Comment by JassNull** [comment]
是用的VNT
试了下确实是脚本的问题.....

**Comment by JassNull** [comment]
如果不用sjis替换的话貌似一个字都注不进去
”无法将位于索引 0 处的 Unicode 字符 \u8BA4 转换为指定的代码页。“

**Comment by satan53x** [comment]
之前好像也有人说VNT的RealLive有点问题，你可以试试用`text_conv`提取，虽然它提取出来是txt，也只支持JIS编码，可以先试试能不能用。能用就可以用SE二次提取然后JIS替换。
text_conv用法 https://github.com/satan53x/SExtractor/issues/1#issuecomment-1692699401

**Comment by JassNull** [comment]
谢谢，今天没空了明天白天我再弄吧，有问题再来问

**Comment by JassNull** [comment]
text_conv倒是可以提取，不过提出来是这样的
![{116FC7A7-7890-452f-9519-2CE5D5F19866}](https://github.com/satan53x/SExtractor/assets/142082458/7623d824-283e-466b-91bd-a0d369875b1b)
不怎么会正则，这种真的可以提出来文本吗？

我看SE更新了又试了下se提取，和VNT的比较了下大概有20句缺失或不完整，如果我在翻译前把orig中不完整的句子删掉不翻译，写入的时候SE可以把没有翻译的原日文写回去吗？以前试过删SE提取出的多余代码可以跳过
可以的话我觉得我可以手动改下这些翻译

**Comment by satan53x** [comment]
可以，SE译文json里边字符串置空就是不替换，保持原来的字节。
不过翻译前不需要手动删掉吧，不是少提取了吗？少提取的就直接用010编辑器之类的手动编辑一下。

**Comment by JassNull** [comment]
好，感谢
