### ISSUE TITLE
NekoSDK导出后有很多\r\n，导回时需要放回去吗？

### ISSUE THREAD

**Issue by wycstc353** [satan53x/SExtractor#21]
NekoSDK导出后有很多\r\n，导回时需要放回去吗？如果要放回去，是不是还要每个\r\n之前的数据比较长度？

**Comment by satan53x** [comment]
NekoSDK中的\r\n是剧本文本自己的，不是SE添加的，所以才需要把设置里的段落分割符改成其他字符串。（防止SE误认为是工具添加的）
NekoSDK的文本长度是可变的，不需要比较长度。（除非是某一行过长超过显示框，且不能能自动换行的引擎）

**Comment by wycstc353** [comment]
> NekoSDK中的\r\n是剧本文本自己的，不是SE添加的，所以才需要把设置里的段落分割符改成其他字符串。（防止SE误认为是工具添加的） NekoSDK的文本长度是可变的，不需要处理长度，\r\n个数也是可变的。 （除非是某一行过长超过显示框，且不能自动换行的游戏）

OK,明白了，那就是只要自己专门试出最长就行了是吧

**Comment by wycstc353** [comment]
> NekoSDK中的\r\n是剧本文本自己的，不是SE添加的，所以才需要把设置里的段落分割符改成其他字符串。（防止SE误认为是工具添加的） NekoSDK的文本长度是可变的，不需要处理长度，\r\n个数也是可变的。 （除非是某一行过长超过显示框，且不能自动换行的游戏）
 还是华府社的问题，为啥
![image](https://github.com/satan53x/SExtractor/assets/39401653/6fb9f0ac-5cec-4bf6-a99a-a68d39db1e40)
我ku框出来的文件导出的剧本文本导不出要翻译的内容呢？有啥区别吗？

**Comment by wycstc353** [comment]
![image](https://github.com/satan53x/SExtractor/assets/39401653/5183f8a9-64bb-43b6-b9b8-ca43c6e0eda2)
程序zh直接闪退了

**Comment by satan53x** [comment]
不清楚，你在SE设置页面把Debug勾上可以看到是哪个文件闪退的，好像都是明文找一下问题。

**Comment by wycstc353** [comment]
> 不清楚，你在SE设置页面把Debug勾上可以看到是哪个文件闪退的，好像都是明文找一下问题。
我自己找到原因了，那个9的文件是很久以前的机翻补丁来着
……

**Comment by wycstc353** [comment]
> 不清楚，你在SE设置页面把Debug勾上可以看到是哪个文件闪退的，好像都是明文找一下问题。
对了，ALL-TiME的游戏有没有准备导入导出的计划啊，看了一下，就是个.db后缀的文件，UTF8编码的，明文的

**Comment by satan53x** [comment]
没有，明文的纯文本一般自己用正则就行

**Comment by wycstc353** [comment]
不知道咋写，这个社的应该都是这样的文件
[scenario.zip](https://github.com/satan53x/SExtractor/files/13927949/scenario.zip)


> 没有，明文的纯文本一般自己用正则就行

**Comment by satan53x** [comment]
哦，你这不是文本啊，我以为你说是utf-8文本呢。
这是sqlite3的数据库，你可以用sqlite的可视化工具导出。但问题是导出的数据也是字节流，不是纯文本。
所以最好的办法是自己写脚本用python读取sqlite再处理。python原生支持sqlite，但需要一定的程序功底。

**Comment by wycstc353** [comment]
> 哦，你这不是文本啊，我以为你说是utf-8文本呢。 这是sqlite3的数据库，你可以用sqlite的可视化工具导出。但问题是导出的数据也是字节流，不是纯文本。 所以最好的办法是自己写脚本用python读取sqlite再处理。python原生支持sqlite，但需要一定的程序功底。
我知道是数据库，但可以用纯文本方式打开的，用文本方式打开改了也行，所以在想应该用正则表达式取应该就可以了，用读数据库的反而不好弄

**Comment by satan53x** [comment]
正则的话有两个问题，第一是字符串没有结束符，如果右边有符合utf-8格式的字节有部分会提取歪，第二是文本长度不能变。
你不解包，也就是不用sqlite的话最好也是用脚本提取，脚本里边能处理字符串前边记录的字节长度，保证不会提取歪，可以解决第一个问题。（但第二个问题还是不能解决，不解包光改文本的记录字节长度没有用，因为db头部有页索引，一般有页长度）

**Comment by wycstc353** [comment]
> 正则的话有两个问题，第一是他这个结构里字符串没有结束符，如果右边有符合utf-8格式的字节有部分会提取歪，第二是文本长度不能变。 你不解包，也就是不用sqlite的话最好也是用脚本提取，脚本里边能处理字符串前边记录的字节长度，保证不会提取歪，可以解决第一个问题。（但第二个问题还是不能解决，不解包光改文本的记录字节长度没有用，因为db头部有页索引，一般有页长度）
哎，长度的话，用你的截取应该问题就不大了，主要是提取歪，这点就讨厌了，哎

**Comment by satan53x** [comment]
```
00_skip=^[\S\s]{0,4}$
10_search=^\x00{0,2}[\x01-\xFF]{0,2}?【(?P<name>[\xC0-\xF7][\x80-\xF7]{1,}?)】[\x00-\x7F]
20_search=^\x00{0,2}[\x01-\xFF]{0,2}?([\xC0-\xF7][\x80-\xF7]{3,}?)[\x00-\x7F]
ignoreDecodeError=1
seprate=\x00\x00
```
只能给你个例子，可能会少提取，可能会多提取（比如控制文本`暗転`应该是图片名）。
控制文本需要自行译文置空，或者是postSkip=^暗転$
