### ISSUE TITLE
RPGMV引擎

### ISSUE THREAD

**Issue by kao0312** [satan53x/SExtractor#23]
我用SExtractor测试提取了多个RPGMV引擎的游戏，总结出了几个问题
1、当data目录下存在TrpParticles.json和ContainerProperties.json这两个文件之一时提取文本会导致程序崩溃
不知道这两个文件的作用，不过里面没有文本
报错信息
```
值查找失败, 请检查Json格式 -1
Traceback (most recent call last):
（省略）
    events = content['events']
KeyError: 'events'
```
顺带一提，在出现报错时能不能不关闭主窗口，因为自己编辑的正则不会及时保存，有时候因为上述问题或者编码选择错误导致丢失自己编辑的正则表达式
2、选择name,message导出格式，提取不出人名
`extractName=^MapInfos|^(?!Map)`的含义是从Map文件以外的文件里提取出人名吗？实在是不会用这个功能

**Comment by satan53x** [comment]
RPGMV当初是对一个游戏随便写的，基本不会维护，现在我都是用T++再二次提取。

**Comment by satan53x** [comment]
> 1、当data目录下存在TrpParticles.json和ContainerProperties.json这两个文件之一时提取文本会导致程序崩溃
> 不知道这两个文件的作用，不过里面没有文本

不需要的文件不要放工具目录，对其他引擎也一样的。
你自定义正则在预设`__Custom`里编辑就会自动保存，这个应该是在提取之前就会保存的吧。

**Comment by satan53x** [comment]
> 2、选择name,message导出格式，提取不出人名
> `extractName=^MapInfos|^(?!Map)`的含义是从Map文件以外的文件里提取出人名吗？实在是不会用这个功能

不是，这个name是指剧本文件json里的`name`元素，不是人名。
默认正则的name就是靠`01_search=^ {0,1}(?P<name>.+)：$`，这个是当时我那个游戏文本的结构，其他游戏不一定通用，你需要看自己的文本进行修改。我那个文本名字是单独一行，由`：`结束。

**Comment by TXT2GAM** [comment]
> RPGMV当初是对一个游戏随便写的，基本不会维护，现在我都是用T++再二次提取。

好吧，我也用过T++。感觉T++优化不行，用着体验很卡。SExtractor虽然提取不出所有文本，但是非常方便
没注意Custom预设的这个功能，难怪之前改了匹配规则也不会保存
确实不同的游戏开发者的代码习惯不同，还遇到过人名就在对话文本前面的，也遇到过单独一行并且没有冒号这些字符的

**Comment by satan53x** [comment]
主要RPGMaker的json格式还是比较乱，懒得全适配，所以就干脆用T++先导出一次再二次提取。

> 顺带一提，在出现报错时能不能不关闭主窗口，因为自己编辑的正则不会及时保存，有时候因为上述问题或者编码选择错误导致丢失自己编辑的正则表达式

这个倒是可以，待会儿搞一下，异常不退出主程序。

**Comment by TXT2GAM** [comment]
> RPGMV当初是对一个游戏随便写的，基本不会维护，现在我都是用T++再二次提取。

分别看了下T++导出的几种格式，应该选择CSV格式对吧
不清楚SExtractor的CSV引擎是怎么运作的，`extraData`就是列名吗
假如想要提取第一列然后写入译文到第二列应该如何配置正则？
还存在一个问题，假如某行原文是`[代码]文本[代码]`，提取出`文本`后，怎样才能实现在第二列写入`[代码]文本翻译[代码]`，而不仅仅是提取的`文本`的翻译

**Comment by satan53x** [comment]
如果格式都比较固定，文本全是同一列，也可以直接按TXT处理。

> 不清楚SExtractor的CSV引擎是怎么运作的，`extraData`就是列名吗

是的，第1行作为列名按正则进行匹配。
如果第1行没有列名，则需要`structure=nohead`，`extraData`就是列的索引列表，如`name0,1`表示第1列是名字，第2列是文本。

> 假设想要提取第一列然后写入译文到第二列应该如何配置正则？

`writeOffset=1`可以偏移写入列。

**Comment by satan53x** [comment]
> 还存在一个问题，如果某行原文是`[代码]文本[代码]`，提取出`文本`后，怎样才能实现在第二列写入`[代码]文本翻译[代码]`，而不仅仅是提取的`文本`的翻译

原文是`[代码]文本[代码]`，提取出`文本`那就是只会改文本啊，不影响[代码]。

**Comment by satan53x** [comment]
准备重写一下RPGMV的解析，可以提供几个游戏的文本嘛，我对比下格式差异。最好带上System.json。

**Comment by satan53x** [comment]
@TXT2GAM 准备重写一下RPGMV的解析，可以提供几个游戏的文本嘛，我对比下格式差异。最好带上System.json。

**Comment by TXT2GAM** [comment]
感谢大佬，已上传（游戏的data文件夹）[密码:i4gp](https://wwz.lanzouq.com/icDDK1mmo9hg)

**Comment by satan53x** [comment]
已更新，只能说基本都能提取到，但是因为游戏的不同需要自己修改正则。
为了方便分段，每行前边会加上`<code401>`或者`<root   >`之类等长的控制段，不要提取到json里就行，写入的时候不需要这段。
默认正则是skip非code的。
预设里有个System规则是全提取。

**Comment by TXT2GAM** [comment]
我在用这个新的RPGMV的引擎提取时遇到了疑惑
```
00_skip=^<.+?>$
01_skip=^<code108>|^<code408>|^<root
02_skip=^<code401>\\#
10_search=^<code401>(?P<unfinish>[\S\s]+)$
20_search=^(<.+?>[\S\s]+)$
extractKey=all
postSkip=^[ -~\s]+$
sample=Custom
```

**Comment by satan53x** [comment]
尽量不要使用`extractKey=all`吧，这个一般是单独提取`System.json`用的。
`extractKey`就是提取code之外的普通文本，默认没有的话就是`extractKey=name`，也就是提取`"name":"文本"`这种key-value对。
但是它在控制段<>里的名字并不是name，而是父节点的key。`root`就是根节点，因为找不到它父节点的名字了。

**Comment by satan53x** [comment]
`extractKey`后边是key列表，比如你用`extractKey=name,nickname`就是提取这两个key的值，其实前边的控制段叫啥不重要，反正不是code就行。

**Comment by TXT2GAM** [comment]
经过这几天的测试，只要合理调整正则几乎可以处理所有非插件的文本。但是其中一部游戏遇到一个小问题，对话框左上角的人名提取不出。据我观察对应这段`{"code":101,"indent":0,"parameters":["",0,0,2,"エリザ"]}`
我尝试自己修改`extract_RPGMV.py`的`101 : ["Show Text Attributes", True, True],`，但是还是提取不出，目前我想不到其它办法了

**Comment by TXT2GAM** [comment]
[这个](https://wwz.lanzouq.com/ibfaq1myv6lg)是游戏的data压缩包，希望可以作为参考

**Comment by satan53x** [comment]
把`101 : ["Show Text Attributes", True, True],`设为True之后可以正常提取`{"code":101,"indent":0,"parameters":["",0,0,2,"エリザ"]}`啊？
你是说有漏提取吗还是一个都提取不到？
我用测试正则
```
00_skip=^<.+?>$
01_skip=^<(?!code)
02_skip=^<code(?!101)
20_search=^<.+?>([\S\s]+)$
```
能提取到1600多个message啊？
```
[
  {
    "message": "調教師"
  },
  {
    "message": "エリザ"
  },
  {
    "message": "エリザ"
  },
  {
    "message": "調教師"
  },
  {
    "message": "エリザ"
  },
  {
    "message": "調教師"
  },
```

**Comment by TXT2GAM** [comment]
应该是引擎选错了。。。确实能提取
麻烦大佬了
