### ISSUE TITLE
建议：更改安装依赖的方式为从requirements.txt安装

### ISSUE THREAD

**Issue by thiliapr** [satan53x/SExtractor#24]
如题，原来安装依赖依靠bat批处理文件，但我观察到大部分项目将依赖储存在`requirements.txt`文件，我认为可以将安装依赖的方式改为更常见的为从`requirements.txt`安装。
作此更改，`requirements.txt`的内容（如果不能确定以后版本的依赖是否适用于该项目的代码，可以限定依赖的版本，格式示例：`pyqt5==5.15.10`）：
```
pyqt5
colorama
pandas
```
`安装依赖.bat`的内容将被更改为：
```
pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
pip install -r requirements.txt
```

**Comment by satan53x** [comment]
恩，也可以，因为最初是只有一个依赖pyqt5，所以直接写的

**Comment by thiliapr** [comment]
既然这样，那么我就不操心这个了。
