### ISSUE TITLE
Cyberworks引擎疑问……

### ISSUE THREAD

**Issue by DaiHM** [satan53x/SExtractor#25]
Cyberworks引擎，导出为txt文档 { 文本 }格式，放上对应文本格式勾选填充为原文长度可以替换。
但用其他格式放上对应的译文文件写入都失败，包括json列表 [ { name : 名字, message : 带换行对话 } ]格式……都提示”译文为空，不替换“……
这应该怎么设置好……？

**Comment by satan53x** [comment]
不确定什么问题，可能是原文里就含有\r\n？和段落分隔符冲突了。在设置里修改段落分割符试试。修改为任意字符串，比如⚡。

**Comment by DaiHM** [comment]
修改为任意字符串后随便替换了几个词语，好像可以了，谢谢！
