### ISSUE TITLE
YU-RIS引擎 舊版本 能否支持導出

### ISSUE THREAD

**Issue by a115014** [satan53x/SExtractor#27]
satan大 您好
目前找不到好用的工具
請問舊版本有辦法支持導出嗎?
謝謝!

**Comment by satan53x** [comment]
有多旧啊？发点文本出来看一下呢

**Comment by a115014** [comment]
這是0.290的
[yst00149.zip](https://github.com/satan53x/SExtractor/files/14178252/yst00149.zip)

**Comment by satan53x** [comment]
更新了，但是没有测试过，如果有问题只有年后再说

**Comment by a115014** [comment]
提取沒問題,但導入就亂碼了
能否支持人名提取
[yst00140.zip](https://github.com/satan53x/SExtractor/files/14203724/yst00140.zip)
感謝!

**Comment by satan53x** [comment]
默认是GBK导入，如果需要cp932导入需要勾选编码也对bin生效。
人名啥问题？好像你之前发的那个文本人名是提取到了的吧。

**Comment by a115014** [comment]
了解
我想提取yst00140.ybn這文件的人名

**Comment by satan53x** [comment]
哦，新版的名字文件也是和普通文件一样提取的，这个旧版的提取不了吗？但是现在用的平板没有设备可以查看二进制文件。
按理说都是ybn结构一样吧，是不是正则需要修改？你可以看下是不是10_search需要把里边引号去掉。观察一下ybn。

**Comment by a115014** [comment]
的確跟新版差不多,有先試過了,但搞不定
還是等satan大 有空再幫忙看看吧

**Comment by satan53x** [comment]
按理说ybn结构应该不变，唯一有影响的应该是extraData，可以尝试把extraData逐渐调小，只提取这一个文件的话，调到1都行。

**Comment by a115014** [comment]
可以了,感謝!
