### ISSUE TITLE
如何处理使用双空行来更换段落的文本

### ISSUE THREAD

**Issue by lightning32x** [satan53x/SExtractor#28]
我遇到了类似这样的文本，使用两行空行换段而不是特定的格式控制符。
```
AAAAAA
BBBBBB


DDDDDD


【NAMEa】
「EEEE
   EEEE
   EEEE」


【NAMEb】
「FFFFF」


GGGGGGG
```
期望的输出是
```json
[
  {
    "message": "AAAAAA\r\nBBBBBB"
  },
  {
    "message": "DDDDDD"
  },
  {
    "name": "NAMEa",
    "message": "「EEEE\r\nEEEE\r\nEEEE」"
  },
  {
    "name": "NAMEb",
    "message": "「FFFFF」"
  },
  {
    "message": "GGGGGGG"
  }
]
```
选用的引擎是TXT，正则表达式是
```
00_skip=^[;#/]
02_search=^【(?P<name>.+)】$
11_search=^(?P<unfinish>.+)$
```
得到的输出是
```json
[
  {
    "message": "AAAAAA\r\nBBBBBB\r\nDDDDDD"
  },
  {
    "name": "NAMEa",
    "message": "「EEEE\r\n   EEEE\r\n   EEEE」"
  },
  {
    "name": "NAMEb",
    "message": "「FFFFF」\r\nGGGGGGG"
  }
]
```
我尝试了在表达式中使用\n来实现需求，但不起作用。
请问我该如何修改表达式来实现期望的输出？

**Comment by satan53x** [comment]
TXT引擎是单行读取的，主要是需要加上structure=paragraph
```
00_skip=^[;#/]
01_skip=^$
02_search=^【(?P<name>.+)】$
11_search=^(?P<unfinish>.+)$
structure=paragraph
```
paragraph在遇到过skip的时候会结束上一段落，所以需要01_skip匹配空行。

**Comment by satan53x** [comment]
当然，还有种方法是用BIN引擎，打开纯文本模式，且勾选编码也对BIN生效。
这样你可以加上`separate=\r\n\r\n`，就可以跨行读取了，正则里边就可以用\r\n。
但是你这个文本结构不需要这样处理，直接TXT按上边说的简单一些。

**Comment by lightning32x** [comment]
> TXT引擎是单行读取的，主要是需要加上structure=paragraph
> 
> ```
> 00_skip=^[;#/]
> 01_skip=^$
> 02_search=^【(?P<name>.+)】$
> 11_search=^(?P<unfinish>.+)$
> structure=paragraph
> ```
> 
> paragraph在匹配到skip或者name的时候会结束上一段落，所以需要01_skip匹配空行。


很有帮助，感谢您的指导！
