### ISSUE TITLE
“生成VNT的JIS隧道” 功能

### ISSUE THREAD

**Issue by lightning32x** [satan53x/SExtractor#29]
我这里的一个游戏使用`SJIS`编码的脚本。将提取的`UTF-8`JSON文件翻译成中文后，将将其应用回脚本中。
我在下面选中的`TXT编码`是`cp932`，程序报错：
```
UnicodeEncodeError: 'cp932' codec can't encode character '\u55ef' in position 10: illegal multibyte sequence
```
我希望使用`VNTextProxy`对程序hook以实现中文显示，由于上面的报错，我尝试将原始脚本手动更改为`UTF-8`编码，并在下面也选中`UTF-8`编码，并勾选`JIS`配置中的`生成VNT的JIS隧道`选项。翻译正确应用到了脚本，但程序生成的`sjis_ext.bin`文件大小为0。

**Comment by satan53x** [comment]
JIS隧道原理是使用8101,8102,8103...是非法的JIS编码，所以无法直接写回TXT。
如果是cp932纯文本用隧道，需要使用BIN引擎且勾选纯文本模式。
