### ISSUE TITLE
Failed to extract Artemis's script

### ISSUE THREAD

**Issue by Cosetto** [satan53x/SExtractor#3]
The tool stops at 01_共通07.ast
[script.zip](https://github.com/satan53x/SExtractor/files/12640778/script.zip)

**Comment by satan53x** [comment]
It used to check items and exclude those with only a name and no message. 
I just made a change.
Now it only print warnings instead of  throwing exceptions.

**Comment by Cosetto** [comment]
Can you also tell how to insert the translated text back?
![image](https://github.com/satan53x/SExtractor/assets/81801486/4ac8b0e4-6eb7-4b23-92f2-5481ed4cdf11)

**Comment by satan53x** [comment]
Most engines do not support adding or removing lines because the design is based on replacement.
Extra lines are discarded, and missing lines are filled with spaces.

TXT mode reads text line by line, while BIN mode allows for handling across lines. 
If you want to add or remove lines, you'll need to use BIN mode and write regular expressions to process them yourself. 
There are no preset options for that.

Because Japanese to Chinese translation typically does not involve adding lines, in order to preserve the original structure, it's usually done through replacement rather than adding or removing lines.

**Comment by satan53x** [comment]
However, it's possible to add line breaks using this engine. 
You can add line breaks in the translation by inserting \",\n{\"rt2\"},\n\" into the text, and this will create line breaks in the output.

**Comment by Cosetto** [comment]
Thank you again.

**Comment by Cosetto** [comment]
[EAGLS.zip](https://github.com/satan53x/SExtractor/files/12721004/EAGLS.zip)
@satan53x Tool for EAGLS if you need

**Comment by Cosetto** [comment]
@satan53x https://disk.yandex.ru/d/BPX07VulskWJ5 Unity's script tool
Guide: [video](https://mega.nz/file/Wup2gaZa#suSBaUkkBtJAR_Oh8k5R9_q-Fg0E1VQtq5xt2HtPo-E)
The hardest step is finding where's the script, but should be able to find it with "MonoBehavior" filter
You can export the script to .csv, and use Emeditor or Libre Office to edit it
[Uabea here](https://github.com/nesrak1/UABEA)

**Comment by satan53x** [comment]
> [Unity's script tool](https://disk.yandex.ru/d/BPX07VulskWJ5)

@Cosetto Thx bro.
By the way, can the sentences be filtered before exporting to CSV, or are all the sentences exported and then filtered separately?

**Comment by Cosetto** [comment]
> > [Unity's script tool](https://disk.yandex.ru/d/BPX07VulskWJ5)
> 
> @Cosetto Thx bro. By the way, can the sentences be filtered before exporting to CSV, or are all the sentences exported and then filtered separately?

![image](https://github.com/satan53x/SExtractor/assets/81801486/66840e5e-e941-45fe-95e5-33e3b1eb9298)
This one I think, I'm not sure how this works though.

**Comment by Cosetto** [comment]
If you choose to export to csv, hit "csv" when you need to import back. And you don't need the original .dat script
![image](https://github.com/satan53x/SExtractor/assets/81801486/06f75c84-4449-4cf7-803d-596e670dcdfb)
I also have UnityEx 2021 version here if you need 
[UnityEX.zip](https://github.com/satan53x/SExtractor/files/13470135/UnityEX.zip)

**Comment by Cosetto** [comment]
@satan53x Kuro Ai here is Kuro Ai from Clockup right? If yes, I have the unpack/pack tools here. The engine is called Pix studio
[PIX.zip](https://github.com/satan53x/SExtractor/files/13765200/PIX.zip)

**Comment by satan53x** [comment]
> @satan53x Kuro Ai here is Kuro Ai from Clockup right? If yes, I have the unpack/pack tools here. The engine is called Pix studio [PIX.zip](https://github.com/satan53x/SExtractor/files/13765200/PIX.zip)

Thx, it's effective.
So, maybe all the games from Pix studio used the same key.

**Comment by Cosetto** [comment]
I haven't tested pack tool yet, but the engine itself read from "data" folder right?

**Comment by satan53x** [comment]
Yes, it will prioritize reading from the `bin` file; deleting the `bin` file will allow it to read from the data folder.
However, the name of data folder is configured in the `pix.xml` file. In this game:
```
<datafolder>KuroaiHD_dl</datafolder>
```

**Comment by Cosetto** [comment]
@satan53x The command to pack AST with arc_conv: arc_conv.exe --pack arc12 <in_folder> <output_file> <1 or 2>

**Comment by Cosetto** [comment]
@satan53x maybe this can help with malie packer
https://github.com/Dir-A/MalieTools/blob/main/MalieTools/Modules/MalieTools/MalieDecryption_Key.h

**Comment by satan53x** [comment]
> @satan53x maybe this can help with malie packer https://github.com/Dir-A/MalieTools/blob/main/MalieTools/Modules/MalieTools/MalieDecryption_Key.h

Thanks, bro. 
I'm aware of this, and it's similar to garbro. They all involve only unpacking without alignment padding in the generation process. 
For now, the only option is to temporarily fill with '00'. (Perhaps the padding doesn't affect the operation)

**Comment by Cosetto** [comment]
Bro, how can I pack the doesn't have RotateKey?
![image](https://github.com/satan53x/SExtractor/assets/81801486/b136224b-36c2-4570-b13c-44c09a1d8691)
It keeps throwing this error whenever I choose the game without RotateKey

**Comment by satan53x** [comment]
Yes, you can set `ExpectHeader` to the first 4 bytes of you orignal archive, it will try to find the right key just like `Garbro`.
`GameType` is not the key, it's the game's name in the `database_malie.json` .

**Comment by satan53x** [comment]
Oh, I see.
If your game is only has 'Key' in database that means it's the `cameliia` encryption, now the script is not supported.
Maybe I will add it lator.
Malie has  encryption `cfi` and `cameliia`, so the script's name is `cfi_pack`。

**Comment by satan53x** [comment]
@Cosetto 
I add the `cameliia` encryption. 
But didn't test the padding that in `cameliia` will effect the other bytes of  0x10 block.  
It can avoid through manually align game's script file. Ensure that the byte length of the file is a multiple of 0x10.

**Comment by satan53x** [comment]
Btw, because `cameliia` encryption will effect the other bytes of 0x10 block.
 The `ExpectHeader` is not the initial 4 bytes anymore, and it's now the `0x10~0x18` bytes because of the plaintext is all `00` in this position.

**Comment by Cosetto** [comment]
![image](https://github.com/satan53x/SExtractor/assets/81801486/322f052c-2d18-4ec0-b5f8-8d8a9e2c182d)
So if the ExpectHeader of the archives are not the same, do I adjust like this?

**Comment by Cosetto** [comment]
Okay, so it doesn't work. data6.dat is the new created archive
![image](https://github.com/satan53x/SExtractor/assets/81801486/e9196b02-36bc-4400-bbbb-44f2ffcd64cc)
GARbro can't recognize the .svg file anymore, it returns blank file. Exec.dat can't be extracted too.
![image](https://github.com/satan53x/SExtractor/assets/81801486/c971f5eb-094d-4231-b705-62a0018e75ee)
![image](https://github.com/satan53x/SExtractor/assets/81801486/9b015647-0e19-42d9-9121-8ff6019d8f67)

**Comment by satan53x** [comment]
Can you upload this original archive?

**Comment by Cosetto** [comment]
Here https://drive.google.com/file/d/1kRvS8PsS0DDv1_Thg2YbwblFAH5oLyw9/view?usp=sharing

**Comment by satan53x** [comment]
I find the problem, it's not the cryption error.
I didn't dump the `DataAlign` from garbro to database, and the game may have diffrent algin.

**Comment by satan53x** [comment]
You can update , I change it with the temporary alignment adjustment.
I will dump the database again later and add `Align`.

**Comment by satan53x** [comment]
You can update , I change it with the temporary alignment adjustment.
I will dump the database again later and add `Align`.

**Comment by Cosetto** [comment]
Thanks, it works now

**Comment by satan53x** [comment]
Database updated.

**Comment by Cosetto** [comment]
Btw, if the Cli_encryption's Key is the same, then these should be the RotateKeys for missing games [link](https://github.com/Dir-A/MalieTools/blob/1ca6c769274260d2924b90e4f7d806410a5f516b/MalieTools/exdieslib/MalieEncryption_Key.h#L21-L28)
We just need to convert from Hexadecimal to Decimal to match your database_malie.json
`Align` could be same too

**Comment by satan53x** [comment]
Yes, actually the `Key` of cfi games from garbro seems to be all the same.
Only need `RotateKeys`: four int32 integers.

**Comment by Cosetto** [comment]
Works, Silverio Ragnarok
![image](https://github.com/satan53x/SExtractor/assets/81801486/d98ff080-5c53-4e7f-bcb6-dbd633a786a4)
```
  "Silverio Ragnarok": {
    "Key": "pKemoaCjoqyvrqmoq6q0t7axsLOyvL++ubi7uqGpsbk=",
    "RotateKey": [
      1886727479,
      1246915416,
      2017543546,
      1732338005
    ],
    "Align": 1024
  },
```

**Comment by satan53x** [comment]
I don't know how to add to garbro's formarts file. I dump it by breakpoint debugging.

**Comment by Cosetto** [comment]
I see

**Comment by satan53x** [comment]
I find Garbro has SchemeTool project, I try to add them to `Formats` file. Doesn't test, you can try it.
[Formats.zip](https://github.com/satan53x/SExtractor/files/14075517/Formats.zip)

**Comment by Cosetto** [comment]
Btw, can you tell how did Dir-A find the RotateKeys in (this post)[https://github.com/Dir-A/Dir-A_Essays_MD/blob/main/Reverse/%5BMalie%5D%20%E5%AF%BB%E6%89%BE%E5%AF%86%E9%92%A5%20P1/%5BMalie%5D%20%E5%AF%BB%E6%89%BE%E5%AF%86%E9%92%A5%20P1.md]
There's a game I wanna add the keys

**Comment by satan53x** [comment]
I just used the key without trying to find it, not very sure.
What's your game's name?

**Comment by Cosetto** [comment]
Nvm, I found it by blindly follow "cmp edx, 10" instruction
It is for the English version of [this game](https://vndb.org/v18685).

**Comment by satan53x** [comment]
[Formats.zip release](https://github.com/satan53x/GARbro/releases/tag/v1.5.44-d3)
And I update the code of `SchemeTool ` project in garbro solution.
```
{
    uint[] rot_key = { 0x3C787768, 0x466E2D69, 0x35726440, 0x612B6743 };
    var crypt = new GameRes.Formats.Malie.LibCfiScheme(0x100, key, rot_key);
    string name = "Dies irae Interview with Kaziklu Bey [ENG]";
    if (!scheme.KnownSchemes.ContainsKey(name)) scheme.KnownSchemes.Add(name, crypt);
}
```
Only need to rebuild the `SchemeTool ` project and run, it will output file to `bin\Debug\GameData`.

**Comment by satan53x** [comment]
Wait, I write the wrong `Align`.

**Comment by Cosetto** [comment]
@satan53x You can add https://www.bilibili.com/read/cv27648507/ to regular expression list. The engine is RPM. The code to find the key is in the post. And to repack: arc_conv --pack ciel msg msg.arc {0|1|2|3|4|5} (key), eg: arc_conv --pack ciel msg msg.arc 4 faulta
Game in example: [link](https://vndb.org/v1648)

**Comment by Cosetto** [comment]
[Seen.zip](https://github.com/satan53x/SExtractor/files/15288485/Seen.zip)
Bro can find the xor key of this game? I can't find any truncated line to perform xor.
@satan53x

**Comment by satan53x** [comment]
I don’t have the text displayed in the game, so only try similar bytes comparisons.
Maybe the key is:
```
67 1C 21 BE 6F EF B5 16 4A 82 39 2B AD 3A 71 3F
```

**Comment by satan53x** [comment]
Actually, if no text is found in the encrypted area, there is no need to perform secondary encryption and decryption, and extract/import can proceed normally.

**Comment by Cosetto** [comment]
> 67 1C 21 BE 6F EF B5 16 4A 82 39 2B AD 3A 71 3F

Thanks bro, seems like it's also Kud Wafter's key

**Comment by satan53x** [comment]
> Thanks bro, seems like it's also Kud Wafter's key

Is it the case that VNT cannot be extracted without performing a secondary decryption?
And what's the name of the first game?

**Comment by Cosetto** [comment]
And what's the name of the first game?
https://vndb.org/v3079
I'm using text_conv because VNT might not work. Also, the names mess up, maybe because of this:
![image](https://github.com/satan53x/SExtractor/assets/81801486/27c32681-9aa6-4c0e-b5e3-9af00756e04e)
![image](https://github.com/satan53x/SExtractor/assets/81801486/755add51-1e43-46ac-8c5d-f48794a0e628)
From what I see, Kud Wafter is the same type [as these](https://github.com/theappleman/rldev/blob/634b6c5ad1adfae3b94082993295fad75224a843/lib/game.cfg#L74-L145), so rldev might work better

**Comment by Cosetto** [comment]
I had it worked for Oni-uta and Kud Wafter with [rldev compiler](https://drive.google.com/file/d/1doiNXoT6eDEYiDDl5PFJzH7B_UxLLlg1/view?usp=sharing). Too bad rldev is outdated for Hadashi's games
![image](https://github.com/satan53x/SExtractor/assets/81801486/33863cc3-2a44-4b70-8a76-514f29d55cde)
![image](https://github.com/satan53x/SExtractor/assets/81801486/dbd20158-d88f-4949-97ab-a70dfc35591b)
For Chinese, I think you should append "-e cp936" to the command line.

**Comment by Cosetto** [comment]
@satan53x Bro, do you know how to fix the error in [this tool](https://github.com/Cosetto/vn_re/tree/master/bin/acv1) when using pack_resource:
![image](https://github.com/satan53x/SExtractor/assets/81801486/a01e20d4-69a6-4657-b066-9b0799427368)
pack_script is fine though.

**Comment by satan53x** [comment]
I don't have data. Maybe you can debug this:
https://github.com/Cosetto/vn_re/blob/b8b4cd361a8582a1f2799db4bdfb7879d1e70ad7/vn_re/archives/acv1/resources.py#L137C1-L151C85
The `file_name` may be empty.

**Comment by Cosetto** [comment]
I got some files here:
[Edit.zip](https://drive.google.com/file/d/1HhwpWqS_sHBf9kMNRn-ALWrnSKURAXFF/view?usp=sharing)
I don't know if the error relate to the file_name.txt or not?

**Comment by satan53x** [comment]
https://github.com/Cosetto/vn_re/blob/b8b4cd361a8582a1f2799db4bdfb7879d1e70ad7/vn_re/archives/acv1/resources.py#L138
```
    file_name = "/".join(input_file_name.split("/")[1:]).encode("cp932")
```
Change the `"/"` to `os.sep`.

**Comment by Cosetto** [comment]
Thanks bro, works

**Comment by Cosetto** [comment]
@satan53x 
[Entis_Gls_kit.zip](https://github.com/user-attachments/files/15748372/Entis_Gls_kit.zip)
Command line noa packer

**Comment by Cosetto** [comment]
@satan53x 
https://f95zone.to/threads/translation-request-saiminjutsu-2-black-rainbow.90051/post-13646517
Another script tool for Black Rainbow, tested on Saiminjutsu 2 and Ura Saiminjutsu 2

**Comment by satan53x** [comment]
> @satan53x https://f95zone.to/threads/translation-request-saiminjutsu-2-black-rainbow.90051/post-13646517 Another script tool for Black Rainbow, tested on Saiminjutsu 2 and Ura Saiminjutsu 2

Yeah, I know this tool: https://github.com/satan53x/SExtractor/issues/72
This tool is equivalent to using `extraData=\x01\x00\x00\x00` in SE when extract script.

**Comment by Cosetto** [comment]
@satan53x Is it possible to find the xor key of Seen0070.txt, Seen0090.txt, Seen9992.txt, Seen9994.txt, Seen995.txt, Seen997.txt of Niizuma Koyomi? Also, can you tell how do the new test_xor.py work? I only have been using old test_xor.py until now
[Seen.zip](https://github.com/user-attachments/files/17945396/Seen.zip)

**Comment by satan53x** [comment]
Is there anything special about these txt files? The key should be the same as other txt files.

And `test_xor.py` has no updates for RealLive. The `main3()` is used to test Kirikiri.

**Comment by satan53x** [comment]
![image](https://github.com/user-attachments/assets/9055c9b1-4d03-4bca-b842-da62be2a8dc4)
![image](https://github.com/user-attachments/assets/fb01a7e5-0c41-4466-9ced-dd712a1d8584)
I'm sure the decrytion works fine.

The encrypted section start at the value of address `0x20` in every file:  
![image](https://github.com/user-attachments/assets/ab1e82ac-eb22-48f2-80d6-68e9c5fbeb60)
```
0x0020: D4 01 00 00 -> 1D4
start: 1D4 + 100 -> 2D4
end: 2D4 + 101 -> 3D5 
```

**Comment by Cosetto** [comment]
@satan53x Found the way to find keys with xdbg. First, run the game to get EntryPoint, Search>Current region>Constant>8000000F. Set breakpoint on all commands containing the constant 0x8000000F, then press F9 to run it. When you hit the breakpoint, you'll see [cmp reg, 100] instruction. Next press F9 to run one more time, right click the "key_data_prt_ptr">Follow in dump>ebx: Value
![image](https://github.com/user-attachments/assets/a2a012fc-fd41-4811-b011-525d1ad2e14d)
![image](https://github.com/user-attachments/assets/8e36f113-7192-47a0-84be-dd3776e9da8e)
[Tutorial video](<https://mega.nz/file/ivRWDKgR#6W7ass8qEXLuSAKo-YxkHxOVTQiQyGA19TB_Uzw0wwQ>)

**Comment by Cosetto** [comment]
Also, I think I found the source errors. Example in Seen0070.txt, I not sure why it tells me the ")" should be there not "."
![image](https://github.com/user-attachments/assets/7ce7b8b9-b60c-4c4e-9e2d-b73d9e79c9a6)

**Comment by satan53x** [comment]
Maybe the decompiler is not compatible?
The `.` in `""` should be allowed. The txt is not wrong.

**Comment by Cosetto** [comment]
> Maybe the decompiler is not compatible?

I'm not sure, maybe pointer problem? When I replace .(2E) with G(47), the decompiler will throw "found 47" instead

**Comment by satan53x** [comment]
Maybe the error is not here?
Try to edit the above string `G00\\` to `G00GG`.

**Comment by Cosetto** [comment]
@satan53x I found the bytes to crack Reallive.exe
Disable region check message:
```python
Find: E8 18 1B FF FF
Replace: 90 90 90 90 90
```
```python
Disable dvd check messgae:
Find: E8 67 10 F1 FF 8B F0 83 FE FF 0F 84
Replace: B8 01 00 00 00 5B 5F E9 CE 02 00 00 
```

**Comment by satan53x** [comment]
Yeah, I add a link to this issue in the `README.md` of `tools/RealLive`.

**Comment by Cosetto** [comment]
@satan53x https://gitgud.io/xorxorrax/dxlib-tools

**Comment by Cosetto** [comment]
@satan53x Do you have unpacked Formats.dat of GARbro?

**Comment by satan53x** [comment]
Here's the json and `Garbro.Console.exe`.
[console.zip](https://github.com/user-attachments/files/18643734/console.zip)
You can put the exe in Garbro dir to unpack for your own dat file. 
And the code updated too: [commit](https://github.com/satan53x/GARbro/commit/49436087b94684240c8019bff571639f11f3b99b)

**Comment by Cosetto** [comment]
Thanks

**Comment by Cosetto** [comment]
@satan53x I ported [RLDev](https://github.com/eglaysher/rldev) to Python. So far, I’ve only tested it with Niizuma Koyomi, but it works very well. You can also add `-x cp936` in `compile.bat` when compiling new TXT files for Chinese encoding.

Edit: Update select_s2 to take 3 arguments (Princess HeartLink)
[Rldev_python.zip](https://github.com/user-attachments/files/27523809/Rldev_python.zip)

**Comment by satan53x** [comment]
Good, I will update to the `tools/RealLive` folder later. 
Or do you want to create a new GitHub project by yourself? If you need to update frequently.

**Comment by Cosetto** [comment]
I'll will create a new repos later after testing with more games.

**Comment by Cosetto** [comment]
@satan53x It's here https://github.com/Cosetto/Rldev-python

**Comment by Cosetto** [comment]
@satan53x Can you help me get the key of [this game](https://vndb.org/v1124)?
Sample truncated line in Seen0104.txt: 動と静が激しく入り乱れる中で、ふっとたずねる。
[Seen.zip](https://github.com/user-attachments/files/30734864/Seen.zip)

**Comment by satan53x** [comment]
Try this: `83 05 D7 50 8D 08 57 32 AC 7A D2 1A 49 23 87 D1`

**Comment by Cosetto** [comment]
Thanks! It works
