### ISSUE TITLE
脚本提取和回写问题

### ISSUE THREAD

**Issue by lightning32x** [satan53x/SExtractor#32]
我面对的一个脚本：提取时出现大量`提取时原文为空`，但可以正确提取出文本。
翻译完成后的文本无法正确写回，提示`译文为空，不替换`。
脚本格式类似如下
```
#MESSAGE
>-1
name1 or EMPTY_LINE
>-1
message1
#OTHER_CONTROL_COMMAND or NONE
#MESSAGE
...
```
考虑处理多行文本所以选择了BIN引擎，并勾选`BIN启用纯文本正则模式`。
我的正则表达式：
```
10_search=>-1\r\n(?P<name>.*)\r\n>-1\r\n(?P<msg>[\S\s]+?)(?:\r\n#|$)
separate=\r\n#MESSAGE\r\n
```
您要是方便能否帮忙看下？
脚本文件
链接：https://pan.quark.cn/s/4c065975b752
提取码：upiF
解压码：test

**Comment by satan53x** [comment]
导入不了的话，应该是因为(?P<msg>[\S\s]+?)是可以包含\r\n的，和se工具的默认段落分隔符冲突了，在没有使用unfinish分组的情况下只需要简单修改se设置页面分隔符为任意不会出现的字符就行。（比如⚡）

**Comment by satan53x** [comment]
至于提取是显示原文为空则是因为`(?P<name>.*)`可以为空，如果一定有名字简单改为+即可。
如果是同时存在有名字和没有名字的情况，改完+后用两个search分别处理带名字和不带名字的情况，不带名字的search删掉name分组就行。

**Comment by lightning32x** [comment]
> 导入不了的话，应该是因为`(?P<msg>[\S\s]+?)`是可以包含\r\n的，和se工具的默认段落分隔符冲突了，在没有使用unfinish分组的情况下只需要导入之前简单修改se设置页面分隔符为任意不会出现的字符串就行（比如⚡）。

感谢指导，确实是段落分隔符冲突的问题
