### ISSUE TITLE
大佬可以添加对多级文件夹的支持吗

### ISSUE THREAD

**Issue by wjh191** [satan53x/SExtractor#33]

**Comment by satan53x** [comment]
暂不支持子文件夹。即使se支持，多文档输出的json也是包含子文件夹的，但是目前大部分翻译器都是不支持子文件夹的，所以意义不大。

之后会在合并分割页面实现收集分发功能，用于处理多级目录。

**Comment by satan53x** [comment]
或者你可以直接搜索一下是否有第三方工具可以收集多级目录文件，可能已经有类似的工具了。

**Comment by satan53x** [comment]
已添加收集分发功能

**Comment by HOKORISAMA** [comment]
Is this tool is only for unpacking of game script if yes then will it support packing of script in future.

**Comment by satan53x** [comment]
> Is this tool is only for unpacking of game script if yes then will it support packing of script in future.

Which tool are you referring to? 
The SExtractor is used for extracting and importing text from scripts. 
Unpacking and packing are typically done with other tools, such as Garbro.

**Comment by HOKORISAMA** [comment]
> > Is this tool is only for unpacking of game script if yes then will it support packing of script in future.
> 
> Which tool are you referring to? The SExtractor is used for extracting and importing text from scripts. Unpacking and packing are typically done with other tools, such as Garbro.

Like for cyberworks script, I know there is a tool named Csystem tools but whenever I try vntextpatch to insert the json to output it gives error like -String have too many lines.
Also I didn't understand who to skip some particular words or charcters appearing in the line.
I don't know anything about reagex filtering and your tool is in Chinese.
So I changed to to English for UI window that helped a bit.

**Comment by satan53x** [comment]
> Like for cyberworks script, I know there is a tool named Csystem tools but whenever I try vntextpatch to insert the json to output it gives error like -String have too many lines. Also I didn't understand who to skip some particular words or charcters appearing in the line. I don't know anything about reagex filtering and your tool is in Chinese. So I changed to to English for UI window that helped a bit.

Give me one of your .a0 script, I'll show you how to extract and import it.

**Comment by satan53x** [comment]
> Like for cyberworks script, I know there is a tool named Csystem tools but whenever I try vntextpatch to insert the json to output it gives error like -String have too many lines. Also I didn't understand who to skip some particular words or charcters appearing in the line. I don't know anything about reagex filtering and your tool is in Chinese. So I changed to to English for UI window that helped a bit.

Give me one of your .a0 script, I'll show you how to extract and import it.

**Comment by HOKORISAMA** [comment]
Okay wait a minute.

**Comment by HOKORISAMA** [comment]
[input.zip](https://github.com/satan53x/SExtractor/files/14429153/input.zip)
Here is it.

**Comment by satan53x** [comment]
@HOKORISAMA 
![image](https://github.com/satan53x/SExtractor/assets/138396258/51fadf57-a1fa-42fe-a65f-82244697e6bb)
Put all the `a0` files into the working directory, then select the `Cyberworks` engine in SE. 
Because your game uses UTF-16 encoding, select `__None` for regex to use the default.

![image](https://github.com/satan53x/SExtractor/assets/138396258/cb74a5af-350f-48f2-bf4c-0d40c00e41a5)
If you have chosen the `多文档` export method, the extracted JSON files will be in the `orig` directory.
Simply place the translated JSON files into the `trans` folder. No other settings need to be changed. Just click `提取/导入` to proceed with the import.

**Comment by HOKORISAMA** [comment]
What about export?

**Comment by satan53x** [comment]
> What about export?

The Extract/Import both use the same button. 
When SE detects translated JSON files with the same names in the `trans` folder, pressing this button will initiate the import process. 
The newly generated files will be located in the `new` folder.
![image](https://github.com/satan53x/SExtractor/assets/138396258/b2d29a62-4c5f-46a1-ad1e-ae541bfc1ed9)

**Comment by satan53x** [comment]
![image](https://github.com/satan53x/SExtractor/assets/138396258/e71aebc4-d869-46f6-8ed2-97b1e8eb9eb4)
The `trans` folder contains the JSON files after translation.

**Comment by HOKORISAMA** [comment]
> ![image](https://private-user-images.githubusercontent.com/138396258/308432764-e71aebc4-d869-46f6-8ed2-97b1e8eb9eb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwOTg5NDAsIm5iZiI6MTcwOTA5ODY0MCwicGF0aCI6Ii8xMzgzOTYyNTgvMzA4NDMyNzY0LWU3MWFlYmM0LWQ4NjktNDZmNi04ZWQyLTk3YjFlOGViOWViNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQwNTM3MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05M2RjMzM4MjdkOWNmN2JkOTMxN2I5OWNmNWU2YWYxYmE3ZDgwYjQ2OTZjYzMxMWQ0ZmJkYzNlMzU2NGI1OGQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1B5lDYJZC3GnjW2xlPgA1idxDq3u3iSf66ymvtlBfWk) The `trans` folder contains the JSON files after translation.

Thanks it worked atleast the export.

**Comment by satan53x** [comment]
```
    "name": "ÿÿ\u0001n\u0002瀬人",
    "message": "「……は～～～～……」"
```
Cyberwork has some special control texts. It is recommended to process them in the JSON before translation.
You can just delete the control texts and keep only the valid text to prevent translation errors.
```
    "name": "瀬人",
    "message": "「……は～～～～……」"
```
Of course, if you need to delete them in bulk, you may require some regex experience to perform batch replacements in a text editor such as `EmEditor` or `Sublime`.

**Comment by HOKORISAMA** [comment]
> ```
>     "name": "ÿÿ\u0001n\u0002瀬人",
>     "message": "「……は～～～～……」"
> ```
> 
> `Cyberworks` has some special control texts. It is recommended to process them in the JSON before translation. If you use machine translation, you can simply delete the control texts and keep only the valid text to prevent translation errors.
> 
> ```
>     "name": "瀬人",
>     "message": "「……は～～～～……」"
> ```
> 
> Of course, if you need to delete them in bulk, you may require some regex experience to perform batch replacements in a text editor such as `EmEditor` or `Sublime`.
I'll do translation myself and yeah for this reagex I manage with some python program.

**Comment by HOKORISAMA** [comment]
I am getting some errors about the translation length exceeded--
![image](https://github.com/satan53x/SExtractor/assets/160050298/335e5384-f452-4dc3-9252-f1db36a93aab)

**Comment by satan53x** [comment]
Uncheck the truncation option in the bottom left corner. Cyberworks engine generally doesn't require truncation.

**Comment by HOKORISAMA** [comment]
> Uncheck the truncation option in the bottom left corner. Cyberworks engine generally doesn't require truncation(`截断`).

Everythings working fine but I have some issues like--
1.How can i insert linebreak in lines , I tried \n but it didn't worked.
2.There is some japanese words that is showing before translated lines and aren't available in the json files to translate.
3.Is there anyway to change the font of the games the default one sucks, the gap between each word is too much.

**Comment by satan53x** [comment]
> Everythings working fine but I have some issues like--

1. The "\n" in the Cyberworks engine seems to be used to indicate the end of a sentence and cannot be used for line breaks; it automatically wraps text. Looking at the text structure, if a line break is needed, the sentence needs to be split into two structures. It's not something that can be handled by simply extracting text; it requires some additional operation code bytes.
2. Will all the sentences appear? Or just a part, please paste a Japanese original sentence to see.
3. Not sure, but generally speaking, the font in games can be modified by editing the CreateFont of the exe file. Usually, the font name for ADV is `ＭＳ ゴシック`. You can try searching `ＭＳ` and modifying it in the exe file, ensuring that the byte length remains unchanged, and filling in any insufficient bytes with 00.

**Comment by Cosetto** [comment]
[Release.zip](https://github.com/satan53x/SExtractor/files/14433436/Release.zip)
This should be VNTextPatch supports utf-16 Csystem

**Comment by HOKORISAMA** [comment]
> [Release.zip](https://github.com/satan53x/SExtractor/files/14433436/Release.zip) This should be VNTextPatch supports utf-16 Csystem

Thanks bro will check it out.

**Comment by Cosetto** [comment]
> > Uncheck the truncation option in the bottom left corner. Cyberworks engine generally doesn't require truncation(`截断`).
> 
> Everythings working fine but I have some issues like-- 1.How can i insert linebreak in lines , I tried \n but it didn't worked. 2.There is some japanese words that is showing before translated lines and aren't available in the json files to translate. 3.Is there anyway to change the font of the games the default one sucks, the gap between each word is too much. ![Screenshot (78)](https://private-user-images.githubusercontent.com/160050298/308516511-95dfc4a1-3f57-46ef-9690-0ca539255f7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMjE0MjgsIm5iZiI6MTcwOTEyMTEyOCwicGF0aCI6Ii8xNjAwNTAyOTgvMzA4NTE2NTExLTk1ZGZjNGExLTNmNTctNDZlZi05NjkwLTBjYTUzOTI1NWY3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQxMTUyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzNjMjcwYWQ3NTM1YWNhMWRlNWM4MTIxYTQ1MjJiOWU2OGE1YTczMDM5MDNiOTg3YjEyYTgzMzcyY2M5MmMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7evGbqu9aXPtViQmFifl81v57sMBwNj0jsK2jyh7btg) ![Screenshot (77)](https://private-user-images.githubusercontent.com/160050298/308516523-4f2553ea-8563-4512-8f38-6da8b3e0d99b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMjE0MjgsIm5iZiI6MTcwOTEyMTEyOCwicGF0aCI6Ii8xNjAwNTAyOTgvMzA4NTE2NTIzLTRmMjU1M2VhLTg1NjMtNDUxMi04ZjM4LTZkYThiM2UwZDk5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQxMTUyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDAxZDI5MWRjY2RlMDMzNTc3MDEzODhmMGEzMDljYzRhZWJiNjE0ZTI3ZjNmOThmNDM5NTllNTc0MjZhZTUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T2xPXC-raZf8PK5B4CF8ngUQnT6a-4gSfC9M--b6Vxk) ![Screenshot (76)](https://private-user-images.githubusercontent.com/160050298/308516532-3c82ee20-8943-4988-a5e3-7d7ba9453e5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMjE0MjgsIm5iZiI6MTcwOTEyMTEyOCwicGF0aCI6Ii8xNjAwNTAyOTgvMzA4NTE2NTMyLTNjODJlZTIwLTg5NDMtNDk4OC1hNWUzLTdkN2JhOTQ1M2U1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQxMTUyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzFjYzQwOTEwYzQxZDYwNjMwNTdiMGRjYjU4OTY0MDMyODNkYWNkNjhiOTdjYTZhZGY2Mzg4N2QyNGM5YjUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WTIV7fDX6wnI_3MkQOSeA5XCTFJB_Ew5uwQHzoiJmyw)

Btw, is the default settings of the game, or did you change anything to make the space between characters shrink?

**Comment by HOKORISAMA** [comment]
> > > Uncheck the truncation option in the bottom left corner. Cyberworks engine generally doesn't require truncation(`截断`).
> > 
> > 
> > Everythings working fine but I have some issues like-- 1.How can i insert linebreak in lines , I tried \n but it didn't worked. 2.There is some japanese words that is showing before translated lines and aren't available in the json files to translate. 3.Is there anyway to change the font of the games the default one sucks, the gap between each word is too much. ![Screenshot (78)](https://private-user-images.githubusercontent.com/160050298/308516511-95dfc4a1-3f57-46ef-9690-0ca539255f7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMjE0MjgsIm5iZiI6MTcwOTEyMTEyOCwicGF0aCI6Ii8xNjAwNTAyOTgvMzA4NTE2NTExLTk1ZGZjNGExLTNmNTctNDZlZi05NjkwLTBjYTUzOTI1NWY3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQxMTUyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzNjMjcwYWQ3NTM1YWNhMWRlNWM4MTIxYTQ1MjJiOWU2OGE1YTczMDM5MDNiOTg3YjEyYTgzMzcyY2M5MmMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7evGbqu9aXPtViQmFifl81v57sMBwNj0jsK2jyh7btg) ![Screenshot (77)](https://private-user-images.githubusercontent.com/160050298/308516523-4f2553ea-8563-4512-8f38-6da8b3e0d99b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMjE0MjgsIm5iZiI6MTcwOTEyMTEyOCwicGF0aCI6Ii8xNjAwNTAyOTgvMzA4NTE2NTIzLTRmMjU1M2VhLTg1NjMtNDUxMi04ZjM4LTZkYThiM2UwZDk5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQxMTUyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDAxZDI5MWRjY2RlMDMzNTc3MDEzODhmMGEzMDljYzRhZWJiNjE0ZTI3ZjNmOThmNDM5NTllNTc0MjZhZTUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T2xPXC-raZf8PK5B4CF8ngUQnT6a-4gSfC9M--b6Vxk) ![Screenshot (76)](https://private-user-images.githubusercontent.com/160050298/308516532-3c82ee20-8943-4988-a5e3-7d7ba9453e5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMjE0MjgsIm5iZiI6MTcwOTEyMTEyOCwicGF0aCI6Ii8xNjAwNTAyOTgvMzA4NTE2NTMyLTNjODJlZTIwLTg5NDMtNDk4OC1hNWUzLTdkN2JhOTQ1M2U1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQxMTUyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzFjYzQwOTEwYzQxZDYwNjMwNTdiMGRjYjU4OTY0MDMyODNkYWNkNjhiOTdjYTZhZGY2Mzg4N2QyNGM5YjUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WTIV7fDX6wnI_3MkQOSeA5XCTFJB_Ew5uwQHzoiJmyw)
> 
> Btw, is the default settings of the game, or did you change anything to make the space between characters shrink?

The link you gave is missing the exe file and yes i changed the settings to shrink the text.

**Comment by HOKORISAMA** [comment]
> Oh, I forgot. But I just checked, vntextpatch extracted first few scripts, then threw an error. I'll include the modified CSystemScript.cs (for utf16) if anyone knows how to fix. [a.zip](https://github.com/satan53x/SExtractor/files/14433721/a.zip)

Sure.

**Comment by Cosetto** [comment]
Hm, that's weird

**Comment by HOKORISAMA** [comment]
> Hm, that's weird

The .a0 file here are not for the game i am working on right now the one i have uploaded here are for-SEWOHAYAMI,
And right now i am trying OYAKO X SHUFFLE.

**Comment by HOKORISAMA** [comment]
@satan53x , @Cosetto 
I am an idiot there is an option to change the font type in the very exe file of game , I just noticed it and with that everything seems fine .
Thank you for your help .

**Comment by Cosetto** [comment]
You can use d2d1.dll from vntextproxy + a .ttf font to hook

**Comment by HOKORISAMA** [comment]
> You can use d2d1.dll from vntextproxy + a .ttf font to hook

Ohh, Got it.

**Comment by Cosetto** [comment]
odn Valkyria doesn't accept half-width text.
![image](https://github.com/satan53x/SExtractor/assets/81801486/0894ffb4-5bf3-49ca-9058-141a0b42f5a9)
Dxlib here is PixStudio not Dxlib of LuneTeamTB.

**Comment by satan53x** [comment]
odn repack: https://github.com/satan53x/GARbro/releases/tag/v1.5.44-d3

**Comment by satan53x** [comment]
> Dxlib here is PixStudio not Dxlib of LuneTeamTB.

I forgot what the pixstudio script looks like, maybe you can upload a script and I will check it out tomorrow.

**Comment by HOKORISAMA** [comment]
@Cosetto and @satan53x 
Sorry for bothering you guys but i was just wondering you guys have came across any tool that can extract and repack the resources of of [Ail engine](https://vndb.org/p207) ?
I tried searching everywhere but was unable to find any and this engine uses archives like gall00.dat, gall01.dat and for script it uses Sall.snl and some Pall.dat and vall.dat.

**Comment by Cosetto** [comment]
Well, there's no info in the config file, it only changes font size. To close the gap, you need to debug and patch the exe to disable full-width rendering, I guess.
Another way is if you know how to use [this function](https://github.com/arcusmaximus/VNTranslationTools/blob/36fbe909d02f2e9bb187443e03e2df595f56bfec/VNTextProxy/Util/StringUtil.cpp#L18-L24) of vntextproxy, you can turn the full-width into half-width.

**Comment by HOKORISAMA** [comment]
> Well, there's no info in the config file, it only changes font size. To close the gap, you need to debug and patch the exe to disable full-width rendering, I guess. Another way is if you know how to use [this function](https://github.com/arcusmaximus/VNTranslationTools/blob/36fbe909d02f2e9bb187443e03e2df595f56bfec/VNTextProxy/Util/StringUtil.cpp#L18-L24) of vntextproxy, you can turn the full-width into half-width.

And about the repacking tool of ail engine?

**Comment by Cosetto** [comment]
No tool for Ail, not every engine has tools. If you can't find any info on github, it means no one has made it.
Well, you need to implement your own script format to vntextpatch for .odn, or you can use SExtract since it supports .odn's script.
