### ISSUE TITLE
NekoSDK提取/回嵌出现错误

### ISSUE THREAD

**Issue by PiDanShouRouZhouXD** [satan53x/SExtractor#34]
![image](https://github.com/satan53x/SExtractor/assets/38401147/2322fbcb-d6af-426d-a6ae-c229e514aa88)
如上图，这部分的文本在游戏内无法正常显示，原因不明。
表现为播放时完全不显示，查看log时则是显示日文未替换的部分。
![image](https://github.com/satan53x/SExtractor/assets/38401147/16a6f259-bfad-4021-9f62-38a4a92e4e21)
在对文本日语部分进行了二进制替换后，游戏则会直接崩溃。
请问这是游戏自身的问题还是导入导出问题？

**Comment by satan53x** [comment]
导入时打印窗口是否有警告或者报错？

**Comment by PiDanShouRouZhouXD** [comment]
应该是没有的。
![image](https://github.com/satan53x/SExtractor/assets/38401147/820d93be-79f4-4d50-ad96-0e62aea96ecf)

**Comment by satan53x** [comment]
> ![image](https://private-user-images.githubusercontent.com/38401147/307600082-16a6f259-bfad-4021-9f62-38a4a92e4e21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NzQ5OTIsIm5iZiI6MTcwODg3NDY5MiwicGF0aCI6Ii8zODQwMTE0Ny8zMDc2MDAwODItMTZhNmYyNTktYmZhZC00MDIxLTlmNjItMzhhNGE5MmU0ZTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDE1MjQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZDE3YzNlYzVhN2RkZTE4YjE5YmFmODk1YTU3YjE0MzM3YTI4MTE5ZGRlNmExOWRiMDUxMWJjYTFjYTYyNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yx_kMay4woyMqPfnlfEgB2_6dJghuAEf1ioHCmOjodk) 

游戏截图中文本在剧本中的位置是？

**Comment by PiDanShouRouZhouXD** [comment]
> > ![image](https://private-user-images.githubusercontent.com/38401147/307600082-16a6f259-bfad-4021-9f62-38a4a92e4e21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NzQ5OTIsIm5iZiI6MTcwODg3NDY5MiwicGF0aCI6Ii8zODQwMTE0Ny8zMDc2MDAwODItMTZhNmYyNTktYmZhZC00MDIxLTlmNjItMzhhNGE5MmU0ZTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDE1MjQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZDE3YzNlYzVhN2RkZTE4YjE5YmFmODk1YTU3YjE0MzM3YTI4MTE5ZGRlNmExOWRiMDUxMWJjYTFjYTYyNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yx_kMay4woyMqPfnlfEgB2_6dJghuAEf1ioHCmOjodk)
> 
> 游戏截图中文本在剧本中的位置是？

序章，即sc_000_000_000_000.txt。
以下为剧本、导出json，翻译json和新生成的文件：
[scr_extract.zip](https://github.com/satan53x/SExtractor/files/14396809/scr_extract.zip)

**Comment by satan53x** [comment]
彳亍，明天看一下，今天电脑关了。

**Comment by satan53x** [comment]
![image](https://github.com/satan53x/SExtractor/assets/138396258/14943750-e52e-4d88-b9c2-bbcd676691d2)
看起来这句话是被正确提取和导入了的。
你确定你现在游戏读取的是这个最新的txt吗？

**Comment by PiDanShouRouZhouXD** [comment]
> ![image](https://private-user-images.githubusercontent.com/138396258/307647393-14943750-e52e-4d88-b9c2-bbcd676691d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MzU0NjQsIm5iZiI6MTcwODkzNTE2NCwicGF0aCI6Ii8xMzgzOTYyNTgvMzA3NjQ3MzkzLTE0OTQzNzUwLWU1MmUtNGQ4OC1iOWMyLWJiY2Q2NzY2OTFkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQwODEyNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NWRlMjRjODdiNjYzOGM0ZjM4MjFiYjdkNzRiOGEyZjA1NDQ5OTMwYjVjM2VmZmM3YjhjYzMyODQxNjM4ZDQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3EmEw1YzDa8tciIUF3iElY77I9p-Y6BPo3lUfc0OgjQ) 看起来这句话是被正确提取和导入了的。 你确定你现在游戏读取的是这个最新的txt吗？

是的，我可以确定。是否需要游戏本体来进行debug?

**Comment by satan53x** [comment]
更新了SE，现在会提取LOG显示用的文本了。
不过它这个文本本身好像并不会在对话框UI里边显示，只用于LOG。

**Comment by PiDanShouRouZhouXD** [comment]
> 更新了SE，现在会提取LOG显示用的文本了。 不过它这个文本本身好像并不会在对话框UI里边显示，只用于LOG。

非常感谢。我检查了一下，确实如此，这段文本只会显示在log中。
