### ISSUE TITLE
运行bat提示报错

### ISSUE THREAD

**Issue by bzxbao123** [satan53x/SExtractor#36]
你好，我这边是直接整包直接下载下来的，先安装成功了环境，然后运行了run.bat.
并没有窗口弹出来，直接提示有函数未找到，能看看是什么原因吗
![Snipaste_2024-03-03_17-46-42](https://github.com/satan53x/SExtractor/assets/45854057/22cc3ed5-6723-42f3-b464-023969f8f0e5)

**Comment by satan53x** [comment]
你是覆盖的之前旧版本的SE吗？几个月前有个一次脚本迁移，从根目录移动到了main文件夹。
如果一定要覆盖则需要把根目录下的main_extract.py删除。

**Comment by satan53x** [comment]
我刚刚试了下了zip包并解压到全新的路径，可以正常运行啊？

**Comment by satan53x** [comment]
你的python版本是？

**Comment by bzxbao123** [comment]
我是全新下载下来的。
![Snipaste_2024-03-03_18-27-41](https://github.com/satan53x/SExtractor/assets/45854057/ecd926b1-2326-42bf-9d6f-c4b46900d9d1)

**Comment by satan53x** [comment]
不确定是不是版本太低了，至少要3.9。推荐是3.11

**Comment by bzxbao123** [comment]
我更新了下版本，报错又又变了
![Snipaste_2024-03-03_20-23-08](https://github.com/satan53x/SExtractor/assets/45854057/c48574a7-476f-415e-aae3-05c67a8a20d6)
![Snipaste_2024-03-03_20-23-21](https://github.com/satan53x/SExtractor/assets/45854057/68f0cd1f-8074-46cb-a2e6-e8602c18d018)

**Comment by satan53x** [comment]
更换python之后重新安装依赖了吗？

**Comment by bzxbao123** [comment]
打扰了，已经解决了。我把所有的东西都重装了一次就行了
