### ISSUE TITLE
UIF无法生效

### ISSUE THREAD

**Issue by a115014** [satan53x/SExtractor#37]
satan53x大 您好~
[きみはぐ](http://game.anmo.info/game/view/6740)
引擎是QLIE
請問有辦法支援這遊戲嗎?
或者有其他支持中文顯示的方法?
謝謝!

**Comment by Cosetto** [comment]
Judging by release year. The qlie version should be "FilePackVer1.0"
You can use [arc_conv](https://github.com/amayra/arc_conv) with command "arc_conv.exe --pack qlie in_folder out_file.pack" (make sure you remain the subfolder path).

For qlie script, you can convert them to GB2312. But you need to patch the game's exe or use hook to support the encoding.

**Comment by a115014** [comment]
> Judging from the release year. The qlie version should be "FilePackVer1.0" or "FilePackVer3.0", I'm not sure. You can use [arc_conv](https://github.com/amayra/arc_conv) with command "arc_conv.exe --pack qlie in_folder out_file.pack" to pack (make sure to remain the subfolder path). For unpacking, you can use GARbro.
> 
> For qlie script, you can convert them to GB2312. But you need to patch the game's exe or use hook to support the encoding.

Hello,
Thank you for your response.
However, I'm currently stuck with the UIF hook being invalidated, and I don't know how to modify the game's executable.

**Comment by satan53x** [comment]
可以先试试通用教程修改exe编码和范围：https://www.bilibili.com/read/cv12543346

**Comment by Cosetto** [comment]
This could help https://github.com/Inori/FuckGalEngine/tree/master/QLIE/%E8%BE%B9%E7%95%8C%E6%A3%80%E6%B5%8B

**Comment by a115014** [comment]
> 我沒遇到過這個引擎，不清楚具體方法。 可以先試試通用教程修改exe編碼和範圍：https://www.bilibili.com/read/cv12543346
謝謝!我再研究看看

**Comment by a115014** [comment]
> This could help https://github.com/Inori/FuckGalEngine/tree/master/QLIE/%E8%BE%B9%E7%95%8C%E6%A3%80%E6%B5%8B

Thank you for informing
