### ISSUE TITLE
進行BIN暴力提取，翻譯完替換截斷處被插入了判斷式

### ISSUE THREAD

**Issue by FishYu-htps** [satan53x/SExtractor#38]
我提取的文本是BIN格式，我自己判斷每句文本都是[\x04-\x50]\x09開頭
所以嘗試寫了以下正則
00_skip=^\x81\x40\x00\x02\x0a
01_skip=^\x81\x40\x00
04_search=^(?P<msg>[\x40-\xFE]*)\x2f\x63\x00
10_search=^(?P<msg>[\x40-\xFE]*)\x00\x02\x0a
11_search=^(?P<msg>[\x40-\xFE]*)\x00$
separate=[\x04-\x50]\x09
文本算是有提取出，所以我判斷"separate=[\x04-\x50]\x09"應該有生效
並進行了翻譯，但在進行替換時，分割處被替換成了5B042D505D09([\x04-\x50]\x09)
這算是正常的嗎? 分割判斷是否不能這樣寫?
另外也想請教想要知道正則功能有哪些參數可以設定可以參考什麼資料或教學嗎?
像是separate或是ignoreDecodeError PostSkip這些，沒找到相關的文檔

**Comment by satan53x** [comment]
可以实现。
separate加上捕获分组就行，`separate=([\x04-\x50]\x09)`。
这样就能提取出来分隔符并写入，不会再额外补分隔符。

**Comment by satan53x** [comment]
> 像是separate或是ignoreDecodeError PostSkip這些，沒找到相關的文檔

这个没有文档，只能看预设正则和字面意思。

**Comment by FishYu-htps** [comment]
加上捕获分组後，確實不會有這樣的問題了，提取和替換都沒問題了
再請您幫忙了，最近在研究提取文本，自己想了很久才想到separate的用法，如果有相關文檔會更好，感謝

**Comment by satan53x** [comment]
Readme添加了部分正则说明
