### ISSUE TITLE
大佬有空可以解析一下MED的脚本吗

### ISSUE THREAD

**Issue by wjh191** [satan53x/SExtractor#41]
解包得到的脚本虽然是明文，但直接提取不会包含对话框的角色名（只有该文件第一次出现的角色名才会提取）。
比如：

巫小耶
「……ち、茅南……はぁ、はぁ……茅南……っ……
　ダメ……戦って……私はいいから、た、戦って……」
半ば意識を失ったままの巫小耶の、かすれた声が聞こえて
「く、くぅっ……本当……ですか？
　本当に、巫小耶ちゃんには何もしないと……約束して
　くれますか？」
「ああ、約束するぜ。
　お前がおとなしくなるんなら、倒れてる奴なんか
　襲っても意味ねえだろ？」

角色名巫小耶只出现了一次。

**Comment by satan53x** [comment]
因为这个名字的文本在剧本文件里本来就只出现了一次，实际显示的时候可能是变量调用。
我是直接参照ssynn的[game_translation](https://github.com/ssynn/game_translation)解析的，他就是直接提取文本的，原理如下：https://www.jianshu.com/p/53a7fa640864。
你可以找找有没有其他工具分析了文本结构的。
