### ISSUE TITLE
AI6WIN引擎文本提取

### ISSUE THREAD

**Issue by a115014** [satan53x/SExtractor#44]
satan大 您好!
請問能否增加AI6WIN引擎的提取?
謝謝!
範例文本如下
[stage07_01.ZIP](https://github.com/satan53x/SExtractor/files/14574443/stage07_01.ZIP)

**Comment by satan53x** [comment]
AI6WIN直接使用VNT就行。
为了避免重复造轮子，VNT支持的版本我一般不需要加。
`GalTransl`的`useful_tools`文件夹下`GalTransl_DumpInjector`就是VNT的GUI图形版本，也支持JIS替换。
