### ISSUE TITLE
Yu-ris Engine extraction issue

### ISSUE THREAD

**Issue by HOKORISAMA** [satan53x/SExtractor#53]
I was trying to extract the script files with SE and it extracted the the files after yst00126 but there is some some text in file before this too and is necessary to patch a game like yst00112 have the text to config names VNtextpatch can extract the script but the imported script crashes the game--
The Original files
[ysbin+WORKING.zip](https://github.com/satan53x/SExtractor/files/14717170/ysbin%2BWORKING.zip)

I configuration I used to extract is default--
![image](https://github.com/satan53x/SExtractor/assets/160050298/53c905ec-8cab-479c-a877-df68e511865b)

**Comment by satan53x** [comment]
Do you mean about character names? Some game of Yuris need to decrease the value of `extraData`, for example, to `extraData=5`.
(However, it can't be too low, as sometimes it will extract other Japanese text used for control which should not be translated.)

**Comment by HOKORISAMA** [comment]
> Do you mean character names? Some game of Yuris need to decrease the value of `extraData`, for example, to `extraData=5`. (However, it can't be too low, as sometimes it will extract other Japanese text used for control which should not be translated.)

It's a extracting the names but there is a file where all the names are written in a specific order and it's not extracting that file that is yst000112.

**Comment by satan53x** [comment]
> It's a extracting the names but there is a file where all the names are written in a specific order and it's not extracting that file that is yst000112.
> I mean it's not extracting any file before yst00126.

That's what I mean.
Decrease param `extraData`, maybe to 5.
`yst000112` should be extrated after decrease.

**Comment by satan53x** [comment]
In Yuris, operation code `WORD` usually only used dialogue or narration. 
The other operation has some parameters, and the `extraData` is used for limiting the smallest parameters' count.

**Comment by HOKORISAMA** [comment]
> In Yuris, operation code `WORD` usually is only used for dialogue or narration. The other operation has some parameters, and the `extraData` is used for limiting the smallest count of parameters.

It worked thanks.

**Comment by HOKORISAMA** [comment]
> > In Yuris, operation code `WORD` usually is only used for dialogue or narration. The other operation has some parameters, and the `extraData` is used for limiting the smallest count of parameters.
> 
> It worked thanks.

Also it's extracting some names in message part rather than Names-
![image](https://github.com/satan53x/SExtractor/assets/160050298/ba068d31-b20c-425d-b607-fa4ae2ea2f7e)
like line 3401

**Comment by satan53x** [comment]
Default regex only use to whole sentence.
Add some regex to depart name, such as:
```
01_skip=^M[\S\s]{2}"(?=[^\x81-\xEF]|■|◆)
10_search=^M[\S\s]{2}"(.+?)"
15_skip=^[^\x81-\xEF]
20_search=^(?P<name>.{1,20}?)(「.+」)$
21_search=^(?P<name>.{1,20}?)(（.+）)$
22_search=^(?P<name>.{1,20}?)(?P<unfinish>「.+)$
23_search=^(?P<name>.{1,20}?)(?P<unfinish>（.+)$
30_search=^(.+)(?<=」|）|。|！|？)$
31_search=^(?P<unfinish>.+)$
decrypt=auto
extraData=5
```
Just a sample, maybe need to add more end symbol.

**Comment by HOKORISAMA** [comment]
> Default regex only is used for whole sentence. Add some regex to depart name, such as:
> 
> ```
> 01_skip=^M[\S\s]{2}"(?=[^\x81-\xEF]|■|◆)
> 10_search=^M[\S\s]{2}"(.+?)"
> 15_skip=^[^\x81-\xEF]
> 20_search=^(?P<name>.{1,20}?)(「.+」)$
> 21_search=^(?P<name>.{1,20}?)(（.+）)$
> 22_search=^(?P<name>.{1,20}?)(?P<unfinish>「.+)$
> 23_search=^(?P<name>.{1,20}?)(?P<unfinish>（.+)$
> 30_search=^(.+)(?<=」|）|。|！|？)$
> 31_search=^(?P<unfinish>.+)$
> decrypt=auto
> extraData=5
> ```
> 
> Just a sample, maybe need to add more end symbol, or ignore some sentence not end with symbol.

It worked.

**Comment by HOKORISAMA** [comment]
The lines with these brackets -『』are extracting altogether.

**Comment by satan53x** [comment]
> Just a sample, maybe need to add more end symbol, or ignore some sentence not end with symbol.

This. Just add the end symbol that you need.
`30_search=^(.+)(?<=」|）|。|！|？|』)$`

**Comment by satan53x** [comment]
Or edit 30 and 31 to `30_search=^(.+)$` if you only need to depart name.

**Comment by HOKORISAMA** [comment]
> Or edit 30 and 31 to `30_search=^(.+)$` if you only need departing name.

The Default Yu-ris Pattern extracts just fine but but the still have name merging in the message line issue, after switching to the one you have provided sometime two lines joins to be one and the 『』problem too, Is it possible to just fix the name merging in the message part error without making any other issues?

**Comment by satan53x** [comment]
> Or edit 30 and 31 to `30_search=^(.+)$` if you only need departing name.

That's what I mean.
Equals that only add
```
22_search=^(?P<name>.{1,20}?)(?P<unfinish>「.+)$
23_search=^(?P<name>.{1,20}?)(?P<unfinish>（.+)$
```
into the default regex.
