### ISSUE TITLE
A request

### ISSUE THREAD

**Issue by Cosetto** [satan53x/SExtractor#54]
Can you help me dump the English text from these scripts with SExtract? I just to get the text, no need for insert.
![image](https://github.com/satan53x/SExtractor/assets/81801486/ba1ff2e6-ad1e-4b7e-b2b3-c3d5d5db6943)
[CC.zip](https://github.com/satan53x/SExtractor/files/14724018/CC.zip)

**Comment by satan53x** [comment]
This does not seem to be plain text, it may be compressed by the `lzss` algorithm.

**Comment by Cosetto** [comment]
Then, do you know any way to dump it?

**Comment by satan53x** [comment]
Try to decompress first. 
There may be some info bytes that should ignore in the file head.

In `tools` dir there are some python script using module `lzss` or `zlib` that show how to use.

(I use a phone now, maybe tomorrow to check it out)

**Comment by satan53x** [comment]
[cc_decompress.zip](https://github.com/satan53x/SExtractor/files/14730019/cc_decompress.zip)

`ContentStart = 0x18`
File head has `0x18` bytes infomation, I just abandon them when decompress.
If you want to compress back you need cache them.

**Comment by satan53x** [comment]
After decompress, choose engine `BIN` to extract.
```
00_skip=^[\S\s]{0,3}$
10_search=^[\S\s]([\x20-\xFC\r\n]+?)[\x00\x04]
checkJIS=[ -~\r\n]
ignoreDecodeError=1
separate=\xFD
```
Just a sample, maybe you should check if there's more structure of bytes.

**Comment by Cosetto** [comment]
Wait, do I need to get a lzss.dll or something:
```
    uncom = lzss.decompress(com)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
```

**Comment by satan53x** [comment]
Forgot to say
```
pip install pylzss==0.3.4
```

**Comment by Cosetto** [comment]
Thanks again bro
