### ISSUE TITLE
希望增加提取功能

### ISSUE THREAD

**Issue by TXT2GAM** [satan53x/SExtractor#6]
如果文本行混杂的代码过多，而且没有明显固定位置的话
需要二次甚至更多次提取才能完整过滤出代码。
比如在一行中出现多个换行符和<>标签，unfinish的命名分组对于固定位置的代码能够很好的处理，但是如果位置和数目随机的话就很麻烦了。应该只能写多个search分别考虑到所有情况。

所以希望新设立一个命名分组和一个对应的skip，这个skip用于跳过行内的代码部分。例如：
`<a>文本1<b>\n文本2<c><d>`
先用search将这行归入那个新的命名分组，然后对这个分组用`\\n|<.+?>`跳过代码部分，最后导出的文本就是完全不含代码的。

不知道这样的想法容不容易实现

**Comment by satan53x** [comment]
其实每行提取本来就支持多个匹配，只是一般在正则匹配时加了^表示行首，你不加就行。
比如你的例子：`<a>文本1<b>\n文本2<c><d>`
就可以用`10_search=([^ -~\n]+)`提取出两个文本来。
当然这只是一个例子，如果你文本里含有和控制标签一样的字符，也可以只按标签分割`10_search=([^<>\n]+)`
然后有一个postSkip可以用：`postSkip=^[a-zA-Z]`去掉以字母开头的。

**Comment by satan53x** [comment]
当然，如果是纯文本也可以直接用`Krkr_Reg`引擎，即使你不是Krkr的脚本。
可以看下预设的`Krkr_Orcsoft`规则：
```01_skip=^[*;]
02_skip=^\[(?!￥|名前|「|（)
10_search=^\[名前.+?id=【(?P<name>.+?)】
ctrlStr=^[A-Za-z]|^シンボル|^――$|^「|^（
endStr=￥```
这就是只匹配了名字，剩下的全部按照中括号`[^\\[\\]]+`分割每行，利用ctrlStr来跳过控制段。
（可以设置`sepStr=[^<>]+`）
因为他这种krkr在段落末尾有结束标志，所以还会设定endStr来自动结束段落，不然就需要自己匹配结束文本。
总之这个引擎只是帮忙处理未匹配的行。

**Comment by TXT2GAM** [comment]
请问在哪可以看到ctrlStr，endStr ，sepStr之类的用法
还有其他规则吗

**Comment by satan53x** [comment]
因为我都懒得写说明，所以要看只能去脚本里看实现，基本正则相关都在extract_TXT.py里，因为大多数脚本最后正则都会调用到extract_TXT里边，是同一个函数。
或者是看下其他预设有没有一些额外功能。
当然，有些引擎有额外的功能不在extract_TXT.py里，比如ctrlStr，endStr ，sepStr都是Krkr_Reg.py，一般都在脚本头部。
```
def initParseVar(var:ParseVar, regDic=None):
	if regDic == None:
		regDic = ExVar.regDic
	var.nameList = ExVar.nameList
	var.regList = GetRegList(regDic.items(), var.OldEncodeName)
	var.ignoreDecodeError = ExVar.ignoreDecodeError
	var.postSkip = ExVar.postSkip
	var.checkJIS = ExVar.checkJIS
	if var.checkJIS and var.OldEncodeName:
		var.checkJIS = var.checkJIS.encode(var.OldEncodeName)
```
这是extract_TXT.py的一个初始化函数，大概就这些功能了。
上边没提到的就checkJIS和ignoreDecodeError ，这个一般是BIN模式才会用。

**Comment by satan53x** [comment]
其实所有功能我应该都是分开写在了一些预设正则里边，不过就是没写说明，所以大家可能都不清楚。

**Comment by TXT2GAM** [comment]
明白了，确实靠目前的这些功能就足够了
我再仔细研究下这几个脚本

**Comment by satan53x** [comment]
其实有postSkip处理下，大部分都能解决。
就差一个postSearch了，但是我觉得单纯一个postSearch并不是很灵活，一般有这种需求二次提取就行。
再复杂就不建议用正则了，有时很复杂的正则不如写几句脚本一下就解决了，所以我还预留了一个extract_Custom.py，至少能帮忙处理文件读写。
