### ISSUE TITLE
AST封包工具

### ISSUE THREAD

**Issue by a115014** [satan53x/SExtractor#60]
satan大佬 您好
我使用您附帶的工具,做了一個補丁
發現封包好像有點問題,動態回想有BUG
不知能否解決?

遊戲名:彼女×彼女×彼女 ドキドキ フルスロットル

**Comment by satan53x** [comment]
什么现象？确定是封包还是译文问题？
就是解包之后不翻译直接封包会有问题吗？

**Comment by a115014** [comment]
> 什么现象？确定是封包还是译文问题？ 就是解包之后不翻译直接封包会有问题吗？

我放在 御爱同萌 
若是單純的文本,封包不會有問題
但裡面有其他動態文件,只有動態回想有BUG
已確認過原文件封包,還是會出BUG

**Comment by satan53x** [comment]
哪个版本的pack脚本？你上传一下arc2_pack.py呢。

**Comment by a115014** [comment]
> 哪个版本的pack脚本？你上传一下arc2_pack.py呢。

[arc2_pack.zip](https://github.com/satan53x/SExtractor/files/14816071/arc2_pack.zip)

**Comment by satan53x** [comment]
那可能需要自行修改一下脚本，大概是加密和压缩的问题。
48~53行：
```
		#附加文件
		IfCompress = filename.endswith('.adv') #剧本
		if IfCompress or data[0:4] == b'\x89\x50\x4E\x47': #图片
			data = xorBytes(data, b'\xFF') #加密
		if IfCompress:
			data = lzss.compress(bytes(data)) #压缩
```
现在默认是加密后缀为adv的剧本文件和`\x89\x50\x4E\x47`为头部字节的图片文件。
然后是压缩adv文件。

可能是你有不同头部字节的图片？

**Comment by satan53x** [comment]
如果包不大的话上传一下包也行。

**Comment by a115014** [comment]
> 如果包不大的话上传一下包也行。

請問需要本體嗎?

**Comment by satan53x** [comment]
> 請問需要本體嗎?

不用，封回去有问题的原始包就行。

**Comment by a115014** [comment]
> > 請問需要本體嗎?
> 
> 不用，封回去有问题的原始包就行。

[ https://terabox.com/s/1ntgnbU_CbSfcN7z8rqh_TA](url)

**Comment by satan53x** [comment]
大陆无法使用TeraBox

**Comment by a115014** [comment]
> 大陆无法使用TeraBox。 而且上传的是原日文包对吧？

1fichier 能用嗎?
請問是原日文包 還是我重新打包有問題的日文包?

**Comment by satan53x** [comment]
原日文包

**Comment by a115014** [comment]
> 原日文包。 1fichier应该可以。

[https://1fichier.com/?kr3qs08w69bqri1ijg3h](url)

**Comment by satan53x** [comment]
> 现在默认是加密后缀为adv的剧本文件和`89 50 4E 47`为头部字节的png图片文件。
> 然后是压缩adv文件。

在脚本头部添加了可配置需要压缩的文件后缀的变量`NeedToCompress`。
现在默认是`NeedToCompress = ['.adv', '.anm', '.db']`。
你试试，还有问题就往里边加后缀，一般来说除png和ogg之类的音频和图片类型外的都需要。
（因为Garbro是解压，解压是根据字节大小判断是否压缩就行；但是压缩脚本不一样，需要人工指定哪些类型要进行压缩。）

**Comment by Cosetto** [comment]
You can try using arc_conv to pack AST:  arc_conv.exe --pack arc12 <in_folder> <output_file> <1 or 2>

**Comment by a115014** [comment]
> > 现在默认是加密后缀为adv的剧本文件和`89 50 4E 47`为头部字节的png图片文件。
> > 然后是压缩adv文件。
> 
> 在脚本头部添加了可配置需要压缩的文件后缀的变量`NeedToCompress`。 现在默认是`NeedToCompress = ['.adv', '.anm', '.db']`。 你试试，如果还有问题就往里边加后缀，一般来说除png和ogg之类的音频和图片类型外的都需要。 （因为Garbro是解包，解包是根据字节大小判断是否压缩就行；但是封包脚本不一样，需要人工指定哪些文件类型要进行压缩。）

完美,感謝
