### ISSUE TITLE
AI5WIN ENGINE EXTRACTION ERROR

### ISSUE THREAD

**Issue by HOKORISAMA** [satan53x/SExtractor#61]
Hi satan bro, As usual i was just trying to extract some game with SE and when I tried to extract the .mes files from mes.arc file of game
Isaku by ELF it failed to extract .
I used the regex provided in the .fake.ini file , So i was just asking if your tool supports AI5WIN or not. Or do you have any plan to add support for this engine.

Thank you.

**Comment by satan53x** [comment]
The regex `[BIN AI5WIN AI5WINScriptTool提取txt]` in `fake.ini` is only used to 2nd extraction.
So you should use `AI5WINScriptTool`  to extract txt from mes first.

**Comment by HOKORISAMA** [comment]
> The regex `[BIN AI5WIN AI5WINScriptTool提取txt]` in `fake.ini` is only used to 2nd extraction. So you should use `AI5WINScriptTool` to extract txt from mes first.

But the AI5WINSCRIPTTOOL is unable to extract the files it says --
Json object is not serializable
illegal multiple bytes.

**Comment by HOKORISAMA** [comment]
Fake.ini have another regex as well-
`[BIN AI5WIN 段落完全合并]
01_skip=^(?!1-TEXT|1-SYSTEM_TEXT)
10_search="【(?P<name>.+?)】"
15_search="(?P<unfinishANDpredel_unfinish>　)"
20_search="(?P<unfinish>.+?)"
structure=paragraph
separate=#
flag=skipIgnoreCtrl,skipIgnoreUnfinish
<不推荐的写法，仅供参考>`

**Comment by satan53x** [comment]
Both use for AI5WINScriptTool.

**Comment by satan53x** [comment]
>Mes script files can be used not just in AI5WIN, but also in AI6WIN and Silky Engine. For assembling and disassembling mes script files of AI6WIN use [AI6WINScriptTool](https://github.com/TesterTesterov/AI6WINScriptTool), for mes of Silky Engine use [mesScriptAsseAndDisassembler](https://github.com/TesterTesterov/mesScriptAsseAndDisassembler).

Maybe find another tool.
AI5WINScriptTool says Silky should use another.
Or upload some mes.

**Comment by HOKORISAMA** [comment]
> > Mes script files can be used not just in AI5WIN, but also in AI6WIN and Silky Engine. For assembling and disassembling mes script files of AI6WIN use [AI6WINScriptTool](https://github.com/TesterTesterov/AI6WINScriptTool), for mes of Silky Engine use [mesScriptAsseAndDisassembler](https://github.com/TesterTesterov/mesScriptAsseAndDisassembler).
> 
> Maybe find another tool. AI5WINScriptTool says Silky should use another. Or upload some mes.

I have tried Ai6winTool as well but still same-
here are some mes files.
[MES.zip](https://github.com/satan53x/SExtractor/files/14832491/MES.zip)

**Comment by satan53x** [comment]
The mes has mix structure. It use the old command table.
Just exchange the key 0 and 1 of `command_library` and `offsets_library ` in [ai5win_mes.py](https://github.com/TesterTesterov/AI5WINScriptTool/blob/main/ai5win_mes.py). (Or copy the value of 0 to 1)

![image](https://github.com/satan53x/SExtractor/assets/138396258/240bfbe8-dbb5-434f-b947-1e668579c333)

Here's the edited script: [ai5win_mes.zip](https://github.com/satan53x/SExtractor/files/14834196/ai5win_mes.zip)

**Comment by satan53x** [comment]
And the `txt` has different text strcture that regex in fake.ini is not prefect-adaptation.
In fact, its structure is simpler because its name and message are in the same string.

**Comment by satan53x** [comment]
> Thanks Also can you take a look at these mes files too these are for Shuusaku-- Apparently this game uses a engine that is derived from AI5WIN. [message.zip](https://github.com/satan53x/SExtractor/files/14834262/message.zip)

Not sure, it cannot see plaintext, maybe not decompress or decrypt when unpack?

**Comment by HOKORISAMA** [comment]
> > Thanks Also can you take a look at these mes files too these are for Shuusaku-- Apparently this game uses a engine that is derived from AI5WIN. [message.zip](https://github.com/satan53x/SExtractor/files/14834262/message.zip)
> 
> Not sure, it cannot see plaintext, maybe not decompress or decrypt when unpack?

I used a tool Made by the developer of who made tool for AI5win and AI6WIn-
Here is the tool is it can help you in some way--
[AIWArcTool.zip](https://github.com/satan53x/SExtractor/files/14834873/AIWArcTool.zip)

**Comment by satan53x** [comment]
Upload package.

**Comment by HOKORISAMA** [comment]
[Uploading message (2).zip…]()

**Comment by satan53x** [comment]
Checked it. Maybe has different compression or encrypt key. Cannot help.

**Comment by Cosetto** [comment]
These tools were made for YU-NO, but I doubt it would work
[Sus.zip](https://github.com/satan53x/SExtractor/files/14836318/Sus.zip)

**Comment by HOKORISAMA** [comment]
> These tools were made for YU-NO, but I doubt it would work [Sus.zip](https://github.com/satan53x/SExtractor/files/14836318/Sus.zip)

Well thanks but No luck here as well.
