### ISSUE TITLE
正则提取时异常中断

### ISSUE THREAD

**Issue by seelesern** [satan53x/SExtractor#63]
大佬们，我是用SiglusExtract提取的txt文件，但是正则提取时异常中断，请问是出了什么问题？是否是用SiglusTools才行？
![QQ图片20240403184450](https://github.com/satan53x/SExtractor/assets/116353684/8d76321f-cd5a-4f6b-b367-114c7542db0c)
![QQ图片20240404163359](https://github.com/satan53x/SExtractor/assets/116353684/a200e97d-5912-46b4-85f0-caffda6052ca)
![QQ图片20240404163404](https://github.com/satan53x/SExtractor/assets/116353684/ad3f6c0d-73fd-42cc-a505-0ecb57434749)

**Comment by satan53x** [comment]
编码没选对，你txt是utf-16的。

**Comment by seelesern** [comment]
> 编码没选对，txt选utf-16。 （记事本编码显示也不完全，你这个应该是带bom的）

谢谢大佬，解决了。御爱没了好可惜。
