### ISSUE TITLE
moonhir引擎处理

### ISSUE THREAD

**Issue by YeziTl** [satan53x/SExtractor#65]
我希望跑いじくりママ剩下几部，看了一下大佬你是把fbx文件放目录里，所以我想问一下moonhir的fbx要怎么处理？

**Comment by satan53x** [comment]
Garbro解开fpk之后，fbx已经被解压了，而游戏免封包需要读取压缩的fbx，直接使用未压缩的fbx会报错。
以前的老脚本一直没有上传，刚刚更新到了tools/MoonHir文件夹下。

**Comment by satan53x** [comment]
最初是直接截断处理的文本。
不清楚修正fbx开头的0x08~0x27的这个索引区能不能够使文本不限制长度，因为以前没有处理这部分。
