### ISSUE TITLE
unfinish分组的文本回填问题

### ISSUE THREAD

**Issue by TXT2GAM** [satan53x/SExtractor#66]
目前已经发现了原因所在（不同语言的语序问题），但是没办法解决。
用实际的文本举个例子，

```
原文本：
You can find what we need <i>here</i>.
hello, <name>.

se提取：
You can find what we need \r\nhere\r\n.
hello, \r\n.

翻译后：
你可以在\r\n这里\r\n找到我们需要的东西。
你好，\r\n。

se回填：
你可以在<i>这里</i>找到我们需要的东西。
你好，<name>找到我们需要的东西。
```

回填时第二行就会出现问题。是因为在第一行翻译时，由于翻译后语序发生变化，符号“.”对应的不是“。”，而是“找到我们需要的东西。”，但是se回填第二行时依旧采用的是第一行的这种对应关系，就出现问题了。

**Comment by satan53x** [comment]
其实是SE的历史遗留BUG，因为一开始内部是用字典保存的，所以后边都是用的字典。
你把提取目录和正则发来看看，我看下能不能解决，主要这东西影响所有的引擎。

**Comment by TXT2GAM** [comment]
好的。正则是我参照fake.ini改的，导出方式是json origRN origRN，引擎txt
```
10_search=(?P<unfinish>[^<>]+)\<|\>([^<>]+)$
11_search=^(.+)$
```
https://wwz.lanzouq.com/iqIhF1w8y9te

**Comment by satan53x** [comment]
更新了

**Comment by TXT2GAM** [comment]
感谢，确实解决了

**Comment by TXT2GAM** [comment]
更新之后出现了新的bug，rpgmv引擎。
正常提取翻译后，回填时每一行均为“译文为空, 不替换”。然后人工检查文本，发现有的回填成功，有的回填失败（依旧是原文）。没发现什么规律。

**Comment by TXT2GAM** [comment]
rpgmv引擎，json origRN origRN，规则
```
00_skip=^(?!<root   >|<code101>|<code102>|<code401>|<code405>|<terms  >|<message>)
11_search=^<code401>[ -~]*(?P<unfinish>[\S\s]+?)[ -~]*$
21_search=^<.+?>([\S\s]+?)$
postSkip=^[ -~\s]+$
extractKey=all
```
翻译文件https://wwz.lanzouq.com/i6sXf1wgux0d
例如actors文件的`ルルカ`回填成功
map013文件的`えいっ、えい！　ほーら、悪いレバーちゃん！`回填失败

**Comment by satan53x** [comment]
行，五一之后我看看，现在可以先用着旧版本的。

**Comment by satan53x** [comment]
更新了，可以试试正不正常

**Comment by TXT2GAM** [comment]
另一个问题，也是关于unfinish分组的。
json字典格式提取到了这样的文本（`\r\n`连接的是unfinish内容）：
```
"人名A"
"人名A\r\n「对话内容\r\n对话内容」"
...```
从逻辑上来讲，假如删掉`"人名A"`这个键值对，在回填时应该显示`译文为空, 不替换 <文件名> 人名A`。但是恰好因为后面的unfinish分组也匹配到了`"人名A"`，即使删掉第一行，依旧会正常回填，这是不合理的。

**Comment by TXT2GAM** [comment]
可能会问我为什么会有这么奇怪的需求。实际上我处理某个rpg游戏时正好遇到了这种情况：游戏开发者把第一行的人名A与角色的立绘文件相绑定，因为不能翻译，否则会报错找不到图片文件。而第二行的人名A是属于code: 401的内容，是可以被翻译的。

**Comment by satan53x** [comment]
其实不是字典json本身不能保存，是Ainiee支持的这种字典不能保存，是因为它的值是单个字符串，所以在提取为json的时候就抛弃掉了。
所以用字典类型的话最好还是不要有译文一对多的，有这个需求的时候尽量使用列表类型。

**Comment by TXT2GAM** [comment]
> 就比如你这个`"人名A"`单独的这一行，其实在剧本里可能是多次出现的，但是字典json结构上并不能保存它出现的次数和位置。

是的。我并不了解内部字典的工作原理，我原本以为unfinish和单独匹配到这两者之间是分开的。比如删除`"人名A"`单独这一行仅会影响到非unfinish分组匹配到的`"人名A"`（可能不止一个）。
既然原理上不行那就没办法了，遇到这种情况就选列表类型。
