### ISSUE TITLE
能否添加对旧版Csystem(Shift-JIS编码)的文本GBK编码写入的功能？

### ISSUE THREAD

**Issue by sakura4214** [satan53x/SExtractor#7]
我查了下，这个引擎是按系统编码读取的，所以只要可以把Shift-JIS编码的文本改成GBK或者Unicode就行，我也尝试了使用VNTextProxy的sjs隧道功能，但是对这个游戏不管用，游戏名叫なつこい！

**Comment by satan53x** [comment]
添加了Cyberworks读取JIS的预设，但是需要自行处理控制段。
```
"message": "『\u0003さとし\u0001聡』というありふれた名前を持つ僕が生まれ育った、ありふれた田舎町。"
```
比如这种，这句话不支持GBK写入，要么删掉控制部分，要么使用JIS隧道或JIS替换，要么修改提取正则在提取时排除。
``是控制标识，`\u0003`和`\u0001`是后边跟随的文本长度。

**Comment by sakura4214** [comment]
设置如图
![image](https://github.com/satan53x/SExtractor/assets/113588801/834acf24-424d-4a39-8c02-fe4979329e8d)
但是提取时报错
![image](https://github.com/satan53x/SExtractor/assets/113588801/3f09646b-b6f2-4100-801e-99b25a9321cc)
是我那里设置不对吗？

**Comment by sakura4214** [comment]
我用[VNTranslationTools](https://github.com/arcusmaximus/VNTranslationTools)可以提，但是它的JIS隧道无法生效，JIS替换也是

**Comment by satan53x** [comment]
设置看起来没问题啊，我这样设置可以正常提取

**Comment by sakura4214** [comment]
抱歉，貌似我的文件出了问题，我再重新解包了试试

**Comment by sakura4214** [comment]
我把控制部分删了，接下来我该如何以GBK编码导入呢？或者说我该如何设置呢？我把翻译好了的文件以GBK编码保存在了trans文件夹，再点了一次“提取/写入”按钮，但是只再提取了一遍但是没有写入

**Comment by satan53x** [comment]
设置不变就行。
bin默认对脚本是读jis写gbk，中间处理的json都是utf-8不需要改编码。

**Comment by sakura4214** [comment]
非常感谢，成功解决了

**Comment by sakura4214** [comment]
又有个问题，人名的边框没有提取，导致乱码
![无阿姐是否合适就题](https://github.com/satan53x/SExtractor/assets/113588801/b8fe8313-1590-4614-bd0f-8a0fdf994dd9)
原来的边框是这样
![屏幕截图 2023-09-24 210416](https://github.com/satan53x/SExtractor/assets/113588801/78db9bdf-8ea1-4f64-9415-2507291c41b3)

**Comment by sakura4214** [comment]
不知道是程序内部的问题还是提取时没有提出来

**Comment by satan53x** [comment]
正则里括号放分组里边就行`10_search=^(?P<name>【.+?】)`

**Comment by sakura4214** [comment]
解决了，非常感谢
