### ISSUE TITLE
Help request

### ISSUE THREAD

**Issue by Cosetto** [satan53x/SExtractor#71]
Hello bro, I wonder if you could help me with this request, it's not for script but for multi-frame image archive of Qlie engine. So, this Chinese tool here can read, exporting and importing the content of the archive, [bExplorer.zip](https://github.com/satan53x/SExtractor/files/15196502/bExplorer.zip)
However, in the [latest game](https://vndb.org/v44184), the tool failed to read the multi-frame archive. Apparently GARbro can, I think it's because of [this code](https://github.com/morkt/GARbro/commit/e0f17747aecc35214a01212554092c292e99b8c0). Yet, I don't know how to implement that code to bExplorer (also written in C# btw). Here's a sample [back01.zip](https://github.com/satan53x/SExtractor/files/15144521/back01.zip)

**Comment by satan53x** [comment]
Bro, I'm on vacation now so I don't have a work computer available. 
I might not be back until May 4th.

**Comment by Cosetto** [comment]
Ok, I can wait until then

**Comment by satan53x** [comment]
[B浏览器.cs.zip](https://github.com/satan53x/SExtractor/files/15200831/B.cs.zip)
Cover the old `B浏览器.cs`.

**Comment by Cosetto** [comment]
Thanks again bro. It works!
