### ISSUE TITLE
BlackRainbow Engine Script issue

### ISSUE THREAD

**Issue by HOKORISAMA** [satan53x/SExtractor#72]
Hi, So as always I was trying to extract some file and this type it is BlackRainbow Engine , The issue is SE is unable to extract the script from the .spt files. 
I used GarBro for unpacking the sj_spt.dat then I tried to extract them directly with SE through the default BlackRainbow regex.
Am i doing something wrong? Is your tool supposed to extract the scripts during second stage extraction?
Here are the spt.dat and unpacked files if you wanna take a look.
Thanks--
[blackrainbow saimin 2.zip](https://github.com/satan53x/SExtractor/files/15208223/blackrainbow.saimin.2.zip)

**Comment by satan53x** [comment]
The `extraData` in regex is the game's xor key. You need find it first.
You can compare the first displayed-text in the game with the first text in the script file. (xor the two text's bytes)
`Blackrainbow` encrypt only displayed-text, not control-text, so you can find which is the first script.
```
init.spt -> title.spt -> E_001.spt or pro_001.spt
```
What's the first displayed-text in your game?

**Comment by satan53x** [comment]
![image](https://github.com/satan53x/SExtractor/assets/138396258/4ec03036-b3ae-4ff8-9805-aca3d5f0aee6)

Fortunately, your xor-key looks pretty simple, because half of the encrypted text is plain text.
I think it is:
```
extraData=\x01\x00\x00\x00
```
and the displayed-text is `……ボクは『後始末』をする。`

**Comment by HOKORISAMA** [comment]
> ![image](https://private-user-images.githubusercontent.com/138396258/327934299-4ec03036-b3ae-4ff8-9805-aca3d5f0aee6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MjAyMzksIm5iZiI6MTcxNDgxOTkzOSwicGF0aCI6Ii8xMzgzOTYyNTgvMzI3OTM0Mjk5LTRlYzAzMDM2LWIzYWUtNGZmOC05ODA1LWFjYTNkNWYwYWVlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQxMDUyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MDJhZDdlMzRjMThmNDA1ZmE5Y2JjMjcxNmYyZWY4ZDNkOTg5NTg4NDlmYmU2MDg3OGI0M2Q1ZjNhYzBjYzk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._Hd4Fiyu8x4UvDMK17NQW3kwA460_G0RscYn_etoTww)
> 
> Fortunately, your xor-key looks pretty simple, because half of the encrypted text is plain text. I think it is:
> 
> ```
> extraData=\x01\x00\x00\x00
> ```
> 
> and the displayed-text is `……ボクは『後始末』をする。`

It worked like a charm thanks.

**Comment by HOKORISAMA** [comment]
Can you tell me about the xoring process like I tried to convert `c…・クο『阪始蘭』・す・・` to bytes and got `b'\xc2\x80c\xe2\x80\xa6\xe3\x83\xbb\xe3\x82\xaf\xce\xbf\xe3\x80\x8e\xe9\x98\xaa\xe5\xa7\x8b\xe8\x98\xad\xe3\x80\x8f\xe3\x83\xbb\xe3\x81\x99\xe3\x83\xbb\xe3\x83\xbb'`

and with `……ボクは『後始末』をする。` i got `b'\xe2\x80\xa6\xe2\x80\xa6\xe3\x83\x9c\xe3\x82\xaf\xe3\x81\xaf\xe3\x80\x8e\xe5\xbe\x8c\xe5\xa7\x8b\xe6\x9c\xab\xe3\x80\x8f\xe3\x82\x92\xe3\x81\x99\xe3\x82\x8b\xe3\x80\x82'` .
Now the question is should i xor the corresponding positional bytes or use one as a key or something.

**Comment by satan53x** [comment]
![image](https://github.com/satan53x/SExtractor/assets/138396258/4ec03036-b3ae-4ff8-9805-aca3d5f0aee6)
`�c…・クο『阪始蘭』・す・・` is not plain text, you just use the bytes in script file. 
```
80 63 81 63 82 7B 83 4E 83 CD 81 77 8D E3 8E 6E 97 96 81 78 83 F0 82 B7 83 E9 81 42
```
![image](https://github.com/satan53x/SExtractor/assets/138396258/3d6e0edb-6273-4532-948d-7f5544c30581)
`……ボクは『後始末』をする。` is the text displayed in your game. (Just a sample, you can use the first text in your game)
Convert it to encode `Shift-JIS` : (may use 010Editor)
```
81 63 81 63 83 7B 83 4E 82 CD 81 77 8C E3 8E 6E 96 96 81 78 82 F0 82 B7 82 E9 81 42
```
Then xor them, you can get the repeated key. (Many tools can do this, even the windows calculator)
![image](https://github.com/satan53x/SExtractor/assets/138396258/4f6de3d0-0f2f-435a-8a9b-c636ea18fab1)

**Comment by satan53x** [comment]
> Also do the length of key varies for different games? And for packing should i use the key you provided in datapack.py that is in Tools/Blackrainbow?

No need. The key is just used to extract/import. Unpack/Pack dost need that.
And it will re-encrypt when use SExtractor to import. You doesn't need additional operations.

**Comment by HOKORISAMA** [comment]
> > Also do the length of key varies for different games? And for packing should i use the key you provided in datapack.py that is in Tools/Blackrainbow?
> 
> Unnecessary. The key is just used to extract/import. Unpack/Pack doesn't need that. And it will re-encrypt when use SExtractor to import. You don't need additional operations.
> 
> The length of key is not limited, but it seems that they are all 4-bytes in BlackRainbow. (Minimum repeat length)

Got it thanks.

**Comment by HOKORISAMA** [comment]
Hi, can you take a look at this tool it seems to be able to extract the script and if you can implement it SE so no one have to go through the trouble of looks for xor keys-
[black_saimin.zip](https://github.com/satan53x/SExtractor/files/15213049/black_saimin.zip)

Thanks.

**Comment by satan53x** [comment]
blackrb_spt.py
```
def mess_decrypt(txt):
    txt = bytearray(txt)
    for i in range(0, len(txt), 4):
        txt[i] ^= 1
    return txt
```
The same way. (`\x01\x00\x00\x00` in the case of 4-byte little-endian integer means `1`)
And it hardcodes the key, so it won't work on all games.

**Comment by HOKORISAMA** [comment]
> blackrb_spt.py
> 
> ```
> def mess_decrypt(txt):
>     txt = bytearray(txt)
>     for i in range(0, len(txt), 4):
>         txt[i] ^= 1
>     return txt
> ```
> 
> The same way. (`\x01\x00\x00\x00` in the case of 4-byte little-endian integer means `1`) And it hardcodes the key, so it won't work on all games.

Okay, thanks.
