### ISSUE TITLE
Old Cyberworks_Engine Formats

### ISSUE THREAD

**Issue by HOKORISAMA** [satan53x/SExtractor#73]
I was looking at older cyberworks game and noticed that they were using some different file format like rather than two files for scenario like `Arc01.dat` and `Arc04.dat`, There are just some `Arc.dat` , `Arca.dat` and so on and `Csystemtool` aren't able to extract them.
Extracting with Garbro Works fine But then VNTRANSLATION tools raises error.

So can you look at the arc.dat if it can be extracted or not.

[arc.zip](https://github.com/satan53x/SExtractor/files/15258565/arc.zip)

Thanks....

**Comment by Cosetto** [comment]
It's simple. This is not Csystem but different engine. And it seems like this is engine doesn't use index files like Csystem, so Arc.dat and Arca.dat are sole archives
![image](https://github.com/satan53x/SExtractor/assets/81801486/4aabc906-87ad-4120-8303-ca9cad9213a6)

**Comment by HOKORISAMA** [comment]
> It's simple. This is not Csystem but different engine. And it seems like this is engine doesn't use index files like Csystem, so Arc.dat and Arca.dat are sole archives ![image](https://private-user-images.githubusercontent.com/81801486/329161829-4aabc906-87ad-4120-8303-ca9cad9213a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDEwNTUsIm5iZiI6MTcxNTI0MDc1NSwicGF0aCI6Ii84MTgwMTQ4Ni8zMjkxNjE4MjktNGFhYmM5MDYtODdhZC00MTIwLTgzMDMtY2E5Y2FkOTIxM2E2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA3NDU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3Y2U3MGY1YWFjZTk4ZGU2ZWIxNzE1MjBiMzU5ZmZjOGZmNmY3ODlhNWZiZTU2ZmM0MzhhMjFmNzQ2YmFiMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pi98jCIdseT_I4FNVCQIY0XeWHZ2ZyaFdd4JLzdXYcg)

How silly of me. LoL...
So you of any tool for this?

**Comment by HOKORISAMA** [comment]
It seems to be plain text even in Arc.dat so maybe it can be extracted with SE ?
So there will be no need to find a packer and un-packer for it.
@satan53x can you please take a look at it.

**Comment by satan53x** [comment]
In general, not unpacking cannot change the byte length of individual scripts internally.
So, extracting without unpacking is not very meaningful, because English translations are generally longer than Japanese.

Perhaps you should try this game to see if it can read files without packaging.

**Comment by HOKORISAMA** [comment]
> In general, not unpacking cannot change the byte length of individual scripts internally. So, extracting without unpacking is not very meaningful, because English translations are generally longer than Japanese.
> 
> Perhaps you should try this game to see if it can read files without packaging.

You're absolutely right , I am able to display the English text but if the length of characters exceeds the length of Japanese characters then engine throws error.
![image](https://github.com/satan53x/SExtractor/assets/160050298/6381aa25-af87-464d-a138-f85b399303d3)

**Comment by HOKORISAMA** [comment]
No it can't read from folders, seems like this will be a though one to deal with so I am closing this issue without bothering you further.
