### ISSUE TITLE
How to repack translated files

### ISSUE THREAD

**Issue by Ronald181381** [satan53x/SExtractor#77]
I've tried and used the text extractor to translate vns from Kaguya, which works perfectly, but there's no way to repack the text files back into the original TBLSTR.ARC file, and any outside way of doing so would be useless, considering how the extracted txt files just contain plain text

**Comment by satan53x** [comment]
`Extract/Import` using the same button. (No need to change settings)
If you extract them by `MultiFile` mode, just put the translated files into `trans` folder.

**Comment by Ronald181381** [comment]
> `Extract/Import` using the same button. (No need to change settings) If you extract them by `MultiFile` mode, just put the translated files into `trans` folder. (Leave the files in `orig` folder unchanged) The new `TBLSTR.ARC ` in `new` folder after importing.
> 
> The corresponding relationship between original and translated files with different ExtractMode is in the `Instructions` tab.

Got it, thanks
