### ISSUE TITLE
Kaguya Game crashing after replacement

### ISSUE THREAD

**Issue by Ronald181381** [satan53x/SExtractor#79]
I tried translating a few lines of a kaguya vn, for a trial run, and:
1.) Speaker names were translated while dialogs were not
2.) The game showed a runtime error and crashed 2-3 within dialogs of the translated text
<img width="302" alt="image" src="https://github.com/satan53x/SExtractor/assets/170245814/f7f321b2-bc2a-43ce-8588-5492c9970b6f">
3.) I tried referencing [this issue](https://github.com/satan53x/SExtractor/issues/35), but neither could I get the exe modification done, nor could I get the Universal Injector Framework running

Here's the settings I used, which is basically what we get when the tool runns for the first time
![image](https://github.com/satan53x/SExtractor/assets/170245814/e8abd247-d2cb-456f-9742-fddfa158f0a6)
![image](https://github.com/satan53x/SExtractor/assets/170245814/f1a0c437-0cd0-45df-976e-397c2a605c95)

**Comment by satan53x** [comment]
SE like VNT do not process ’`script.arc` file, so some versions of Kaguya games need to choose  `Trans Length Truncated and Padded to Orig Length` when import, which means keeping the byte length of the text unchanged.
This is not a major issue when translating from Japanese to Chinese, but when translating to English, there are likely to be many cases where the translated text is longer than the original text.

**Comment by Ronald181381** [comment]
> SE like VNT do not process ’`script.arc` file, so some versions of Kaguya games need to choose `Trans Length Truncated and Padded to Orig Length` when import, which means keeping the byte length of the text unchanged. This is not a major issue when translating from Japanese to Chinese, but when translating to English, there are likely to be many cases where the translated text is longer than the original text.

Is there no way to bypass this?

**Comment by Ronald181381** [comment]
> Not sure if this is the problem you are encountering now. You can choose `Trans Length Truncated and Padded to Orig Length` to test.

It did work, but the translated text was cut in half

Is it not possible to use [HookFont..exe](https://github.com/Dir-A/VN_Localization_Tutorials/tree/main/%E5%85%B6%E5%AE%83/Hook%E5%AD%97%E4%BD%93) to reduce the byte size of the translated text?

**Comment by satan53x** [comment]
No, it's the file length problem not display.

But not sure if it is the problem.
Some versions of Kaguya games not limit the length of text, but limit the length of each line. That also may cause crashed.
You can try not to choose the Truncated but add some \n into json to make one line text shorter.

**Comment by Ronald181381** [comment]
> No, it's the file length problem not display.
> 
> But not sure if it is the problem. Some versions of Kaguya games not limit the length of text, but limit the length of each line. That also may cause crashed. You can try not to choose the Truncated but add some \n into text to make one line text shorter.

Hmm, I'll try that
Thanks for accommodating my stupid requests

**Comment by Ronald181381** [comment]
Interestingly enough, I tried injecting a blank translation and the text was pretty skewed, with random alphanummeric characters appearing
Then the game crashed

**Comment by satan53x** [comment]
SE can do nothing about it when Kaguya need to truncate.

**Comment by Ronald181381** [comment]
> SE can do nothing about it when Kaguya need to truncate.

Oh well, guess that's too bad

**Comment by Cosetto** [comment]
Well, [strarctool](https://github.com/crskycode/Kaguya_Tool/tree/main/StrArcTool) by Crsky can change the length of tblstr.arc, but you might want to modify it to support old tblstr.arc. You could try to create an issue to ask Crsky, and include sample file.

**Comment by Ronald181381** [comment]
> Well, [strarctool](https://github.com/crskycode/Kaguya_Tool/tree/main/StrArcTool) by Crsky can change the length of tblstr.arc, but you might want to modify it to support old tblstr.arc. You could try to create an issue to ask Crsky, and include sample file.

I didn't think of that
I did try it out, but gave up when it didn't work
Thank you, I'll try that
