### ISSUE TITLE
打了强化补丁后，很多不显示中文了。

### ISSUE THREAD

**Issue by wjzyxbaby** [satan53x/SExtractor#8]
Cyberworks / CSystem
https://vndb.org/v32026
大佬你好。这个游戏Arc04解包出来的文本我都汉化完了。不打强化补丁时，全部显示正常。但打了强化补丁后，很多原来显示中文的地方都变回了日文，一段剧情中文。一段剧情日文这样。强化补丁多了两个文件：tumamituadd01.app和tumamituadd01.dat。请问，这种情况有解决办法吗？

**Comment by satan53x** [comment]
因为强化补丁有文本，补丁一样可以用CSystemTools解（garbro也能解但是需要名字改为arc01和arc04）。
最好是用我Tools文件夹改过的CSystemTools解，原版解包有BUG（只改了解包时b0不转为png）。
但是无论是原版还是修改版，都存在封包之后游戏可能不能识别的问题，即使解出来什么也不修改，封回去也不行。
这是CSystemTools本身的封包问题，你可以找找有没有其他封包工具，或者去CSystemTools源码看看他是不是有什么BUG。

**Comment by wjzyxbaby** [comment]
哈哈，谢谢大佬。改成 arc01和arc04  后 的确能用CSystemArc_UTF16 提取。至于封包有没问题。晚点再试试。
昨晚我第一次封包，也是打不开游戏。后来我感觉不是封包问题，是json写入a0文件的问题。
原版CSystemTools是不会提取空的没内容的json（或者提取后删掉了）。
你这个SExtractor是会提取空的没内容的json，然后这些json不删一起写入a0文件，再封包就会有BUG。
删掉那些的没内容的json，在写入和封包就没问题。

**Comment by satan53x** [comment]
不是，普通的arc04.dat解封包是正常的。
但之前有人试过加强补丁app，解包后什么也不修改就直接封包也不行，没有进行提取json并导入a0这一步。

**Comment by wjzyxbaby** [comment]
新的CSystemTools带上cache.xml 确实可以。谢谢大佬
