### ISSUE TITLE
文本导入的问题

### ISSUE THREAD

**Issue by wjh191** [satan53x/SExtractor#80]
我的问题与这位相似：https://github.com/satan53x/SExtractor/issues/66
但我试了导入json列表 [ { name : 名字, message : 带换行对话 } ]、json列表 [ 带换行文本 ]这两种均无法解决。

以文档A-01.txt中的L29为例：
```
原文：
ここ・・・・どこだ？<CR>
何してたんだっけ、俺・・・？<CR>
あ・・・・んぅ・・・・・<KW><WinClear>

SE提取后：
ここ・・・・どこだ？\r\n何してたんだっけ、俺・・・？\r\nあ・・・・んぅ・・・・・

SE导入后：
这里………是哪里？我刚才，做了什么………？啊…………嗯…………<CR>
　<CR>
啊…………嗯呣………两个人都………唔………很熟练呢…………<KW><WinClear>
```

问题出在`あ・・・・んぅ・・・・・`这里，它使用了另一处对应的翻译：
```
jp: あ・・・・んぅ・・・・・\r\n二人とも・・・・・\r\nう・・・うまい・・・・
cn: 啊…………嗯呣………两个人都………唔………很熟练呢…………
```

从结果来看，虽然我使用了列表导入，但实际上好像还是字典导入。请问我该如何解决这个问题。

以下是相关的文本和使用的正则：
https://www.123pan.com/s/muyGjv-ytW4h.html

**Comment by satan53x** [comment]
你SE是最新版本的吗？你更新到最新试试

**Comment by satan53x** [comment]
彳亍，我周末看看，现在用的手机。

**Comment by satan53x** [comment]
> 从结果来看，虽然我使用了列表导入，但实际上好像还是字典导入。请问我该如何解决这个问题。

和之前的不是同一个BUG，不是字典导入的，而是顺序反了，你这个文本在json里一共有3个，最后一个和第一个位置弄反了。

**Comment by satan53x** [comment]
这个是字典json本身不支持：
https://github.com/satan53x/SExtractor/issues/66
