### ISSUE TITLE
Lzss decompress/compress help

### ISSUE THREAD

**Issue by Cosetto** [satan53x/SExtractor#81]
[Files](https://drive.google.com/file/d/1dKs0mHgjesweG8k0OStiTfJJDad32-5a/view?usp=sharing)
So, when I tried to decompress the files with the included python code, GARbro could read some of them, but some couldn't
![image](https://github.com/satan53x/SExtractor/assets/81801486/2787f277-63f7-43ff-8e68-0b8b03213fc7)
![image](https://github.com/satan53x/SExtractor/assets/81801486/93f8a8b7-18f5-482f-8c20-61c343b1ec3b)
I think the lzss algorithm of those files are different.
Could you also check Shinjiku_bin? After decompressing, none of them is readable.

**Comment by satan53x** [comment]
The LZSS decompression seems working fine.

The `7.xtx` from bin seems too big, you should change code `if (header_size >= 0x1000)` to 0x8000 in Garbro `ImageXTX.cs`, then you can see the image.
The `14.xtx` from bin seems not the xtx image but related to shader.

![image](https://github.com/satan53x/SExtractor/assets/138396258/da9b5302-201d-4a63-9ecf-c29d9d7c3a99)
The xtx files from Shinjiku_bin have type 8, and Garbro can only parse type not greater than 2.

**Comment by Cosetto** [comment]
I see, that's too bad then. Thanks anyway.
