### ISSUE TITLE
Bin extraction issue

### ISSUE THREAD

**Issue by HOKORISAMA** [satan53x/SExtractor#82]
I was trying to extract some file by debonosu works, SE was able to extract but on a closer look it missed some line like-
![image](https://github.com/satan53x/SExtractor/assets/160050298/357f603d-a117-4805-b9da-c5e37d86058c)
This is the image when i inserted the text . I searched the file in  orig folder but wasn't able to found this line-
here are the files.
[script.zip](https://github.com/satan53x/SExtractor/files/15441817/script.zip)
I used bin violent .

**Comment by satan53x** [comment]
`BIN_VIOLENT`'s default param `checkJIS=[\r\n]` means that half-width charactors only allow `\r` or `\n`.
If you need more, you should add them such as `checkJIS=[\r\n{}/]`.
