### ISSUE TITLE
里面的说明没看懂

### ISSUE THREAD

**Issue by maigeng** [satan53x/SExtractor#83]
>提取写入：
输出原文：transDic.output.json    >> 输入译文：transDic.json
输出原文：all.orig.json        >> 输入译文：all.trans.json
多文档输出原文文件夹：orig    >> 输入译文文件夹：trans
开启截断填充时，超长的文本会输出在cutoff.json中，在其中修正即可

>>正则匹配：
skip=表示跳过，search=表示搜索，00数字表示顺序，不一定依次，从小到大即可。
search匹配成功则不会进行下一个顺序匹配
匹配处理命名分组(?P<组名>)：name人名，msg对话，unfinish未结束对话（导出时与下一行合并）
未命名分组默认为msg
原文不要包含\r\n（如果有则需要在设置中更改段落分隔符）
TXT默认读写utf-8；BIN默认读jis写GBK；JSON模式只会操作value
TXT模式截断时会临时判定原文为jis译文为GBK，如无必要不要在TXT模式下打开截断。
BIN默认使用二进制字符串进行正则匹配，启用纯文本模式则会先decode编码为Unicode再进行正则匹配。

>合并分割：
合并：会缓存子文件信息，分割时行数填0则表示使用该缓存
收集：合并目录 >> 提取目录
分发：提取目录 >> 合并目录

看不懂，有大佬说下>>是什么玩意

**Comment by satan53x** [comment]
>>指数据流向，大概和`复制到`差不多意思。
输出原文是工具生成的原文文件，输入译文是你翻译后放置的译文文件位置。
根据你选择的导出格式和导出方式输出不一样，所以输入的译文也应该对应。

**Comment by satan53x** [comment]
比如选多文档导出，那原文就全在orig文件夹里，翻译后译文就放到trans文件夹，每个文件的名字和orig里一致就行。

**Comment by maigeng** [comment]
能不能举个例子，比如一个文件夹里面有ctrl和new文件夹以及几个txt格式的二进制文件，Ctrl里面有译文和生肉的JSON两个文件，然后我跑了se后，命令行显示译文为空不替换，怎么回事，我在游戏里面查看部分日文部分汉字，可译文和生肉的行数明明是一样的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月28日(周二) 下午4:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [satan53x/SExtractor] 里面的说明没看懂 (Issue #83)




 
&gt;&gt;指数据流向，大概和复制到差不多意思。
 输出原文是工具生成的原文文件，输入译文是你翻译后放置的译文文件位置。
 根据你选择的导出格式和导出方式输出不一样，所以输入的译文也应该对应。

**Comment by satan53x** [comment]
哪种导出格式？json文件名是啥？

**Comment by maigeng** [comment]
就nekosdk导出JSON有name和message那种，两个JSON文件名字就是all.orig.json和all.trans.json



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月28日(周二) 下午4:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [satan53x/SExtractor] 里面的说明没看懂 (Issue #83)




 
哪种导出格式？json文件名是啥？

**Comment by satan53x** [comment]
Nekosdk因为文本本身含有\r\n，和SE自身的分隔符冲突了，导入之前需要在设置页面把分隔符改成其他字符串，我记得Nekosdk的正则编辑框最后一行有说明啊。

**Comment by maigeng** [comment]
> Nekosdk因为文本本身含有\r\n，和SE自身的分隔符冲突了，导入之前需要在设置页面把分隔符改成其他字符串，我记得Nekosdk的正则编辑框最后一行有说明啊。
搞定了，谢谢，当时没注意看，不过导入后，游戏里面的文字一大一小的，怎么回事

**Comment by satan53x** [comment]
日本游戏有些默认字体是有这个问题，换一个中文字体就行。
不同的游戏有不同的字体换法，有些是游戏内就能选择，有些是在配置文件，有些是exe写死需要编辑字节。

**Comment by maigeng** [comment]
> 日本游戏有些默认字体是有这个问题，换一个中文字体就行。 不同的游戏有不同的字体换法，有些是游戏内就能选择，有些是在配置文件，有些是exe写死需要编辑字节。

我用了se提取器生成的uif_config.json，然后在里面改个"override_charset": 134，字体问题好像就解决了，为什么

**Comment by satan53x** [comment]
相当于改了exe里的CreateFont参数，只不过uif是hook方式的。
134就是0x86的十进制，0x86是中文，原始的0x80是日文。

**Comment by maigeng** [comment]
> 相当于改了exe里的CreateFont参数，只不过uif是hook方式的。 134就是0x86的十进制，0x86是中文，原始的0x80是日文。

原来如此，那有没有更多相关的资料，比如uif_config.json文件和winmm动态文件不知道具体是什么作用，我也听说过直接改exe文件里面的内容多少可能有出bug的风险
