### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87 in position 19: inv

### ISSUE THREAD

**Issue by maigeng** [satan53x/SExtractor#84]
之前是可以的，但是今天重新弄就不行了，我用转区打开txt文本也可以正常看，怎么解决

**Comment by satan53x** [comment]
不知道你什么文件和设置，看报错你是选的utf-8编码？但剧本文件是cp932的（也就是shift-jis）？

**Comment by maigeng** [comment]
破案了，就是没选对引擎，现在是好了，不过选项里面的说明教程我还是不懂&nbsp;


ee
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月28日(星期二) 下午4:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [satan53x/SExtractor] UnicodeDecodeError: &#39;utf-8&#39; codec can&#39;t decode byte 0x87 in position 19: inv (Issue #84)














 
不知道你什么文件和设置，看报错你是选的utf-8编码？但剧本文件是cp932的（也就是shift-jis）？
