### ISSUE TITLE
竹子社分社Berkshire Yorkshire

### ISSUE THREAD

**Issue by JassNull** [satan53x/SExtractor#88]
这个社的脚本文件好像有点不一样，试了俩游戏都提不出来
[tblstr.arc.zip](https://github.com/user-attachments/files/15574538/tblstr.arc.zip)
一些老工具好像能提取，就是不怎么好用，大佬能不能帮忙适配下

**Comment by satan53x** [comment]
更新了你试试呢。
你这个版本是没有ARI文件的吧

**Comment by satan53x** [comment]
正则加个search，你这文本末尾可能有多个\x00
```
10_search=^([^\x00]+)
extraData=fixLength,exportAri
```

**Comment by JassNull** [comment]
是的，没有ARI文件
试了下，可用的，感谢佬

**Comment by satan53x** [comment]
又改了一下，现在不需要匹配\x00了，匹配之前已经把\x00排除掉了。

**Comment by JassNull** [comment]
好 感谢！
