### ISSUE TITLE
关于txt多行重新分割

### ISSUE THREAD

**Issue by chuliu-hash** [satan53x/SExtractor#9]
好像是按标点和行数来的，「」 遇到这种符号在头尾，中间没有标点的可能会单独一个「分成一行，能不能设置成按原文行数尽量均分字符

**Comment by satan53x** [comment]
helper_text.py的67行：
```
symbolPattern = '[\\u3000-\\u303F\\uFF00-\\uFF65\\u2000-\\u206F]'
```
默认是按符号，理论上来说你改成'[\S\s]'就是任意字符了，会按照原长度比例最接近的位置分割，你可以试下。
不过这样有个问题就是换行的位置也是任意的，可能一个词语会断在中间，所以之前没有过这种需求。

**Comment by chuliu-hash** [comment]
> helper_text.py的67行：
> 
> ```
> symbolPattern = '[\\u3000-\\u303F\\uFF00-\\uFF65\\u2000-\\u206F]'
> ```
> 
> 默认是按符号，理论上来说你改成'[\S\s]'就是任意字符了，会按照原长度比例最接近的位置分割，你可以试下。 不过这样有个问题就是换行的位置也是任意的，可能一个词语会断在中间，所以之前没有过这种需求。
txt提取文本转成json再注回txt时
译文的行数如果比原文行数多，那么多余的行会被截断且没有提示，不能把多余行的字符都加在最后一行后面吗

**Comment by satan53x** [comment]
这不是重新分割的问题吧，按理说重新分割是无视译文行数的。
只有关闭重新分割才可能出现译文被抛弃的情况。

**Comment by chuliu-hash** [comment]
> 这不是重新分割的问题吧，按理说重新分割是无视译文行数的。 只有关闭重新分割才可能出现译文被抛弃的情况。

不是分割的问题，本来我自己原先是统一25个字符左右加一个换行的，然后发现注回去时可能会被截断才去试试重新分割的

**Comment by satan53x** [comment]
待会儿可以修改一下。
好像ChatGPT和传统云翻都只出现过换行减少，基本没有换行增加的情况，所以我是直接没处理译文多出来的行数。

**Comment by chuliu-hash** [comment]
> 待会儿可以修改一下。 好像ChatGPT和传统云翻都只出现过换行减少，基本没有换行增加的情况，所以我是直接没处理译文多出来的行数。

我之前用GPT翻的时候换行增加的情况还挺多的，因为支持自动换行我一般都把换行符全删了，但有个游戏对话框在某些场景会右移，自动换行的话有些字会跑到游戏框外直接看不到了

**Comment by satan53x** [comment]
你是因为自己按字符数加换行才会多吧，我是说正常直接用带换行符的文本翻译，一般换行符只会少不会多。
一个段落的总字符数变多倒是经常有的，但换行符一般不会。

**Comment by satan53x** [comment]
更新了

**Comment by chuliu-hash** [comment]
> 更新了

感谢感谢
