### ISSUE TITLE
Request for Support of More Engines

### ISSUE THREAD

**Issue by fushi002** [satan53x/SExtractor#94]
Thank you for always providing such great tools.

I have a small request: currently, the tool does not include the ANIM or Lune(.pac) engine.

As a result, I had to extract text for these two engines using the game_translation tool. However, the extracted text only displays the name once, which causes confusion when translating subsequent dialogue.

While it might be possible to modify the tool by referencing the code for these engines in the game_translation tool, unfortunately, I don't have the necessary skills to do so.

If you have the time, could you please include these engines in the SExtractor tool? The SExtractor tool is very convenient because it provides various options for text extraction.

If there is already a way to extract text in various formats using the game_translation tool and I am simply unaware of it, please let me know.

Thank you very much. Have a great day!

**Comment by Cosetto** [comment]
For Anim, it should be possible to add support. But for Lune, which is TmrHiroAdvSystem, it might be harder since SExtractor doesn't update the length of binary script required that. You can try using [vntextpatch](https://github.com/arcusmaximus/VNTranslationTools) and to deal with Lune.

**Comment by satan53x** [comment]
As mentioned above, Lune can use VNT.
I added ANIM in SE.
But the name is not just a matter of json dictionary format, the name string only appears once in the dat file.
I can only extract the voice variable as the name:
```
    "name": "f",
    "message": "「どうぞ、お気遣いなく」"
```
And then cooperate with the `name_replace` function in `text_conf.json`:
```
  "name_replace": {
    "f": "早苗"
  }
```
after that:
```
    "name": "早苗",
    "message": "「どうぞ、お気遣いなく」"
```
But the `"name"` field is only used to assist translation, and the translation and original text of `"name"` should be consistent when imported.

**Comment by satan53x** [comment]
If you don't need to extract the name for assistance, just delete `10_search`.
Delete `11_skip` can show all string.

**Comment by fushi002** [comment]
Thank you both for your help.
Have a great day!

**Comment by satan53x** [comment]
Updated again. 
Now the default regular expression has two more parameters:
```
dontImportName=1
extraData=guessName
```
It can automatically guess how to convert variables to names. Don't have to fill in `name_replace`.
If the guessing is wrong, you can also specify the name conversion in the exract_ANIM.py script.
