### ISSUE TITLE
kaguya译文导入，CScript引擎的问题

### ISSUE THREAD

**Issue by FFreQD** [satan53x/SExtractor#95]
1.kaguya tblstr.arc格式 译文导入出现问题，翻译一句或者全文导入时显示“译文为空，不替换”，6月底左右还没这样，换电脑了，下的最新的出现这样的问题。
2.CScript引擎
2.1有一个脚本无法提取文本报错如下
![134](https://github.com/user-attachments/assets/15e97b64-ffe4-40ce-86a2-e8593b17e3f8)
2.2封包出现的问题，提取脚本用了Crass、GARbro。
Crass提取的是未压缩脚本用dat_pack封包进游戏正文报错“压缩フアイルヘッゲ文字列が不正です” “压缩文件头字符串不正确”
GARbro提取的是压缩后脚本，封包后CG回想正常，有个鉴赏和正文读一段报错。
鉴赏报错"アーカイブファイル（.scr.dat）中に目的のフアイル（rec_br_train）が存在しません“
               ”スクリプトフアイルのロードに失败レまレた“   
大意”脚本文件（.dat)中不存在所需的文件（rec_br_train)，加载脚本失败
正文读一段报错同上，.dat中不存在101_ev_ma00_1、br08_medic、br07_bed、br00_wakeup、br01_report、br08_medic、br07_bed，加载脚本失败（br00、br01、br08、br07循环报错）
附上报错脚本
[CScript.zip](https://github.com/user-attachments/files/16392329/CScript.zip)

**Comment by satan53x** [comment]
> 2.1有一个脚本无法提取文本报错如下

这个更新一下，修复了BUG。

> 2.2封包出现的问题，提取脚本用了Crass、GARbro。

这个你试试直接解包完就封，不修改脚本，封包正常吗？确定是封包还是文本问题。

**Comment by satan53x** [comment]
> 1.kaguya tblstr.arc格式 译文导入出现问题，翻译一句或者全文导入时显示“译文为空，不替换”，6月底左右还没这样，换电脑了，下的最新的出现这样的问题。

检查一下orig和trans的json里边的换行符是不是一致，不要\r\n和\n混用。
现在默认正则是\n转为了\r\n，要保留\n的话修改`10_search=^([\S\s]+)$`。
如果已经保留了\n还报错，就是不要勾选分割前替换。

**Comment by FFreQD** [comment]
> > 2.1有一个脚本无法提取文本报错如下
> 
> 这个更新一下，修复了BUG。
> 晚上回去测试下
> > 2.2封包出现的问题，提取脚本用了Crass、GARbro。
> 
> 这个你试试直接解包完就封，不修改脚本，封包正常吗？确定是封包还是文本问题。

就是解包完直接封包报错的

**Comment by satan53x** [comment]
新的包能用Garbro打开吗？

**Comment by FFreQD** [comment]
> 新的包能用Garbro打开吗？

能用Garbro打开，原脚本和重新封包脚本请看下
原来不能提文本的脚本可以提取了

**Comment by FFreQD** [comment]
> > 1.kaguya tblstr.arc格式 译文导入出现问题，翻译一句或者全文导入时显示“译文为空，不替换”，6月底左右还没这样，换电脑了，下的最新的出现这样的问题。
> 
> 检查一下orig和trans的json里边的换行符是不是一致，不要\r\n和\n混用。 现在默认正则是\n转为了\r\n，要保留\n的话修改`10_search=^([\S\s]+)$`。 如果已经保留了\n还报错，就是不要勾选分割前替换。
可以了
可能我对说明上存在误解，”原文中不要有/r/n“ 所以我把默认的/r/n改成了/n
还有导入的时候必须选截断，否则一进正文就程序停止工作，但是截断后部分文字显示不全，之前用limit_maxlen_json_gt.py能搞定，也改了几次maxlen，这次不知道咋回事，是不是游戏的问题，每行字数都有限制？

**Comment by satan53x** [comment]
> 可能我对说明上存在误解，”原文中不要有/r/n“ 所以我把默认的/r/n改成了/n

因为\r\n是默认的段落分隔符，竹子的原文中其实是\n，不冲突，不用自己改。
如果需要截断的情况下，最好还是用这个`10_search=^([\S\s]+)$`，这样能保留\n，不然\n会被`10_search=(?P<unfinish>.+)`转为\r\n。（截断的时候转了\r\n就会分别计算每一句的字节长度，而不是整段）

**Comment by satan53x** [comment]
> 能用Garbro打开，原脚本和重新封包脚本请看下
> [scr.zip](https://github.com/user-attachments/files/16401039/scr.zip)

写入格式是正常的，只是python列举文件名的顺序和windows不一样，我改成日文环境系统排序了，现在封包回去二进制对比是一样的。
不知道为啥文件写入顺序也会有影响？按理说它这个包结构设计应该不影响的。
你更新下打包脚本试试。
需要用windows运行py才能和原始顺序一样，且安装依赖模块`pip install natsort`。

**Comment by FFreQD** [comment]
> > 能用Garbro打开，原脚本和重新封包脚本请看下
> > [scr.zip](https://github.com/user-attachments/files/16401039/scr.zip)
> 
> 写入格式是正常的，只是python列举文件名的顺序和windows不一样，我改成日文环境系统排序了，现在封包回去二进制对比是一样的。 不知道为啥文件写入顺序也会有影响？按理说它这个包结构设计应该不影响的。 你更新下打包脚本试试。 需要用windows运行py才能和原始顺序一样，且安装依赖模块`pip install natsort`。

封的时候报错，是因为我离线安装依赖natsort的原因吗
Traceback (most recent call last):
  File "F:\728\SExtractor-main\tools\CScript\dat_pack.py", line 119, in <module>
    main()
  File "F:\728\SExtractor-main\tools\CScript\dat_pack.py", line 116, in main
    files = listFiles(path)
  File "F:\728\SExtractor-main\tools\CScript\dat_pack.py", line 68, in listFiles
    locale.setlocale(locale.LC_ALL, 'ja_JP')
  File "D:\Python\Python311\Lib\locale.py", line 627, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

**Comment by FFreQD** [comment]
> > 能用Garbro打开，原脚本和重新封包脚本请看下
> > [scr.zip](https://github.com/user-attachments/files/16401039/scr.zip)
> 
> 写入格式是正常的，只是python列举文件名的顺序和windows不一样，我改成日文环境系统排序了，现在封包回去二进制对比是一样的。 不知道为啥文件写入顺序也会有影响？按理说它这个包结构设计应该不影响的。 你更新下打包脚本试试。 需要用windows运行py才能和原始顺序一样，且安装依赖模块`pip install natsort`。

封的时候报错，是因为我离线安装依赖natsort的原因吗
Traceback (most recent call last):
  File "F:\728\SExtractor-main\tools\CScript\dat_pack.py", line 119, in <module>
    main()
  File "F:\728\SExtractor-main\tools\CScript\dat_pack.py", line 116, in main
    files = listFiles(path)
  File "F:\728\SExtractor-main\tools\CScript\dat_pack.py", line 68, in listFiles
    locale.setlocale(locale.LC_ALL, 'ja_JP')
  File "D:\Python\Python311\Lib\locale.py", line 627, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

**Comment by satan53x** [comment]
不是natsort的问题，这是python内置模块locale报的错，不确定是不是版本不同。
你把报错这个68行的`'ja_JP'`改成`'Japanese_Japan.932'`试试呢。

**Comment by FFreQD** [comment]
> 不是natsort的问题，这是python内置模块locale报的错，不确定是不是版本不同。 你把报错这个68行的`'ja_JP'`改成`'Japanese_Japan.932'`试试呢。

大佬牛批，可以了，文本要截断否则报错
