### ISSUE TITLE
请问仕舞妻 ～姉妹妻3～的码表和仕舞妻マリッジディスク 仕舞妻ぶぶづけ是通用的吗？

### ISSUE THREAD

**Issue by MIB000** [satan53x/SExtractor#96]
还是说需要重新制作码表？

**Comment by satan53x** [comment]
不清楚，你上传Seen.txt包看看呢

**Comment by MIB000** [comment]
[SEEN.TXT](https://github.com/user-attachments/files/16530077/SEEN.TXT)

**Comment by satan53x** [comment]
不是同一个码表，需要自己找下。
可以用seen2000.txt来找，找游戏里这句话的前边一句。
```
【天の声】「彼はそこで、画家の妻である大原葵に一目ぼれする」
```

**Comment by MIB000** [comment]
好的！ 非常感谢！
