### ISSUE TITLE
config.ini文件添加无效 文档修改建议

### ISSUE THREAD

**Issue by beef-potato** [satan53x/SExtractor#98]
我是新人，今天尝试 sextractor,。 解包，写正则都很方便，一直到回填的时候我就不知道该怎么做了。ui和说明里写了*提取/写入*，但是没说明要把翻译后的文件放到 `trans`文件夹里，我一开始以为要自己写回填脚本，但是看issue至少6个提到了SExtractor自己有这个功能。于是重读了好几遍说明才发觉要自己主动移动文件。我觉得这一点可以在说明里提一下， 输出文件夹和译文输入用 `>>` 连接也有点不明所以，（我还没全翻译，单纯改几行字测试一下）。

----

然后是说明里提到程序会读取 config*ini, 我将自己的正则添加到 config.ini， 并放到 ctrl 文件夹下，但是我自定义正则没有出现。

```
[Krkr_Reg AKABEiSOFT3]
00_skip=^@(?!(?:nm|btt|saudio)).*$
01_skip=^[*;]
10_search=^@nm\s*t="(?P<name>.+?)".*$
11_search=^@saudio\s*t="(?P<name>.+?)".*?front="(?P<message1>.+?)".+?back="(?P<message2>.+?)"$
12_search=^@btt x=\d*\s*y=\d* graphic="sp_branch1_(.*?)" .*
endStr=np
ctrlStr=^[A-Za-z]
```

使用_custom()，可以保存，

```
前面省略...

mainDirPath=D:/games/Teakamamire no Danshi/scenario
reg__Custom0="00_skip=^@(?!(?:nm|btt|saudio)).*$\n01_skip=^[*;]\n10_search=^@nm\\s*t=\"(?P<name>.+?)\".*$\n11_search=^@saudio\\s*t=\"(?P<name>.+?)\".*?front=\"(?P<message1>.+?)\".+?back=\"(?P<message2>.+?)\"$\n12_search=^@btt x=\\d*\\s*y=\\d* graphic=\"sp_branch1_(.*?)\" .*\nendStr=np\nctrlStr=^[A-Za-z]\n"
windowSize=@Size(750 650)
Engine_Krkr_Reg_nameList=akabeisoft
```
![sex2](https://github.com/user-attachments/assets/1819e9e0-a379-4008-9a00-410635a9727a)
![image](https://github.com/user-attachments/assets/81ec4407-c9f5-4062-ae4c-3ef492adc0ab)

**Comment by satan53x** [comment]
config*.ini不是放置正则的文件，是缓存文件，可以缓存你所有设置，包括各种勾选。
一般不需要主动编辑这个ini，而是在界面上选custom就会缓存到ini里。
只是ini文件位置默认是先读取ctrl目录下的，再读取SE目录的main文件夹下，两个位置都有效。

**Comment by satan53x** [comment]
config.ini并不会修改GUI界面里下拉框选项，那个是读取的配置SE目录下src/reg.ini，如果有需要你可以把上边那个正则复制到这里边去。（但是复制到这个ini里的话，需要转义一下正则里的`\`，变成`\\`）
