### ISSUE TITLE
CScript选项提取不完整。

### ISSUE THREAD

**Issue by PiDanShouRouZhouXD** [satan53x/SExtractor#99]
![image](https://github.com/user-attachments/assets/de7b39cd-f3b7-4c9f-8a22-84a7052ec21e)
另外，可能是由于选项不完整，选择任意选项后会直接导致游戏退出。
请问可能是由于什么原因？

**Comment by PiDanShouRouZhouXD** [comment]
[script.zip](https://github.com/user-attachments/files/16579834/script.zip)
您看下，感谢

**Comment by satan53x** [comment]
更新了，选项也确实有问题，3个选项的第3个提取不到，也修正了。
只有选项不同，不需要重翻，手动在trans中加上缺少的那个也行。

**Comment by satan53x** [comment]
不过我没游戏测试，你试下跳转地址的自动修正正不正常呢。

**Comment by PiDanShouRouZhouXD** [comment]
> 不过我没游戏测试，你试下跳转地址的自动修正正不正常呢。

![image](https://github.com/user-attachments/assets/6bebabf0-cf08-4a60-bc0d-530a1e41cd49)
![image](https://github.com/user-attachments/assets/81473c3a-eda4-47a5-b45e-3a88e55b4e80)

过了一句话之后还是会报错

**Comment by satan53x** [comment]
看了下剧本文件，好像你这个游戏除了选项跳转之外，还有没有选项的情况下也会跳转，你把剧本用解密脚本解密之后搜`SEL_`关键字就能看到，那3个选项之后第二句后边就有。

**Comment by satan53x** [comment]
更新了常规跳转的修正，需要加入fixJump参数：extraData=compress,fixJump
打开debug信息可以看到打印。
分支跳转修正是强制开启的，不加入fixJump也会进行修正。

**Comment by PiDanShouRouZhouXD** [comment]
> 更新了常规跳转的修正，需要加入fixJump参数：extraData=compress,fixJump 打开debug信息可以看到打印。（只允许跳转字符串是ascii字符串） 分支跳转修正是强制开启的，不加入fixJump也会进行修正。

感谢，我尝试一下。

**Comment by satan53x** [comment]
可以再更新一下，扩大了最大的选项数量和跳转分支数量。

**Comment by PiDanShouRouZhouXD** [comment]
> 可以再更新一下，扩大了最大的选项数量和跳转分支数量。

测试了一部分，目前看来是修好了，非常感谢。

**Comment by PiDanShouRouZhouXD** [comment]
还是有bug：
![image](https://imgos.cn/2024/08/13/66baf3f60db2f.png)
还是有选项没提取到
比如rec02_04的   背筋を駆け抜ける射精感に譲二は悶え、絶頂へと向かっていく。   的后面，有个选项：
麻衣の口に出す
麻衣の顔に出す
好像hs的选项都没翻到。

**Comment by satan53x** [comment]
按理说没提取到最多乱码吧，不应该报错啊。
你这个应该是选项指令不一样，你这游戏咋这么多指令啊，一般来说一个游戏同类型指令都是一样的。
你在.py里边355行，把`[0x15,0x1A], dealSel0,`里边加上个0x16应该就能读取到了。
我待会儿把ctrlStr改成json字符串读取，就不用改脚本了。

**Comment by satan53x** [comment]
https://github.com/satan53x/SExtractor/issues/115
